from module_troops_utils import *

troops_outlaws = [
    [
        "looter",
        "Looter",
        "Looters",
        tf_guarantee_armor | tf_guarantee_boots,
        0,
        0,
        fac_outlaws,
        [
            itm_tab_shield_round_a,
            itm_tab_shield_tauria_a,
            itm_falchion_b,
            itm_falchion_b_v1,
            itm_falchion_b_v2,
            itm_mace_a,
            itm_pickaxe_a,
            itm_military_pick_a,
            itm_boar_spear,
            itm_arming_cap_a,
            itm_felt_a_v2,
            itm_padded_coif_b,
            itm_padded_coif_b_v1,
            itm_cervelliere_a,
            itm_cervelliere_b,
            (itm_peasant_regular_shirt_a, 0),
            (itm_peasant_regular_shirt_a_v1, 0),
            (itm_leather_vest_regular_shirt_a, 0),
            (itm_leather_vest_regular_shirt_a_v1, 0),
            itm_leather_gloves_a,
            itm_hose_b,
            itm_poulaines_b,
        ],
        def_attrib | level(5),
        wp(60),
        knows_common,
        bandit_face1,
        bandit_face2,
    ],
    [
        "bandit",
        "Bandit",
        "Bandits",
        tf_guarantee_armor | tf_guarantee_boots,
        0,
        0,
        fac_outlaws,
        [
            itm_tab_shield_tauria_a,
            itm_tab_shield_heater_a,
            itm_hunting_crossbow,
            itm_bolts,
            itm_falchion_b_v2,
            itm_sword_short_a,
            itm_sword_short_b_v1,
            itm_spear_a,
            itm_spear_b,
            itm_mace_b,
            itm_mace_b_v1,
            itm_sallet_a_v1,
            itm_chapel_a_v1,
            itm_eyeslot_kettlehat_a_v1,
            itm_cervelliere_a,
            itm_cervelliere_b,
            (itm_outlaw_leather_armor_a, 0),
            (itm_outlaw_leather_armor_a, imod_thick),
            (itm_outlaw_leather_armor_a, imod_hardened),
            (itm_outlaw_leather_armor_a, imod_reinforced),
            itm_leather_gloves_a,
            itm_leather_boots_a,
            itm_leather_boots_b,
            itm_hose_b,
            itm_poulaines_b,
        ],
        def_attrib | level(10),
        wp(90),
        knows_common | knows_power_draw_1,
        bandit_face1,
        bandit_face2,
    ],
    [
        "pillager",
        "Pillager",
        "Pillagers",
        tf_guarantee_all,
        0,
        0,
        fac_outlaws,
        [
            itm_sword_a,
            itm_mace_b,
            itm_crossbow,
            itm_bolts,
            itm_spear,
            itm_sallet_a_v2,
            itm_chapel_a_v2,
            (itm_brown_hauberk_a, 0),
            (itm_brown_hauberk_a, imod_thick),
            (itm_brown_hauberk_a, imod_hardened),
            itm_leather_gloves_a,
            itm_hose_b,
            itm_poulaines_b,
        ],
        def_attrib | level(15),
        wp(120),
        knows_common | knows_power_draw_1 | knows_ironflesh_2 | knows_power_strike_2,
        bandit_face1,
        bandit_face2,
    ],
    [
        "marauder",
        "Marauder",
        "Marauders",
        tf_guarantee_all,
        0,
        0,
        fac_outlaws,
        [
            itm_polearm_light_halberd_a,
            itm_polearm_light_voulge_a,
            itm_polearm_light_voulge_b,
            itm_spear_a_v1,
            itm_spear_b_v1,
            itm_sallet_a_v2,
            itm_sallet_d_v2,
            (itm_brown_hauberk_a, 0),
            (itm_brown_hauberk_a, imod_thick),
            (itm_brown_hauberk_a, imod_hardened),
            itm_leather_gloves_a,
            itm_hose_b,
            itm_poulaines_b,
        ],
        def_attrib | level(15),
        wp(125),
        knows_common | knows_power_draw_1 | knows_power_strike_2 | knows_ironflesh_4,
        bandit_face1,
        bandit_face2,
    ],
    [
        "outlaw",
        "Outlaw",
        "Outlaws",
        tf_guarantee_all,
        0,
        0,
        fac_outlaws,
        [
            itm_spear,
            itm_sword_a,
            itm_hunting_crossbow,
            itm_bolts,
            itm_tab_shield_small_round_a,
            itm_tab_shield_small_round_b,
            itm_sallet_a_v2,
            itm_sallet_d_v2,
            (itm_regular_leather_jerkin_a, 0),
            (itm_regular_leather_jerkin_b, 0),
            itm_leather_gloves_a,
            itm_leather_boots_a,
            itm_saddle_horse,
        ],
        def_attrib | level(10),
        wp(90),
        knows_common | knows_riding_2,
        bandit_face1,
        bandit_face2,
    ],
    [
        "highwayman",
        "Highwayman",
        "Highwaymen",
        tf_guarantee_all,
        0,
        0,
        fac_outlaws,
        [
            itm_lance,
            itm_sword_a,
            itm_axe_a,
            itm_hunting_crossbow,
            itm_bolts,
            itm_tab_shield_small_round_c,
            itm_sallet_a_v3,
            itm_sallet_d_v3,
            (itm_outlaw_leather_armor_a, 0),
            (itm_outlaw_leather_armor_a, imod_thick),
            (itm_ragged_outfit_aketon_a, imod_thick),
            (itm_ragged_outfit_coat_a, 0),
            (itm_ragged_outfit_coat_a, imod_hardened),
            itm_leather_gloves_a,
            itm_leather_boots_a,
            itm_mail_boots_a,
            itm_saddle_horse,
        ],
        def_attrib | level(15),
        wp(120),
        knows_common | knows_riding_5 | knows_power_strike_4,
        bandit_face1,
        bandit_face2,
    ],
    [
        "bandit_lord",
        "Bandit Lord",
        "Bandit Lords",
        tf_guarantee_all,
        0,
        0,
        fac_outlaws,
        [
            itm_lance,
            itm_lance_a,
            itm_sword_great_a,
            itm_hunting_crossbow,
            itm_bolts,
            itm_tab_shield_small_round_c,
            itm_sallet_a_v4,
            itm_sallet_a_v5,
            itm_great_helmet_heretics,
            (itm_mercenary_brigandine_a, 0),
            (itm_mercenary_brigandine_b, 0),
            (itm_mercenary_brigandine_c, 0),
            itm_leather_gloves_a,
            itm_mail_mittens_a,
            itm_plate_gauntlets_a,
            itm_leather_boots_a,
            itm_mail_boots_a,
            itm_plate_boots_b,
            itm_warhorse,
        ],
        knight_attrib_5 | level(25),
        wp(245),
        knows_common
        | knows_power_draw_1
        | knows_riding_5
        | knows_ironflesh_10
        | knows_power_strike_6,
        bandit_face1,
        bandit_face2,
    ],
    [
        "coastal_bandit",
        "Coastal Bandit",
        "Coastal Bandits",
        tf_guarantee_boots
        | tf_guarantee_armor
        | tf_guarantee_shield
        | tf_guarantee_helmet,
        0,
        0,
        fac_outlaws,
        [
            itm_arrows,
            itm_hunting_bow,
            itm_hatchet_a,
            itm_hatchet_b,
            itm_polearm_military_scythe_a,
            itm_long_pole_mace_a,
            itm_m_plain_round_shield_a,
            itm_felt_b_v1,
            itm_hood_a,
            itm_mail_coif_a_v2,
            itm_flat_top_a_v1,
            itm_flat_top_b_v1,
            itm_ragged_outfit_aketon_a,
            itm_leather_gloves_a,
            itm_mail_mittens_a,
            itm_hose_b,
            itm_poulaines_b,
            itm_leather_boots_b,
        ],
        def_attrib | level(15),
        wp(110),
        knows_ironflesh_2
        | knows_power_strike_2
        | knows_power_draw_2
        | knows_power_throw_2,
        bandit_face1,
        bandit_face2,
    ],
    [
        "scavenger",
        "Scavenger",
        "Scavengers",
        tf_guarantee_boots
        | tf_guarantee_armor
        | tf_guarantee_shield
        | tf_guarantee_helmet,
        0,
        0,
        fac_outlaws,
        [
            itm_sword_a,
            itm_sword_a_v1,
            itm_sword_short_a,
            itm_sword_short_a_v1,
            itm_mace_b,
            itm_mace_b_v1,
            itm_polearm_light_voulge_b,
            itm_tab_shield_tauria_a,
            itm_chapel_a_v2,
            itm_chapel_b_v2,
            itm_morion_a_v2,
            itm_eyeslot_kettlehat_a_v2,
            (itm_scarlet_aketon_a, 0),
            (itm_scarlet_aketon_a_v1, 0),
            itm_leather_gloves_a,
            itm_hose_d,
            itm_poulaines_d,
            itm_leather_boots_a,
        ],
        def_attrib | level(15),
        wp(110),
        knows_ironflesh_2 | knows_power_strike_2 | knows_athletics_3,
        bandit_face1,
        bandit_face2,
    ],
    [
        "scavenger_brute",
        "Scavenger Brute",
        "Scavenger Brutes",
        tf_guarantee_boots
        | tf_guarantee_armor
        | tf_guarantee_gloves
        | tf_guarantee_helmet,
        0,
        0,
        fac_outlaws,
        [
            itm_two_handed_axe,
            itm_two_handed_battle_axe_2,
            itm_sword_short_a,
            itm_sword_short_a_v1,
            itm_mace_b_v2,
            itm_tab_shield_tauria_a,
            itm_chapel_a_v2,
            itm_chapel_b_v2,
            itm_morion_a_v2,
            itm_eyeslot_kettlehat_a_v2,
            (itm_scarlet_aketon_a, imod_hardened),
            (itm_scarlet_aketon_a_v1, imod_hardened),
            itm_leather_gloves_a,
            itm_leather_gloves_a_v1,
            itm_mail_mittens_a,
            itm_leather_boots_a,
            itm_mail_boots_a,
        ],
        def_attrib | level(20),
        wp(160),
        knows_ironflesh_4 | knows_power_strike_4 | knows_athletics_4,
        bandit_face1,
        bandit_face2,
    ],
    [
        "scavenger_shock_trooper",
        "Scavenger Shock Trooper",
        "Scavenger Shock Troopers",
        tf_guarantee_boots
        | tf_guarantee_armor
        | tf_guarantee_gloves
        | tf_guarantee_helmet
        | tf_guarantee_shield,
        0,
        0,
        fac_outlaws,
        [
            itm_two_handed_axe,
            itm_two_handed_battle_axe_2,
            itm_sword_great_a,
            itm_sword_great_a_v1,
            itm_mace_b_v2,
            itm_tab_shield_heater_b,
            itm_tab_shield_heater_c,
            itm_chapel_a_v2,
            itm_chapel_b_v2,
            itm_morion_a_v2,
            itm_eyeslot_kettlehat_a_v2,
            (itm_scarlet_aketon_a, imod_reinforced),
            (itm_scarlet_aketon_a_v1, imod_reinforced),
            itm_leather_gloves_a,
            itm_leather_gloves_a_v1,
            itm_mail_mittens_a,
            itm_leather_boots_a,
            itm_mail_boots_a,
        ],
        def_attrib | level(24),
        wp(240),
        knows_ironflesh_5 | knows_power_strike_5 | knows_athletics_5,
        bandit_face1,
        bandit_face2,
    ],
    [
        "scavenger_crossbowman",
        "Scavenger Crossbowman",
        "Scavenger Crossbowmen",
        tf_guarantee_boots
        | tf_guarantee_armor
        | tf_guarantee_gloves
        | tf_guarantee_helmet
        | tf_guarantee_ranged,
        0,
        0,
        fac_outlaws,
        [
            itm_bolts,
            itm_light_crossbow,
            itm_crossbow,
            itm_sword_short_a,
            itm_sword_short_a_v1,
            itm_mace_b_v2,
            itm_hood_a,
            itm_hood_b,
            itm_morion_a_v2,
            itm_eyeslot_kettlehat_a_v2,
            (itm_scarlet_aketon_a, imod_hardened),
            (itm_scarlet_aketon_a_v1, imod_hardened),
            itm_leather_gloves_a,
            itm_hose_d,
            itm_poulaines_d,
            itm_leather_boots_a,
        ],
        def_attrib | level(20),
        wp(160),
        knows_ironflesh_4 | knows_power_strike_4 | knows_athletics_4,
        bandit_face1,
        bandit_face2,
    ],
    [
        "cultist_acolyte",
        "Twilight Veil Acolyte",
        "Twilight Veil Acolytes",
        tf_guarantee_all,
        0,
        0,
        fac_outlaws,
        [
            itm_leather_gloves_a_v1,
            itm_robe,
            itm_pilgrim_disguise,
            itm_pilgrim_hood,
            itm_studded_club_a,
            itm_pickaxe_a_v1,
            itm_one_handed_battle_axe_c,
            itm_tab_shield_pavise_a,
            itm_leather_boots_a,
            itm_leather_boots_b,
        ],
        def_attrib | str_15 | agi_15 | level(12),
        wp(100),
        knows_common | knows_ironflesh_3,
        bandit_face1,
        bandit_face2,
    ],
    [
        "dark_cultist",
        "Twilight Veil Cultist",
        "Twilight Veil Cultists",
        tf_guarantee_boots | tf_guarantee_armor,
        0,
        0,
        fac_outlaws,
        [
            itm_mail_mittens_a_v1,
            itm_robe,
            itm_pilgrim_disguise,
            itm_pilgrim_hood,
            itm_winged_mace,
            itm_morningstar,
            itm_one_handed_battle_axe_c,
            itm_tab_shield_pavise_a,
            itm_mail_boots_a,
        ],
        def_attrib | str_15 | agi_15 | level(17),
        wp(140),
        knows_common | knows_ironflesh_3,
        bandit_face1,
        bandit_face2,
    ],
    [
        "occultist",
        "Twilight Veil Occultist",
        "Twilight Veil Occultists",
        tf_guarantee_boots
        | tf_guarantee_armor
        | tf_guarantee_helmet
        | tf_guarantee_gloves,
        0,
        0,
        fac_outlaws,
        [
            itm_mail_mittens_a_v1,
            itm_robe,
            itm_pilgrim_disguise,
            itm_winged_mace,
            itm_morningstar,
            itm_one_handed_battle_axe_c,
            itm_tab_shield_pavise_a,
            itm_tab_shield_pavise_b,
            itm_mail_boots_a,
        ],
        def_attrib | str_20 | agi_20 | level(24),
        wp(240),
        knows_common | knows_ironflesh_5,
        bandit_face1,
        bandit_face2,
    ],
    [
        "veilweaver",
        "Veilweaver",
        "Veilweavers",
        tf_guarantee_boots
        | tf_guarantee_armor
        | tf_guarantee_helmet
        | tf_guarantee_gloves,
        0,
        0,
        fac_outlaws,
        [
            itm_mail_mittens_a_v1,
            itm_robe_on_mail_a,
            itm_robe_on_mail_b,
            itm_winged_mace,
            itm_morningstar,
            itm_one_handed_battle_axe_c,
            itm_tab_shield_pavise_c,
            itm_tab_shield_pavise_b,
            itm_mail_boots_a,
        ],
        def_attrib | str_26 | agi_25 | level(28),
        wp(320),
        knows_common | knows_ironflesh_10 | knows_power_strike_8,
        bandit_face1,
        bandit_face2,
    ],
    [
        "veiled_inquisitor",
        "Veiled Inquisitor",
        "Veiled Inquisitors",
        tf_mounted
        | tf_guarantee_horse
        | tf_guarantee_boots
        | tf_guarantee_armor
        | tf_guarantee_helmet
        | tf_guarantee_gloves,
        0,
        0,
        fac_outlaws,
        [
            itm_robe_on_mail_a,
            itm_robe_on_mail_b,
            itm_great_helmet_heretics,
            itm_winged_mace,
            itm_morningstar,
            itm_one_handed_battle_axe_c,
            itm_lance,
            itm_tab_shield_tauria_a,
            itm_black_knight_horse_a,
            itm_mail_boots_a,
        ],
        def_attrib | str_30 | agi_25 | level(28),
        wp(320),
        knows_common | knows_ironflesh_10 | knows_power_strike_8,
        bandit_face1,
        bandit_face2,
    ],
    [
        "dwelling_undead",
        "Dwelling Undead",
        "Dwelling Undead",
        tf_awakened | tf_guarantee_boots | tf_guarantee_armor,
        0,
        0,
        fac_undeads,
        [
            itm_falchion_b,
            itm_falchion_b_v1,
            itm_falchion_b_v2,
            itm_spear_b,
            itm_hatchet_a,
            itm_hatchet_b,
            itm_military_pick_a,
            itm_tab_shield_small_round_a,
            itm_tab_shield_heater_a,
            itm_tab_shield_pavise_a,
            itm_stones,
            itm_sallet_a_v1,
            itm_morion_a_v1,
            itm_eyeslot_kettlehat_a_v1,
            itm_arming_cap_a,
            itm_felt_a_v1,
            (itm_ragged_outfit_aketon_a, 0),
            (itm_ragged_outfit_coat_a, 0),
            itm_leather_gloves_a,
            itm_hose_b,
            itm_poulaines_b,
        ],
        def_attrib | level(20),
        wp(150),
        knows_common | knows_ironflesh_5 | knows_power_strike_5,
        skeleton_face1,
        skeleton_face1,
    ],
    [
        "brigand",
        "Brigand",
        "Brigands",
        tf_mounted | tf_guarantee_boots | tf_guarantee_armor | tf_guarantee_horse,
        0,
        0,
        fac_outlaws,
        [
            itm_arrows,
            itm_spiked_mace,
            itm_sword_a,
            itm_falchion_a,
            itm_wooden_shield,
            itm_hide_covered_round_shield,
            itm_long_bow,
            itm_arming_cap_a,
            itm_regular_leather_jerkin_a,
            itm_leather_boots_a,
            itm_saddle_horse,
        ],
        def_attrib | level(16),
        wp(90),
        knows_common | knows_power_draw_3,
        bandit_face1,
        bandit_face2,
    ],
    [
        "mountain_bandit",
        "Mountain Bandit",
        "Mountain Bandits",
        tf_guarantee_armor | tf_guarantee_boots,
        0,
        0,
        fac_outlaws,
        [
            itm_arrows,
            itm_short_bow,
            itm_hunting_bow,
            itm_javelin,
            itm_sword_a,
            itm_boar_spear,
            itm_hatchet_b,
            itm_hatchet_b_v1,
            itm_military_pick_a_v1,
            itm_military_pick_a_v2,
            itm_falchion_a,
            itm_spiked_club,
            itm_mace_a,
            itm_fur_covered_shield,
            itm_hide_covered_round_shield,
            itm_mail_coif_a,
            itm_flat_top_a_v1,
            itm_flat_top_b_v1,
            itm_hood_a,
            itm_hood_b,
            itm_byrnie_a,
            itm_shirt_a_v2,
            itm_shirt_b_v2,
            itm_shirt_b_v3,
            itm_shirt_b_v4,
            itm_leather_boots_a,
            itm_mail_boots_a,
        ],
        def_attrib | level(11),
        wp(90),
        knows_common | knows_power_draw_2 | knows_power_throw_2,
        rhodok_face_young_1,
        rhodok_face_old_2,
    ],
    [
        "mountain_bandit_warrior",
        "Mountain Bandit Warrior",
        "Mountain Bandit Warriors",
        tf_guarantee_armor
        | tf_guarantee_boots
        | tf_guarantee_helmet
        | tf_guarantee_gloves,
        0,
        0,
        fac_outlaws,
        [
            itm_arrows,
            itm_long_bow,
            itm_javelin,
            itm_sword_a,
            itm_boar_spear,
            itm_military_pick_a_v1,
            itm_military_pick_a_v2,
            itm_mace_b,
            itm_tab_shield_round_b,
            itm_tab_shield_round_c,
            itm_mail_coif_a,
            itm_flat_top_a_v2,
            itm_flat_top_b_v2,
            itm_byrnie_a,
            itm_mail_shirt_a,
            itm_mail_shirt_a_v1,
            itm_leather_gloves_a,
            itm_mail_mittens_a,
            itm_leather_boots_a,
            itm_mail_boots_a,
        ],
        def_attrib | level(15),
        wp(125),
        knows_common | knows_power_draw_3 | knows_power_throw_3,
        rhodok_face_young_1,
        rhodok_face_old_2,
    ],
    [
        "forest_bandit",
        "Forest Bandit",
        "Forest Bandits",
        tf_guarantee_armor | tf_guarantee_ranged | tf_guarantee_boots,
        0,
        0,
        fac_outlaws,
        [
            itm_arrows,
            itm_hunting_bow,
            itm_cudgel,
            itm_wooden_stick,
            itm_hatchet_a,
            itm_hatchet_b,
            itm_mace_1,
            itm_pilgrim_hood,
            itm_hood_a,
            itm_hood_b,
            itm_felt_b,
            itm_felt_b_v1,
            (itm_thick_coat_a, 0),
            (itm_thick_coat_a_v1, 0),
            (itm_thick_coat_b, 0),
            (itm_thick_coat_b_v1, 0),
            (itm_gambeson_b, 0),
            itm_leather_gloves_a,
            itm_hose_b,
            itm_poulaines_b,
        ],
        def_attrib | level(11),
        wp(90),
        knows_common | knows_power_draw_3,
        swadian_face_young_1,
        swadian_face_old_2,
    ],
    [
        "forest_outlaw",
        "Forest Outlaw",
        "Forest Outlaws",
        tf_guarantee_armor | tf_guarantee_ranged | tf_guarantee_boots,
        0,
        0,
        fac_outlaws,
        [
            itm_arrows,
            itm_hunting_bow,
            itm_cleaver_a,
            itm_cleaver_c,
            itm_pilgrim_hood,
            itm_hood_a,
            itm_hood_b,
            itm_mail_coif_a,
            itm_mail_coif_a_v2,
            itm_mail_coif_a_v3,
            (itm_gambeson_a, 0),
            (itm_byrnie_a, 0),
            (itm_hauberk_a, 0),
            (itm_hauberk_a, imod_hardened),
            itm_leather_gloves_a,
            itm_mail_mittens_a,
            itm_leather_boots_a,
            itm_mail_boots_a,
        ],
        def_attrib | level(15),
        wp(125),
        knows_common | knows_power_draw_3,
        swadian_face_young_1,
        swadian_face_old_2,
    ],
    [
        "sea_raider",
        "Sea Raider",
        "Sea Raiders",
        tf_guarantee_boots | tf_guarantee_armor | tf_guarantee_shield,
        0,
        0,
        fac_outlaws,
        [
            itm_arrows,
            itm_sword_a,
            itm_sword_a_v1,
            itm_fighting_axe,
            itm_battle_axe,
            itm_spear,
            itm_war_spear,
            itm_tab_shield_round_b,
            itm_tab_shield_round_c,
            itm_long_bow,
            itm_javelin,
            itm_throwing_axes,
            itm_nasal_helmet_a_v1,
            itm_nasal_helmet_b_v1,
            itm_byrnie_a,
            itm_shirt_a_v1,
            itm_shirt_a_v2,
            itm_leather_gloves_a,
            itm_leather_boots_a,
            itm_leather_boots_b,
            itm_mail_boots_a,
        ],
        def_attrib | level(16),
        wp(110),
        knows_ironflesh_2
        | knows_power_strike_2
        | knows_power_draw_3
        | knows_power_throw_2
        | knows_riding_1
        | knows_athletics_2,
        nord_face_young_1,
        nord_face_old_2,
    ],
    [
        "sea_raider_warlord",
        "Sea Raider Warlord",
        "Sea Raider Warlords",
        tf_guarantee_boots
        | tf_guarantee_armor
        | tf_guarantee_shield
        | tf_guarantee_helmet,
        0,
        0,
        fac_outlaws,
        [
            itm_arrows,
            itm_sword_a,
            itm_sword_a_v1,
            itm_fighting_axe,
            itm_battle_axe,
            itm_spear,
            itm_war_spear,
            itm_tab_shield_round_b,
            itm_tab_shield_round_c,
            itm_long_bow,
            itm_javelin,
            itm_throwing_axes,
            itm_nasal_helmet_a_v1,
            itm_nasal_helmet_b_v1,
            itm_byrnie_a,
            itm_mail_shirt_a,
            itm_mail_shirt_a_v1,
            itm_leather_gloves_a,
            itm_mail_mittens_a,
            itm_leather_boots_a,
            itm_mail_boots_a,
            itm_mail_boots_b,
            itm_mail_boots_c,
        ],
        def_attrib | level(22),
        wp(180),
        knows_ironflesh_4
        | knows_power_strike_4
        | knows_power_draw_4
        | knows_power_throw_3
        | knows_riding_2
        | knows_athletics_3,
        nord_face_young_1,
        nord_face_old_2,
    ],
    [
        "steppe_bandit",
        "Steppe Bandit",
        "Steppe Bandits",
        tf_guarantee_armor
        | tf_guarantee_horse
        | tf_guarantee_ranged
        | tf_guarantee_helmet
        | tf_mounted,
        0,
        0,
        fac_outlaws,
        [
            itm_arrows,
            itm_falchion_a,
            itm_winged_mace,
            itm_spear,
            itm_light_lance,
            itm_nomad_bow,
            itm_nomad_bow,
            itm_short_bow,
            itm_jarid,
            itm_leather_covered_round_shield,
            itm_leather_covered_round_shield,
            itm_leather_boots_a,
            itm_saddle_horse,
            itm_steppe_horse,
            itm_steppe_horse,
        ],
        def_attrib | level(12),
        wp(100),
        knows_riding_4 | knows_horse_archery_3 | knows_power_draw_3,
        khergit_face_young_1,
        khergit_face_old_2,
    ],
    [
        "steppe_bandit_warrior",
        "Steppe Warrior Bandit",
        "Steppe Warrior Bandits",
        tf_guarantee_boots
        | tf_guarantee_armor
        | tf_guarantee_horse
        | tf_guarantee_ranged
        | tf_guarantee_helmet
        | tf_mounted,
        0,
        0,
        fac_outlaws,
        [
            itm_arrows,
            itm_falchion_a,
            itm_falchion_a_v1,
            itm_winged_mace,
            itm_spear,
            itm_light_lance,
            itm_nomad_bow,
            itm_nomad_bow,
            itm_short_bow,
            itm_jarid,
            itm_leather_covered_round_shield,
            itm_leather_covered_round_shield,
            itm_leather_boots_a,
            itm_steppe_horse,
            itm_steppe_horse_b,
        ],
        def_attrib | level(15),
        wp(130),
        knows_riding_4 | knows_horse_archery_5 | knows_power_draw_5,
        khergit_face_young_1,
        khergit_face_old_2,
    ],
    [
        "steppe_bandit_leader",
        "Steppe Bandit Leader",
        "Steppe Bandit Leaders",
        tf_guarantee_boots
        | tf_guarantee_armor
        | tf_guarantee_horse
        | tf_guarantee_ranged
        | tf_guarantee_helmet
        | tf_mounted,
        0,
        0,
        fac_outlaws,
        [
            itm_khergit_arrows,
            itm_barbed_arrows,
            itm_falchion_a_v2,
            itm_falchion_b,
            itm_lance,
            itm_khergit_bow,
            itm_nomad_bow,
            itm_strong_bow,
            itm_jarid,
            itm_leather_covered_round_shield,
            itm_leather_covered_round_shield,
            itm_leather_boots_a,
            itm_steppe_horse,
            itm_steppe_horse_b,
        ],
        def_attrib | level(25),
        wp(230),
        knows_riding_6 | knows_horse_archery_6 | knows_power_draw_6 | knows_ironflesh_6,
        khergit_face_young_1,
        khergit_face_old_2,
    ],
    [
        "taiga_bandit",
        "Taiga Bandit",
        "Taiga Bandits",
        tf_guarantee_boots | tf_guarantee_armor | tf_guarantee_ranged,
        0,
        0,
        fac_outlaws,
        [
            itm_arrows,
            itm_falchion_a,
            itm_winged_mace,
            itm_spear,
            itm_light_lance,
            itm_nomad_bow,
            itm_nomad_bow,
            itm_short_bow,
            itm_jarid,
            itm_javelin,
            itm_pilgrim_hood,
            itm_hood_a,
            itm_hood_b,
            itm_felt_b_v1,
            itm_shirt_a,
            itm_shirt_a_v1,
            itm_shirt_b_v1,
            itm_shirt_b_v2,
            itm_leather_jerkin_a,
            itm_leather_covered_round_shield,
            itm_leather_covered_round_shield,
            itm_leather_boots_a,
            itm_poulaines_b,
        ],
        def_attrib | level(15),
        wp(110),
        knows_common | knows_power_draw_4 | knows_power_throw_3,
        vaegir_face_young_1,
        vaegir_face_old_2,
    ],
    [
        "taiga_bandit_cheiftain",
        "Taiga Bandit Chieftain",
        "Taiga Bandit Chieftains",
        tf_guarantee_boots
        | tf_guarantee_armor
        | tf_guarantee_ranged
        | tf_guarantee_helmet,
        0,
        0,
        fac_outlaws,
        [
            itm_arrows,
            itm_falchion_a_v1,
            itm_falchion_a_v2,
            itm_khergit_bow,
            itm_nomad_bow,
            itm_strong_bow,
            itm_jarid,
            itm_javelin,
            itm_leather_covered_round_shield,
            itm_leather_covered_round_shield,
            itm_facemask_a,
            itm_facemask_a_v1,
            itm_facemask_a_v2,
            itm_tundra_armor_a,
            itm_tundra_armor_a_v1,
            itm_tundra_armor_b,
            itm_tundra_armor_b_v1,
            itm_leather_gloves_a,
            itm_mail_mittens_a,
            itm_leather_boots_a,
            itm_mail_boots_b,
            itm_mail_boots_c,
        ],
        def_attrib | level(20),
        wp(160),
        knows_common | knows_power_draw_5 | knows_power_throw_4,
        vaegir_face_young_1,
        vaegir_face_old_2,
    ],
    [
        "desert_bandit",
        "Piaktu Bandit",
        "Piaktu Bandits",
        tf_guarantee_armor | tf_guarantee_helmet,
        0,
        0,
        fac_outlaws,
        [
            itm_arrows,
            itm_sword_b,
            itm_winged_mace,
            itm_spear,
            itm_jarid,
            itm_nomad_bow,
            itm_short_bow,
            itm_jarid,
            itm_leather_gloves_a,
            itm_leather_covered_round_shield,
            itm_leather_covered_round_shield,
        ],
        def_attrib | level(12),
        wp(100),
        knows_riding_4 | knows_power_draw_3,
        khergit_face_young_1,
        khergit_face_old_2,
    ],
    [
        "desert_bandit_master",
        "Piaktu Assasin",
        "Piaktu Assasins",
        tf_guarantee_armor | tf_guarantee_helmet,
        0,
        0,
        fac_outlaws,
        [
            itm_arrows,
            itm_sword_b,
            itm_sword_b_v1,
            itm_sword_b_v2,
            itm_jarid,
            itm_nomad_bow,
            itm_short_bow,
            itm_jarid,
            itm_leather_gloves_a,
            itm_solarian_oval_shield_a,
            itm_solarian_oval_shield_b,
            itm_solarian_round_shield_a,
            itm_solarian_round_shield_b,
        ],
        def_attrib | level(18),
        wp(160),
        knows_riding_4 | knows_power_draw_3,
        khergit_face_young_1,
        khergit_face_old_2,
    ],
    [
        "desert_bandit_horseman",
        "Piaktu Horseman",
        "Piaktu Horsemen",
        tf_guarantee_armor | tf_guarantee_helmet | tf_mounted | tf_guarantee_horse,
        0,
        0,
        fac_outlaws,
        [
            itm_sword_b,
            itm_sword_b_v1,
            itm_sword_b_v2,
            itm_mail_mittens_a,
            itm_leather_gloves_a_v1,
            itm_solarian_oval_shield_a,
            itm_solarian_oval_shield_b,
            itm_solarian_round_shield_a,
            itm_solarian_round_shield_b,
            itm_arabian_horse_a,
            itm_arabian_horse_b,
        ],
        def_attrib | level(21),
        wp(180),
        knows_riding_4 | knows_power_strike_3 | knows_ironflesh_4,
        khergit_face_young_1,
        khergit_face_old_2,
    ],
    [
        "desert_bandit_ronin",
        "Piaktu Ronin",
        "Piaktu Ronins",
        tf_guarantee_armor | tf_guarantee_helmet | tf_guarantee_gloves,
        0,
        0,
        fac_outlaws,
        [
            itm_khergit_sword_two_handed_a,
            itm_khergit_sword_two_handed_b,
        ],
        def_attrib | level(21),
        wp(180),
        knows_athletics_4 | knows_power_strike_3 | knows_ironflesh_5,
        khergit_face_young_1,
        khergit_face_old_2,
    ],
    [
        "desert_bandit_leader",
        "Piaktu Leader",
        "Piaktu Leaders",
        tf_guarantee_armor
        | tf_guarantee_helmet
        | tf_guarantee_gloves
        | tf_mounted
        | tf_guarantee_horse,
        0,
        0,
        fac_outlaws,
        [
            itm_khergit_sword_two_handed_a,
            itm_khergit_sword_two_handed_b,
            itm_sword_b_v4,
            itm_sword_b_v3,
            itm_sword_b_v2,
            itm_solarian_oval_shield_a,
            itm_solarian_oval_shield_b,
            itm_solarian_round_shield_a,
            itm_solarian_round_shield_b,
            itm_saracin_hard_horses_a,
            itm_saracin_hard_horses_d,
        ],
        def_attrib | level(27),
        wp(240),
        knows_riding_4 | knows_athletics_4 | knows_power_strike_3 | knows_ironflesh_5,
        khergit_face_young_1,
        khergit_face_old_2,
    ],
    [
        "black_celestial_armsman",
        "Black Khergit Horseman",
        "Black Khergit Horsemen",
        tf_mounted | tf_guarantee_boots | tf_guarantee_armor | tf_guarantee_horse,
        0,
        0,
        fac_black_khergits,
        [
            itm_arrows,
            itm_falchion_a_v1,
            itm_scimitar,
            itm_scimitar,
            itm_winged_mace,
            itm_spear,
            itm_lance,
            itm_khergit_bow,
            itm_khergit_bow,
            itm_nomad_bow,
            itm_nomad_bow,
            itm_steppe_cap,
            itm_khergit_war_helmet,
            itm_khergit_war_helmet,
            itm_white_hauberk_a,
            itm_plate_covered_round_shield,
            itm_plate_covered_round_shield,
            itm_saddle_horse,
            itm_steppe_horse,
            itm_leather_boots_a,
        ],
        def_attrib | level(21),
        wp(100),
        knows_riding_3 | knows_ironflesh_3 | knows_horse_archery_3 | knows_power_draw_3,
        khergit_face_young_1,
        khergit_face_old_2,
    ],
]
