from module_troops_utils import *

troops_pretenders = [
    [
        "kingdom_1_pretender",
        "Lady Rose Queen of the Silver",
        "Rose",
        tf_hero | tf_female | tf_unmoveable_in_party_window,
        0,
        reserved,
        fac_kingdom_1,
        [
            itm_charger,
            itm_rich_outfit,
            itm_poulaines_d,
            itm_tabard_v2,
            itm_mail_boots_a,
            itm_sword_medieval_c_small,
            itm_tab_shield_small_round_c,
            itm_silver_rose_scout_helmet_b,
        ],
        lord_attrib,
        wp(220),
        knight_skills_5,
        0x00000000EF0020000ED865C00A8516DB00000000001DB6C30000000000000000,
    ],
    # claims pre-salic descent
    [
        "kingdom_2_pretender",
        "Prince Oleh the Bastard",
        "Oleh",
        tf_hero | tf_unmoveable_in_party_window,
        0,
        reserved,
        fac_kingdom_2,
        [
            itm_hunter,
            itm_courtly_outfit,
            itm_poulaines_d,
            itm_chornovalley_mail_a,
            itm_mail_boots_b,
            itm_military_pick,
            itm_tab_shield_heater_b,
            itm_flat_topped_helmet,
        ],
        lord_attrib,
        wp(220),
        knight_skills_5,
        0x000000000810120436DB6DA9546DBEFF00000000001DB6F00000000000000000,
        vaegir_face_middle_2,
    ],
    # had his patrimony falsified
    [
        "kingdom_3_pretender",
        "King Solomon Blaze",
        "Solomon",
        tf_hero | tf_unmoveable_in_party_window,
        0,
        reserved,
        fac_kingdom_3,
        [
            itm_courser,
            itm_tabard_c,
            itm_poulaines_d,
            itm_m_celestial_plate_a,
            itm_plate_boots_a,
            itm_m_mace_knight,
            itm_tab_shield_small_round_c,
            itm_celestial_sallet_with_plume_c,
        ],
        lord_attrib,
        wp(220),
        knight_skills_5,
        0x000000067F08234606DB6DB6CF4DBEFF00000000001DB6F80000000000000000,
        khergit_face_middle_2,
    ],
    # of the family
    [
        "kingdom_4_pretender",
        "Bartolomew Tallhart",
        "Bartolomew",
        tf_hero | tf_unmoveable_in_party_window,
        0,
        reserved,
        fac_kingdom_4,
        [
            itm_hunter,
            itm_tabard,
            itm_poulaines_d,
            itm_m_brigandine_navy_c,
            itm_mail_boots_a,
            itm_sword_medieval_c,
            itm_tab_shield_heater_cav_a,
            itm_kettle_hat,
        ],
        lord_attrib,
        wp(220),
        knight_skills_5,
        0x000000040000014936DB6FF6DBBE4EFF00000000001DB6EA0000000000000000,
        nord_face_young_2,
    ],
    # dispossessed and wronged
    [
        "kingdom_5_pretender",
        "Lord Alistaar",
        "Alistaar",
        tf_hero | tf_unmoveable_in_party_window,
        0,
        reserved,
        fac_kingdom_5,
        [
            itm_warhorse,
            itm_nobleman_outfit,
            itm_poulaines_d,
            itm_mail_hauberk,
            itm_mail_boots_b,
            itm_sword_medieval_c,
            itm_tab_shield_heater_d,
            itm_alpine_chapel_mail_d,
        ],
        lord_attrib,
        wp(220),
        knight_skills_5,
        0x0000000BED1062861B239246DECCEE7F00000000001E38790000000000000000,
        rhodok_face_old_2,
    ],
    # republican
    [
        "kingdom_6_pretender",
        "Red Maiden Johanna",
        "Johanna",
        tf_hero | tf_female | tf_unmoveable_in_party_window,
        0,
        reserved,
        fac_kingdom_6,
        [
            itm_arabian_horse_b,
            itm_solarian_armor_scale_a,
            itm_desert_leather_boots_b,
            itm_sarranid_cavalry_sword,
            itm_tab_shield_small_round_c,
        ],
        lord_attrib,
        wp(220),
        knight_skills_5,
        0x00000002D3100001371B65B6DB69BADC00000000001DB7030000000000000000,
    ],
]
