from module_troops_utils import *

troops_town = [
    # Seneschals
    [
        "town_1_seneschal",
        "{!}Town 1 Seneschal",
        "{!}Town 1 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_coarse_tunic],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x00000000000C218501EF4F5D2CCB0026,
    ],
    [
        "town_2_seneschal",
        "{!}Town 2 Seneschal",
        "{!}Town 2 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [
            itm_poulaines_d,
            itm_padded_leather,
        ],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x00000000000C03CC01CC34A9A467FDFD,
    ],
    [
        "town_3_seneschal",
        "{!}Town 3 Seneschal",
        "{!}Town 3 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_coarse_tunic],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x00000000000C500E01DBB2115A55F3CD,
    ],
    [
        "town_4_seneschal",
        "{!}Town 4 Seneschal",
        "{!}Town 4 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_blue_gambeson],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x000000000008035201E6EEBAF3F3EB2B,
    ],
    [
        "town_5_seneschal",
        "{!}Town 5 Seneschal",
        "{!}Town 5 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [
            itm_poulaines_d,
            itm_leather_jerkin,
        ],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x000000000000249101E7898999AC54C6,
    ],
    [
        "town_6_seneschal",
        "{!}Town 6 Seneschal",
        "{!}Town 6 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_red_gambeson],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x000000000010360B01CEF8B57553D34E,
    ],
    [
        "town_7_seneschal",
        "{!}Town 7 Seneschal",
        "{!}Town7 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [
            itm_poulaines_d,
            itm_leather_jerkin,
        ],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x000000000000018101F9487AA831DCE4,
    ],
    [
        "town_8_seneschal",
        "{!}Town 8 Seneschal",
        "{!}Town 8 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_red_gambeson],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x000000000004715201EA236C60A2BCAE,
    ],
    [
        "town_9_seneschal",
        "{!}Town 9 Seneschal",
        "{!}Town 9 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_coarse_tunic],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x00000000000440C601E1CD45CFB38550,
    ],
    [
        "town_10_seneschal",
        "{!}Town 10 Seneschal",
        "{!}Town 10 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [
            itm_poulaines_d,
            itm_leather_jerkin,
        ],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x000000000010230C01EF41BADB50465E,
    ],
    [
        "town_11_seneschal",
        "{!}Town 11 Seneschal",
        "{!}Town 11 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_leather_jacket],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x000000000008061301FB89ACFB95332F,
    ],
    [
        "town_12_seneschal",
        "{!}Town 12 Seneschal",
        "{!}Town 12 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_coarse_tunic],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x00000000000C13CE01DC4723AB936C82,
    ],
    [
        "town_13_seneschal",
        "{!}Town 13 Seneschal",
        "{!}Town 13 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [
            itm_poulaines_d,
            itm_leather_jerkin,
        ],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x000000000008548E01D952A9B25D6D5A,
    ],
    [
        "town_14_seneschal",
        "{!}Town 14 Seneschal",
        "{!}Town 14 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_blue_gambeson],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x000000000004728B01C293C694944B05,
    ],
    [
        "town_15_seneschal",
        "{!}Town 15 Seneschal",
        "{!}Town 14 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_blue_gambeson],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x000000000004728B01C293C694944B05,
    ],
    [
        "town_16_seneschal",
        "{!}Town 16 Seneschal",
        "{!}Town 14 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_blue_gambeson],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x000000000004728B01C293C694944B05,
    ],
    [
        "town_17_seneschal",
        "{!}Town17 Seneschal",
        "{!}Town 14 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_blue_gambeson],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x000000000004728B01C293C694944B05,
    ],
    [
        "town_18_seneschal",
        "{!}Town 18 Seneschal",
        "{!}Town 14 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_blue_gambeson],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x000000000004728B01C293C694944B05,
    ],
    [
        "town_19_seneschal",
        "{!}Town 19 Seneschal",
        "{!}Town 14 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_blue_gambeson],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x000000000004728B01C293C694944B05,
    ],
    [
        "town_20_seneschal",
        "{!}Town 20 Seneschal",
        "{!}Town 14 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_blue_gambeson],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x000000000004728B01C293C694944B05,
    ],
    [
        "town_21_seneschal",
        "{!}Town 21 Seneschal",
        "{!}Town 14 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_blue_gambeson],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x000000000004728B01C293C694944B05,
    ],
    [
        "town_22_seneschal",
        "{!}Town 22 Seneschal",
        "{!}Town 14 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_blue_gambeson],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x000000000004728B01C293C694944B05,
    ],
    [
        "castle_1_seneschal",
        "{!}Castle 1 Seneschal",
        "{!}Castle 1 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_coarse_tunic],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x000000000010360B01CEF8B57553D34E,
    ],
    [
        "castle_2_seneschal",
        "{!}Castle 2 Seneschal",
        "{!}Castle 2 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_nomad_armor],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x000000000008061301FB89ACFB95332F,
    ],
    [
        "castle_3_seneschal",
        "{!}Castle 3 Seneschal",
        "{!}Castle 3 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_padded_leather],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x000000000008548E01D952A9B25D6D5A,
    ],
    [
        "castle_4_seneschal",
        "{!}Castle 4 Seneschal",
        "{!}Castle 4 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_linen_tunic],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x000000000004715201EA236C60A2BCAE,
    ],
    [
        "castle_5_seneschal",
        "{!}Castle 5 Seneschal",
        "{!}Castle 5 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_leather_jerkin],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x00000000000C500E01DBB2115A55F3CD,
    ],
    [
        "castle_6_seneschal",
        "{!}Castle 6 Seneschal",
        "{!}Castle 6 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_coarse_tunic],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x00000000000C03CC01CC34A9A467FDFD,
    ],
    [
        "castle_7_seneschal",
        "{!}Castle 7 Seneschal",
        "{!}Castle 7 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_blue_gambeson],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x00000000000C13CE01DC4723AB936C82,
    ],
    [
        "castle_8_seneschal",
        "{!}Castle 8 Seneschal",
        "{!}Castle 8 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_padded_leather],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x00000000000C218501EF4F5D2CCB0026,
    ],
    [
        "castle_9_seneschal",
        "{!}Castle 9 Seneschal",
        "{!}Castle 9 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_leather_jacket],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x000000000008035201E6EEBAF3F3EB2B,
    ],
    [
        "castle_10_seneschal",
        "{!}Castle 10 Seneschal",
        "{!}Castle 10 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_padded_leather],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x00000000000440C601E1CD45CFB38550,
    ],
    [
        "castle_11_seneschal",
        "{!}Castle 11 Seneschal",
        "{!}Castle 11 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_padded_leather],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x00000000000440C601E1CD45CFB38550,
    ],
    [
        "castle_12_seneschal",
        "{!}Castle 2 Seneschal",
        "{!}Castle 2 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_nomad_armor],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x000000000008061301FB89ACFB95332F,
    ],
    [
        "castle_13_seneschal",
        "{!}Castle 3 Seneschal",
        "{!}Castle 3 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_padded_leather],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x000000000008548E01D952A9B25D6D5A,
    ],
    [
        "castle_14_seneschal",
        "{!}Castle 4 Seneschal",
        "{!}Castle 4 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_linen_tunic],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x000000000004715201EA236C60A2BCAE,
    ],
    [
        "castle_15_seneschal",
        "{!}Castle 5 Seneschal",
        "{!}Castle 5 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_leather_jerkin],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x00000000000C500E01DBB2115A55F3CD,
    ],
    [
        "castle_16_seneschal",
        "{!}Castle 6 Seneschal",
        "{!}Castle 6 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_coarse_tunic],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x00000000000C03CC01CC34A9A467FDFD,
    ],
    [
        "castle_17_seneschal",
        "{!}Castle 7 Seneschal",
        "{!}Castle 7 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_blue_gambeson],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x00000000000C13CE01DC4723AB936C82,
    ],
    [
        "castle_18_seneschal",
        "{!}Castle 8 Seneschal",
        "{!}Castle 8 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_padded_leather],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x00000000000C218501EF4F5D2CCB0026,
    ],
    [
        "castle_19_seneschal",
        "{!}Castle 9 Seneschal",
        "{!}Castle 9 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_leather_jacket],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x000000000008035201E6EEBAF3F3EB2B,
    ],
    [
        "castle_20_seneschal",
        "{!}Castle 20 Seneschal",
        "{!}Castle 20 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_padded_leather],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x00000000000440C601E1CD45CFB38550,
    ],
    [
        "castle_21_seneschal",
        "{!}Castle 11 Seneschal",
        "{!}Castle 11 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_padded_leather],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x00000000000440C601E1CD45CFB38550,
    ],
    [
        "castle_22_seneschal",
        "{!}Castle 2 Seneschal",
        "{!}Castle 2 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_nomad_armor],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x000000000008061301FB89ACFB95332F,
    ],
    [
        "castle_23_seneschal",
        "{!}Castle 3 Seneschal",
        "{!}Castle 3 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_padded_leather],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x000000000008548E01D952A9B25D6D5A,
    ],
    [
        "castle_24_seneschal",
        "{!}Castle 4 Seneschal",
        "{!}Castle 4 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_linen_tunic],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x000000000004715201EA236C60A2BCAE,
    ],
    [
        "castle_25_seneschal",
        "{!}Castle 5 Seneschal",
        "{!}Castle 5 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_leather_jerkin],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x00000000000C500E01DBB2115A55F3CD,
    ],
    [
        "castle_26_seneschal",
        "{!}Castle 6 Seneschal",
        "{!}Castle 6 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_coarse_tunic],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x00000000000C03CC01CC34A9A467FDFD,
    ],
    [
        "castle_27_seneschal",
        "{!}Castle 7 Seneschal",
        "{!}Castle 7 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_blue_gambeson],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x00000000000C13CE01DC4723AB936C82,
    ],
    [
        "castle_28_seneschal",
        "{!}Castle 8 Seneschal",
        "{!}Castle 8 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_padded_leather],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x00000000000C218501EF4F5D2CCB0026,
    ],
    [
        "castle_29_seneschal",
        "{!}Castle 9 Seneschal",
        "{!}Castle 9 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_leather_jacket],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x000000000008035201E6EEBAF3F3EB2B,
    ],
    [
        "castle_30_seneschal",
        "{!}Castle 20 Seneschal",
        "{!}Castle 20 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_padded_leather],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x00000000000440C601E1CD45CFB38550,
    ],
    [
        "castle_31_seneschal",
        "{!}Castle 11 Seneschal",
        "{!}Castle 11 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_padded_leather],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x00000000000440C601E1CD45CFB38550,
    ],
    [
        "castle_32_seneschal",
        "{!}Castle 2 Seneschal",
        "{!}Castle 2 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_nomad_armor],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x000000000008061301FB89ACFB95332F,
    ],
    [
        "castle_33_seneschal",
        "{!}Castle 3 Seneschal",
        "{!}Castle 3 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_padded_leather],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x000000000008548E01D952A9B25D6D5A,
    ],
    [
        "castle_34_seneschal",
        "{!}Castle 4 Seneschal",
        "{!}Castle 4 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_linen_tunic],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x000000000004715201EA236C60A2BCAE,
    ],
    [
        "castle_35_seneschal",
        "{!}Castle 5 Seneschal",
        "{!}Castle 5 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_leather_jerkin],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x00000000000C500E01DBB2115A55F3CD,
    ],
    [
        "castle_36_seneschal",
        "{!}Castle 6 Seneschal",
        "{!}Castle 6 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_coarse_tunic],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x00000000000C03CC01CC34A9A467FDFD,
    ],
    [
        "castle_37_seneschal",
        "{!}Castle 7 Seneschal",
        "{!}Castle 7 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_blue_gambeson],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x00000000000C13CE01DC4723AB936C82,
    ],
    [
        "castle_38_seneschal",
        "{!}Castle 8 Seneschal",
        "{!}Castle 8 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_padded_leather],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x00000000000C218501EF4F5D2CCB0026,
    ],
    [
        "castle_39_seneschal",
        "{!}Castle 9 Seneschal",
        "{!}Castle 9 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_leather_jacket],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x000000000008035201E6EEBAF3F3EB2B,
    ],
    [
        "castle_40_seneschal",
        "{!}Castle 20 Seneschal",
        "{!}Castle 20 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_padded_leather],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x00000000000440C601E1CD45CFB38550,
    ],
    [
        "castle_41_seneschal",
        "{!}Castle 20 Seneschal",
        "{!}Castle 20 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_padded_leather],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x00000000000440C601E1CD45CFB38550,
    ],
    [
        "castle_42_seneschal",
        "{!}Castle 20 Seneschal",
        "{!}Castle 20 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_padded_leather],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x00000000000440C601E1CD45CFB38550,
    ],
    [
        "castle_43_seneschal",
        "{!}Castle 20 Seneschal",
        "{!}Castle 20 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_padded_leather],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x00000000000440C601E1CD45CFB38550,
    ],
    [
        "castle_44_seneschal",
        "{!}Castle 20 Seneschal",
        "{!}Castle 20 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_padded_leather],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x00000000000440C601E1CD45CFB38550,
    ],
    [
        "castle_45_seneschal",
        "{!}Castle 20 Seneschal",
        "{!}Castle 20 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_padded_leather],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x00000000000440C601E1CD45CFB38550,
    ],
    [
        "castle_46_seneschal",
        "{!}Castle 20 Seneschal",
        "{!}Castle 20 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_padded_leather],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x00000000000440C601E1CD45CFB38550,
    ],
    [
        "castle_47_seneschal",
        "{!}Castle 20 Seneschal",
        "{!}Castle 20 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_padded_leather],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x00000000000440C601E1CD45CFB38550,
    ],
    [
        "castle_48_seneschal",
        "{!}Castle 20 Seneschal",
        "{!}Castle 20 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_padded_leather],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x00000000000440C601E1CD45CFB38550,
    ],
    [
        "castle_49_seneschal",
        "{!}Castle 20 Seneschal",
        "{!}Castle 20 Seneschal",
        tf_hero | tf_is_merchant,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_padded_leather],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x00000000000440C601E1CD45CFB38550,
    ],
    # Arena Masters
    [
        "town_1_arena_master",
        "Tournament Master",
        "{!}Tournament Master",
        tf_hero | tf_randomize_face,
        scn_town_1_arena | entry(52),
        reserved,
        fac_commoners,
        [itm_hose_d, itm_coarse_tunic],
        def_attrib | level(2),
        wp(20),
        knows_common,
        man_face_middle_1,
        man_face_older_2,
    ],
    [
        "town_2_arena_master",
        "Tournament Master",
        "{!}Tournament Master",
        tf_hero | tf_randomize_face,
        scn_town_2_arena | entry(52),
        reserved,
        fac_commoners,
        [itm_hose_d, itm_linen_tunic],
        def_attrib | level(2),
        wp(20),
        knows_common,
        man_face_middle_1,
        man_face_older_2,
    ],
    [
        "town_3_arena_master",
        "Tournament Master",
        "{!}Tournament Master",
        tf_hero | tf_randomize_face,
        scn_town_3_arena | entry(52),
        reserved,
        fac_commoners,
        [itm_hose_d, itm_nomad_armor],
        def_attrib | level(2),
        wp(20),
        knows_common,
        man_face_middle_1,
        man_face_older_2,
    ],
    [
        "town_4_arena_master",
        "Tournament Master",
        "{!}Tournament Master",
        tf_hero | tf_randomize_face,
        scn_town_4_arena | entry(52),
        reserved,
        fac_commoners,
        [itm_hose_d, itm_coarse_tunic],
        def_attrib | level(2),
        wp(20),
        knows_common,
        man_face_middle_1,
        man_face_older_2,
    ],
    [
        "town_5_arena_master",
        "Tournament Master",
        "{!}Tournament Master",
        tf_hero | tf_randomize_face,
        scn_town_5_arena | entry(52),
        reserved,
        fac_commoners,
        [itm_hose_d, itm_linen_tunic],
        def_attrib | level(2),
        wp(20),
        knows_common,
        man_face_middle_1,
        man_face_older_2,
    ],
    [
        "town_6_arena_master",
        "Tournament Master",
        "{!}Tournament Master",
        tf_hero | tf_randomize_face,
        scn_town_6_arena | entry(52),
        reserved,
        fac_commoners,
        [itm_hose_d, itm_leather_jerkin],
        def_attrib | level(2),
        wp(20),
        knows_common,
        man_face_middle_1,
        man_face_older_2,
    ],
    [
        "town_7_arena_master",
        "Tournament Master",
        "{!}Tournament Master",
        tf_hero | tf_randomize_face,
        scn_town_7_arena | entry(52),
        reserved,
        fac_commoners,
        [itm_hose_d, itm_padded_leather],
        def_attrib | level(2),
        wp(20),
        knows_common,
        man_face_middle_1,
        man_face_older_2,
    ],
    [
        "town_8_arena_master",
        "Tournament Master",
        "{!}Tournament Master",
        tf_hero | tf_randomize_face,
        scn_town_8_arena | entry(52),
        reserved,
        fac_commoners,
        [itm_hose_d, itm_linen_tunic],
        def_attrib | level(2),
        wp(20),
        knows_common,
        man_face_middle_1,
        man_face_older_2,
    ],
    [
        "town_9_arena_master",
        "Tournament Master",
        "{!}Tournament Master",
        tf_hero | tf_randomize_face,
        scn_town_9_arena | entry(52),
        reserved,
        fac_commoners,
        [itm_hose_d, itm_padded_leather],
        def_attrib | level(2),
        wp(20),
        knows_common,
        man_face_middle_1,
        man_face_older_2,
    ],
    [
        "town_10_arena_master",
        "Tournament Master",
        "{!}Tournament Master",
        tf_hero | tf_randomize_face,
        scn_town_10_arena | entry(52),
        reserved,
        fac_commoners,
        [itm_hose_d, itm_nomad_armor],
        def_attrib | level(2),
        wp(20),
        knows_common,
        man_face_middle_1,
        man_face_older_2,
    ],
    [
        "town_11_arena_master",
        "Tournament Master",
        "{!}Tournament Master",
        tf_hero | tf_randomize_face,
        scn_town_11_arena | entry(52),
        reserved,
        fac_commoners,
        [itm_hose_d, itm_coarse_tunic],
        def_attrib | level(2),
        wp(20),
        knows_common,
        man_face_middle_1,
        man_face_older_2,
    ],
    [
        "town_12_arena_master",
        "Tournament Master",
        "{!}Tournament Master",
        tf_hero | tf_randomize_face,
        scn_town_12_arena | entry(52),
        reserved,
        fac_commoners,
        [itm_hose_d, itm_leather_jerkin],
        def_attrib | level(2),
        wp(20),
        knows_common,
        man_face_middle_1,
        man_face_older_2,
    ],
    [
        "town_13_arena_master",
        "Tournament Master",
        "{!}Tournament Master",
        tf_hero | tf_randomize_face,
        scn_town_13_arena | entry(52),
        reserved,
        fac_commoners,
        [itm_hose_d, itm_coarse_tunic],
        def_attrib | level(2),
        wp(20),
        knows_common,
        man_face_middle_1,
        man_face_older_2,
    ],
    [
        "town_14_arena_master",
        "Tournament Master",
        "{!}Tournament Master",
        tf_hero | tf_randomize_face,
        scn_town_14_arena | entry(52),
        reserved,
        fac_commoners,
        [itm_hose_d, itm_padded_leather],
        def_attrib | level(2),
        wp(20),
        knows_common,
        man_face_middle_1,
        man_face_older_2,
    ],
    [
        "town_15_arena_master",
        "Tournament Master",
        "{!}Tournament Master",
        tf_hero | tf_randomize_face,
        scn_town_15_arena | entry(52),
        reserved,
        fac_commoners,
        [itm_hose_d, itm_padded_leather],
        def_attrib | level(2),
        wp(20),
        knows_common,
        man_face_middle_1,
        man_face_older_2,
    ],
    [
        "town_16_arena_master",
        "Tournament Master",
        "{!}Tournament Master",
        tf_hero | tf_randomize_face,
        scn_town_16_arena | entry(52),
        reserved,
        fac_commoners,
        [itm_hose_d, itm_fur_coat],
        def_attrib | level(2),
        wp(20),
        knows_common,
        man_face_middle_1,
        man_face_older_2,
    ],
    [
        "town_17_arena_master",
        "Tournament Master",
        "{!}Tournament Master",
        tf_hero | tf_randomize_face,
        scn_town_17_arena | entry(52),
        reserved,
        fac_commoners,
        [itm_hose_d, itm_padded_leather],
        def_attrib | level(2),
        wp(20),
        knows_common,
        man_face_middle_1,
        man_face_older_2,
    ],
    [
        "town_18_arena_master",
        "Tournament Master",
        "{!}Tournament Master",
        tf_hero | tf_randomize_face,
        scn_town_18_arena | entry(52),
        reserved,
        fac_commoners,
        [itm_hose_d, itm_padded_leather],
        def_attrib | level(2),
        wp(20),
        knows_common,
        man_face_middle_1,
        man_face_older_2,
    ],
    [
        "town_19_arena_master",
        "Tournament Master",
        "{!}Tournament Master",
        tf_hero | tf_randomize_face,
        scn_town_19_arena | entry(52),
        reserved,
        fac_commoners,
        [itm_hose_d, itm_padded_leather],
        def_attrib | level(2),
        wp(20),
        knows_common,
        man_face_middle_1,
        man_face_older_2,
    ],
    [
        "town_20_arena_master",
        "Tournament Master",
        "{!}Tournament Master",
        tf_hero | tf_randomize_face,
        scn_town_20_arena | entry(52),
        reserved,
        fac_commoners,
        [itm_hose_d, itm_fur_coat],
        def_attrib | level(2),
        wp(20),
        knows_common,
        man_face_middle_1,
        man_face_older_2,
    ],
    [
        "town_21_arena_master",
        "Tournament Master",
        "{!}Tournament Master",
        tf_hero | tf_randomize_face,
        scn_town_21_arena | entry(52),
        reserved,
        fac_commoners,
        [itm_hose_d, itm_padded_leather],
        def_attrib | level(2),
        wp(20),
        knows_common,
        man_face_middle_1,
        man_face_older_2,
    ],
    [
        "town_22_arena_master",
        "Tournament Master",
        "{!}Tournament Master",
        tf_hero | tf_randomize_face,
        scn_town_22_arena | entry(52),
        reserved,
        fac_commoners,
        [itm_hose_d, itm_padded_leather],
        def_attrib | level(2),
        wp(20),
        knows_common,
        man_face_middle_1,
        man_face_older_2,
    ],
    # Armor Merchants
    # arena_masters_end = zendar_armorer
    [
        "town_1_armorer",
        "Armorer",
        "{!}Armorer",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_linen_tunic],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "town_2_armorer",
        "Armorer",
        "{!}Armorer",
        tf_hero | tf_randomize_face | tf_female | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_woolen_dress, itm_straw_hat],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        woman_face_1,
        woman_face_2,
    ],
    [
        "town_3_armorer",
        "Armorer",
        "{!}Armorer",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_arena_tunic_red],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "town_4_armorer",
        "Armorer",
        "{!}Armorer",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_red_gambeson],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "town_5_armorer",
        "Armorer",
        "{!}Armorer",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_linen_tunic],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "town_6_armorer",
        "Armorer",
        "{!}Armorer",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_fur_coat],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "town_7_armorer",
        "Armorer",
        "{!}Armorer",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_leather_jerkin],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "town_8_armorer",
        "Armorer",
        "{!}Armorer",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_padded_leather],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "town_9_armorer",
        "Armorer",
        "{!}Armorer",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_blue_gambeson],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "town_10_armorer",
        "Armorer",
        "{!}Armorer",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_leather_jerkin],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "town_11_armorer",
        "Armorer",
        "{!}Armorer",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_fur_coat],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "town_12_armorer",
        "Armorer",
        "{!}Armorer",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_red_gambeson],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "town_13_armorer",
        "Armorer",
        "{!}Armorer",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_leather_jacket],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "town_14_armorer",
        "Armorer",
        "{!}Armorer",
        tf_hero | tf_randomize_face | tf_female | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_woolen_dress, itm_headcloth],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        woman_face_1,
        woman_face_2,
    ],
    [
        "town_15_armorer",
        "Armorer",
        "{!}Armorer",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_blue_gambeson],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "town_16_armorer",
        "Armorer",
        "{!}Armorer",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_fur_coat],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "town_17_armorer",
        "Armorer",
        "{!}Armorer",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_fur_coat],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "town_18_armorer",
        "Armorer",
        "{!}Armorer",
        tf_hero | tf_randomize_face | tf_female | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_woolen_dress, itm_headcloth],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        woman_face_1,
        woman_face_2,
    ],
    [
        "town_19_armorer",
        "Armorer",
        "{!}Armorer",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_blue_gambeson],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "town_20_armorer",
        "Armorer",
        "{!}Armorer",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_fur_coat],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "town_21_armorer",
        "Armorer",
        "{!}Armorer",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_fur_coat],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "town_22_armorer",
        "Armorer",
        "{!}Armorer",
        tf_hero | tf_randomize_face | tf_female | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_sarranid_common_dress, itm_sarranid_head_cloth],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        woman_face_1,
        woman_face_2,
    ],
    # Weapon merchants
    [
        "town_1_weaponsmith",
        "Weaponsmith",
        "{!}Weaponsmith",
        tf_hero | tf_randomize_face | tf_female | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_linen_tunic, itm_straw_hat],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        woman_face_1,
        woman_face_2,
    ],
    [
        "town_2_weaponsmith",
        "Weaponsmith",
        "{!}Weaponsmith",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_shirt],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "town_3_weaponsmith",
        "Weaponsmith",
        "{!}Weaponsmith",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_fur_coat],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "town_4_weaponsmith",
        "Weaponsmith",
        "{!}Weaponsmith",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_shirt],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "town_5_weaponsmith",
        "Weaponsmith",
        "{!}Weaponsmith",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_leather_jerkin],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "town_6_weaponsmith",
        "Weaponsmith",
        "{!}Weaponsmith",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_linen_tunic],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "town_7_weaponsmith",
        "Weaponsmith",
        "{!}Weaponsmith",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_shirt],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "town_8_weaponsmith",
        "Weaponsmith",
        "{!}Weaponsmith",
        tf_hero | tf_randomize_face | tf_female | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_woolen_dress, itm_straw_hat],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        woman_face_1,
        woman_face_2,
    ],
    [
        "town_9_weaponsmith",
        "Weaponsmith",
        "{!}Weaponsmith",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_leather_jerkin],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "town_10_weaponsmith",
        "Weaponsmith",
        "{!}Weaponsmith",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_linen_tunic],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "town_11_weaponsmith",
        "Weaponsmith",
        "{!}Weaponsmith",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_leather_jacket],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "town_12_weaponsmith",
        "Weaponsmith",
        "{!}Weaponsmith",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_shirt],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "town_13_weaponsmith",
        "Weaponsmith",
        "{!}Weaponsmith",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_arena_tunic_red],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "town_14_weaponsmith",
        "Weaponsmith",
        "{!}Weaponsmith",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_arena_tunic_blue],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "town_15_weaponsmith",
        "Weaponsmith",
        "{!}Weaponsmith",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_leather_jacket],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "town_16_weaponsmith",
        "Weaponsmith",
        "{!}Weaponsmith",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_shirt],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "town_17_weaponsmith",
        "Weaponsmith",
        "{!}Weaponsmith",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_arena_tunic_green],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "town_18_weaponsmith",
        "Weaponsmith",
        "{!}Weaponsmith",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_linen_tunic],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "town_19_weaponsmith",
        "Weaponsmith",
        "{!}Weaponsmith",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_leather_jacket],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "town_20_weaponsmith",
        "Weaponsmith",
        "{!}Weaponsmith",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_shirt],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "town_21_weaponsmith",
        "Weaponsmith",
        "{!}Weaponsmith",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_arena_tunic_green],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "town_22_weaponsmith",
        "Weaponsmith",
        "{!}Weaponsmith",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_linen_tunic],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        mercenary_face_1,
        mercenary_face_2,
    ],
    # Tavern keepers
    [
        "town_1_tavernkeeper",
        "Tavern_Keeper",
        "{!}Tavern_Keeper",
        tf_hero | tf_randomize_face,
        scn_town_1_tavern | entry(9),
        0,
        fac_commoners,
        [itm_hose_d, itm_leather_apron],
        def_attrib | level(2),
        wp(20),
        knows_common,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "town_2_tavernkeeper",
        "Tavern_Keeper",
        "{!}Tavern_Keeper",
        tf_hero | tf_randomize_face,
        scn_town_2_tavern | entry(9),
        0,
        fac_commoners,
        [itm_hose_d, itm_leather_apron],
        def_attrib | level(2),
        wp(20),
        knows_common,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "town_3_tavernkeeper",
        "Tavern_Keeper",
        "{!}Tavern_Keeper",
        tf_hero | tf_randomize_face | tf_female,
        scn_town_3_tavern | entry(9),
        0,
        fac_commoners,
        [itm_hose_d, itm_woolen_dress],
        def_attrib | level(2),
        wp(20),
        knows_common,
        woman_face_1,
        woman_face_2,
    ],
    [
        "town_4_tavernkeeper",
        "Tavern_Keeper",
        "{!}Tavern_Keeper",
        tf_hero | tf_randomize_face,
        scn_town_4_tavern | entry(9),
        0,
        fac_commoners,
        [itm_hose_d, itm_leather_apron],
        def_attrib | level(2),
        wp(20),
        knows_common,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "town_5_tavernkeeper",
        "Tavern_Keeper",
        "{!}Tavern_Keeper",
        tf_hero | tf_randomize_face,
        scn_town_5_tavern | entry(9),
        0,
        fac_commoners,
        [itm_hose_d, itm_leather_apron],
        def_attrib | level(2),
        wp(20),
        knows_common,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "town_6_tavernkeeper",
        "Tavern_Keeper",
        "{!}Tavern_Keeper",
        tf_hero | tf_randomize_face | tf_female,
        scn_town_6_tavern | entry(9),
        0,
        fac_commoners,
        [itm_hose_d, itm_woolen_dress],
        def_attrib | level(2),
        wp(20),
        knows_common,
        woman_face_1,
        woman_face_2,
    ],
    [
        "town_7_tavernkeeper",
        "Tavern_Keeper",
        "{!}Tavern_Keeper",
        tf_hero | tf_randomize_face | tf_female,
        scn_town_7_tavern | entry(9),
        0,
        fac_commoners,
        [itm_hose_d, itm_woolen_dress, itm_headcloth],
        def_attrib | level(2),
        wp(20),
        knows_common,
        woman_face_1,
        woman_face_2,
    ],
    [
        "town_8_tavernkeeper",
        "Tavern_Keeper",
        "{!}Tavern_Keeper",
        tf_hero | tf_randomize_face,
        scn_town_8_tavern | entry(9),
        0,
        fac_commoners,
        [itm_hose_d, itm_leather_apron],
        def_attrib | level(2),
        wp(20),
        knows_common,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "town_9_tavernkeeper",
        "Tavern_Keeper",
        "{!}Tavern_Keeper",
        tf_hero | tf_randomize_face | tf_female,
        scn_town_9_tavern | entry(9),
        0,
        fac_commoners,
        [itm_hose_d, itm_woolen_dress],
        def_attrib | level(2),
        wp(20),
        knows_common,
        woman_face_1,
        woman_face_2,
    ],
    [
        "town_10_tavernkeeper",
        "Tavern_Keeper",
        "{!}Tavern_Keeper",
        tf_hero | tf_randomize_face | tf_female,
        scn_town_10_tavern | entry(9),
        0,
        fac_commoners,
        [itm_hose_d, itm_woolen_dress],
        def_attrib | level(2),
        wp(20),
        knows_common,
        woman_face_1,
        woman_face_2,
    ],
    [
        "town_11_tavernkeeper",
        "Tavern_Keeper",
        "{!}Tavern_Keeper",
        tf_hero | tf_randomize_face | tf_female,
        scn_town_11_tavern | entry(9),
        0,
        fac_commoners,
        [itm_hose_d, itm_woolen_dress],
        def_attrib | level(2),
        wp(20),
        knows_common,
        woman_face_1,
        woman_face_2,
    ],
    [
        "town_12_tavernkeeper",
        "Tavern_Keeper",
        "{!}Tavern_Keeper",
        tf_hero | tf_randomize_face,
        scn_town_12_tavern | entry(9),
        0,
        fac_commoners,
        [itm_hose_d, itm_leather_apron],
        def_attrib | level(2),
        wp(20),
        knows_common,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "town_13_tavernkeeper",
        "Tavern_Keeper",
        "{!}Tavern_Keeper",
        tf_hero | tf_randomize_face | tf_female,
        scn_town_13_tavern | entry(9),
        0,
        fac_commoners,
        [itm_hose_d, itm_woolen_dress, itm_headcloth],
        def_attrib | level(2),
        wp(20),
        knows_common,
        woman_face_1,
        woman_face_2,
    ],
    [
        "town_14_tavernkeeper",
        "Tavern_Keeper",
        "{!}Tavern_Keeper",
        tf_hero | tf_randomize_face,
        scn_town_14_tavern | entry(9),
        0,
        fac_commoners,
        [itm_hose_d, itm_shirt],
        def_attrib | level(2),
        wp(20),
        knows_common,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "town_15_tavernkeeper",
        "Tavern_Keeper",
        "{!}Tavern_Keeper",
        tf_hero | tf_randomize_face | tf_female,
        scn_town_15_tavern | entry(9),
        0,
        fac_commoners,
        [itm_hose_d, itm_woolen_dress],
        def_attrib | level(2),
        wp(20),
        knows_common,
        woman_face_1,
        woman_face_2,
    ],
    [
        "town_16_tavernkeeper",
        "Tavern_Keeper",
        "{!}Tavern_Keeper",
        tf_hero | tf_randomize_face,
        scn_town_16_tavern | entry(9),
        0,
        fac_commoners,
        [itm_hose_d, itm_leather_apron],
        def_attrib | level(2),
        wp(20),
        knows_common,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "town_17_tavernkeeper",
        "Tavern_Keeper",
        "{!}Tavern_Keeper",
        tf_hero | tf_randomize_face | tf_female,
        scn_town_17_tavern | entry(9),
        0,
        fac_commoners,
        [itm_hose_d, itm_woolen_dress, itm_headcloth],
        def_attrib | level(2),
        wp(20),
        knows_common,
        woman_face_1,
        woman_face_2,
    ],
    [
        "town_18_tavernkeeper",
        "Tavern_Keeper",
        "{!}Tavern_Keeper",
        tf_hero | tf_randomize_face,
        scn_town_18_tavern | entry(9),
        0,
        fac_commoners,
        [itm_hose_d, itm_shirt],
        def_attrib | level(2),
        wp(20),
        knows_common,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "town_19_tavernkeeper",
        "Tavern_Keeper",
        "{!}Tavern_Keeper",
        tf_hero | tf_randomize_face | tf_female,
        scn_town_19_tavern | entry(9),
        0,
        fac_commoners,
        [itm_hose_d, itm_sarranid_dress_a],
        def_attrib | level(2),
        wp(20),
        knows_common,
        woman_face_1,
        woman_face_2,
    ],
    [
        "town_20_tavernkeeper",
        "Tavern_Keeper",
        "{!}Tavern_Keeper",
        tf_hero | tf_randomize_face,
        scn_town_20_tavern | entry(9),
        0,
        fac_commoners,
        [itm_hose_d, itm_solarian_robe_a],
        def_attrib | level(2),
        wp(20),
        knows_common,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "town_21_tavernkeeper",
        "Tavern_Keeper",
        "{!}Tavern_Keeper",
        tf_hero | tf_randomize_face | tf_female,
        scn_town_21_tavern | entry(9),
        0,
        fac_commoners,
        [itm_hose_d, itm_sarranid_common_dress, itm_headcloth],
        def_attrib | level(2),
        wp(20),
        knows_common,
        woman_face_1,
        woman_face_2,
    ],
    [
        "town_22_tavernkeeper",
        "Tavern_Keeper",
        "{!}Tavern_Keeper",
        tf_hero | tf_randomize_face,
        scn_town_22_tavern | entry(9),
        0,
        fac_commoners,
        [itm_hose_d, itm_solarian_aketon_a],
        def_attrib | level(2),
        wp(20),
        knows_common,
        mercenary_face_1,
        mercenary_face_2,
    ],
    # Goods Merchants
    [
        "town_1_merchant",
        "Merchant",
        "{!}Merchant",
        tf_hero | tf_randomize_face | tf_is_merchant,
        scn_town_1_store | entry(9),
        0,
        fac_commoners,
        [itm_hose_d, itm_coarse_tunic],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_young_1,
        man_face_older_2,
    ],
    [
        "town_2_merchant",
        "Merchant",
        "{!}Merchant",
        tf_hero | tf_randomize_face | tf_is_merchant,
        scn_town_2_store | entry(9),
        0,
        fac_commoners,
        [itm_hose_d, itm_leather_apron],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_young_1,
        man_face_older_2,
    ],
    [
        "town_3_merchant",
        "Merchant",
        "{!}Merchant",
        tf_female | tf_hero | tf_randomize_face | tf_is_merchant,
        scn_town_3_store | entry(9),
        0,
        fac_commoners,
        [itm_hose_d, itm_dress, itm_straw_hat],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        woman_face_1,
        woman_face_2,
    ],
    [
        "town_4_merchant",
        "Merchant",
        "{!}Merchant",
        tf_hero | tf_randomize_face | tf_is_merchant,
        scn_town_4_store | entry(9),
        0,
        fac_commoners,
        [itm_hose_d, itm_leather_apron],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_young_1,
        man_face_older_2,
    ],
    [
        "town_5_merchant",
        "Merchant",
        "{!}Merchant",
        tf_hero | tf_randomize_face | tf_is_merchant,
        scn_town_5_store | entry(9),
        0,
        fac_commoners,
        [itm_hose_d, itm_nomad_armor],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_young_1,
        man_face_older_2,
    ],
    [
        "town_6_merchant",
        "Merchant",
        "{!}Merchant",
        tf_female | tf_hero | tf_randomize_face | tf_is_merchant,
        scn_town_6_store | entry(9),
        0,
        fac_commoners,
        [itm_hose_d, itm_woolen_dress],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_young_1,
        man_face_older_2,
    ],
    [
        "town_7_merchant",
        "Merchant",
        "{!}Merchant",
        tf_hero | tf_randomize_face | tf_is_merchant,
        scn_town_7_store | entry(9),
        0,
        fac_commoners,
        [itm_hose_d, itm_leather_jerkin],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_young_1,
        man_face_older_2,
    ],
    [
        "town_8_merchant",
        "Merchant",
        "{!}Merchant",
        tf_hero | tf_randomize_face | tf_is_merchant,
        scn_town_8_store | entry(9),
        0,
        fac_commoners,
        [itm_hose_d, itm_leather_apron],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_young_1,
        man_face_older_2,
    ],
    [
        "town_9_merchant",
        "Merchant",
        "{!}Merchant",
        tf_hero | tf_randomize_face | tf_is_merchant,
        scn_town_9_store | entry(9),
        0,
        fac_commoners,
        [itm_hose_d, itm_leather_apron],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_young_1,
        man_face_older_2,
    ],
    [
        "town_10_merchant",
        "Merchant",
        "{!}Merchant",
        tf_hero | tf_randomize_face | tf_is_merchant,
        scn_town_10_store | entry(9),
        0,
        fac_commoners,
        [itm_hose_d, itm_leather_jerkin],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_young_1,
        man_face_older_2,
    ],
    [
        "town_11_merchant",
        "Merchant",
        "{!}Merchant",
        tf_hero | tf_randomize_face | tf_is_merchant,
        scn_town_11_store | entry(9),
        0,
        fac_commoners,
        [itm_hose_d, itm_leather_apron],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_young_1,
        man_face_older_2,
    ],
    [
        "town_12_merchant",
        "Merchant",
        "{!}Merchant",
        tf_female | tf_hero | tf_randomize_face | tf_is_merchant,
        scn_town_12_store | entry(9),
        0,
        fac_commoners,
        [itm_hose_d, itm_woolen_dress, itm_female_hood],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        woman_face_1,
        woman_face_2,
    ],
    [
        "town_13_merchant",
        "Merchant",
        "{!}Merchant",
        tf_female | tf_hero | tf_randomize_face | tf_is_merchant,
        scn_town_13_store | entry(9),
        0,
        fac_commoners,
        [itm_hose_d, itm_dress, itm_straw_hat],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        woman_face_1,
        woman_face_2,
    ],
    [
        "town_14_merchant",
        "Merchant",
        "{!}Merchant",
        tf_hero | tf_randomize_face | tf_is_merchant,
        scn_town_14_store | entry(9),
        0,
        fac_commoners,
        [itm_hose_d, itm_leather_apron],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_young_1,
        man_face_older_2,
    ],
    [
        "town_15_merchant",
        "Merchant",
        "{!}Merchant",
        tf_hero | tf_randomize_face | tf_is_merchant,
        scn_town_15_store | entry(9),
        0,
        fac_commoners,
        [itm_hose_d, itm_leather_apron],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_young_1,
        man_face_older_2,
    ],
    [
        "town_16_merchant",
        "Merchant",
        "{!}Merchant",
        tf_female | tf_hero | tf_randomize_face | tf_is_merchant,
        scn_town_16_store | entry(9),
        0,
        fac_commoners,
        [itm_hose_d, itm_woolen_dress, itm_female_hood],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        woman_face_1,
        woman_face_2,
    ],
    [
        "town_17_merchant",
        "Merchant",
        "{!}Merchant",
        tf_female | tf_hero | tf_randomize_face | tf_is_merchant,
        scn_town_17_store | entry(9),
        0,
        fac_commoners,
        [itm_hose_d, itm_dress, itm_straw_hat],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        woman_face_1,
        woman_face_2,
    ],
    [
        "town_18_merchant",
        "Merchant",
        "{!}Merchant",
        tf_hero | tf_randomize_face | tf_is_merchant,
        scn_town_18_store | entry(9),
        0,
        fac_commoners,
        [itm_hose_d, itm_leather_apron],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_young_1,
        man_face_older_2,
    ],
    [
        "town_19_merchant",
        "Merchant",
        "{!}Merchant",
        tf_hero | tf_randomize_face | tf_is_merchant,
        scn_town_19_store | entry(9),
        0,
        fac_commoners,
        [itm_hose_d, itm_leather_apron],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_young_1,
        man_face_older_2,
    ],
    [
        "town_20_merchant",
        "Merchant",
        "{!}Merchant",
        tf_female | tf_hero | tf_randomize_face | tf_is_merchant,
        scn_town_20_store | entry(9),
        0,
        fac_commoners,
        [itm_hose_d, itm_sarranid_common_dress_b, itm_sarranid_felt_head_cloth_b],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        woman_face_1,
        woman_face_2,
    ],
    [
        "town_21_merchant",
        "Merchant",
        "{!}Merchant",
        tf_female | tf_hero | tf_randomize_face | tf_is_merchant,
        scn_town_21_store | entry(9),
        0,
        fac_commoners,
        [itm_hose_d, itm_sarranid_dress_a, itm_sarranid_felt_head_cloth],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        woman_face_1,
        woman_face_2,
    ],
    [
        "town_22_merchant",
        "Merchant",
        "{!}Merchant",
        tf_hero | tf_randomize_face | tf_is_merchant,
        scn_town_22_store | entry(9),
        0,
        fac_commoners,
        [itm_hose_d, itm_leather_apron],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_young_1,
        man_face_older_2,
    ],
    [
        "salt_mine_merchant",
        "Barezan",
        "Barezan",
        tf_hero | tf_is_merchant,
        scn_salt_mine | entry(1),
        0,
        fac_commoners,
        [itm_hose_d, itm_leather_apron],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        0x00000000000C528601EA69B6E46DBDB6,
    ],
    # Horse Merchants
    [
        "town_1_horse_merchant",
        "Horse Merchant",
        "{!}Town 1 Horse Merchant",
        tf_hero | tf_randomize_face | tf_is_merchant | tf_female,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_blue_dress, itm_female_hood],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        woman_face_1,
        woman_face_2,
    ],
    [
        "town_2_horse_merchant",
        "Horse Merchant",
        "{!}Town 2 Horse Merchant",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_linen_tunic],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        man_face_young_1,
        man_face_older_2,
    ],
    [
        "town_3_horse_merchant",
        "Horse Merchant",
        "{!}Town 3 Horse Merchant",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_nomad_armor],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        man_face_young_1,
        man_face_older_2,
    ],
    [
        "town_4_horse_merchant",
        "Horse Merchant",
        "{!}Town 4 Horse Merchant",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_leather_jerkin],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        man_face_young_1,
        man_face_older_2,
    ],
    [
        "town_5_horse_merchant",
        "Horse Merchant",
        "{!}Town 5 Horse Merchant",
        tf_hero | tf_randomize_face | tf_is_merchant | tf_female,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_dress, itm_woolen_hood],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        woman_face_1,
        woman_face_2,
    ],
    [
        "town_6_horse_merchant",
        "Horse Merchant",
        "{!}Town 6 Horse Merchant",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_coarse_tunic],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        man_face_young_1,
        man_face_older_2,
    ],
    [
        "town_7_horse_merchant",
        "Horse Merchant",
        "{!}Town 7 Horse Merchant",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_coarse_tunic],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        man_face_young_1,
        man_face_older_2,
    ],
    [
        "town_8_horse_merchant",
        "Horse Merchant",
        "{!}Town 8 Horse Merchant",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_coarse_tunic],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        man_face_young_1,
        man_face_older_2,
    ],
    [
        "town_9_horse_merchant",
        "Horse Merchant",
        "{!}Town 9 Horse Merchant",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_leather_jerkin],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        man_face_young_1,
        man_face_older_2,
    ],
    [
        "town_10_horse_merchant",
        "Horse Merchant",
        "{!}Town 10 Horse Merchant",
        tf_hero | tf_randomize_face | tf_is_merchant | tf_female,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_blue_dress, itm_straw_hat],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        woman_face_1,
        woman_face_2,
    ],
    [
        "town_11_horse_merchant",
        "Horse Merchant",
        "{!}Town 11 Horse Merchant",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_nomad_armor],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        man_face_young_1,
        man_face_older_2,
    ],
    [
        "town_12_horse_merchant",
        "Horse Merchant",
        "{!}Town 12 Horse Merchant",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_leather_jacket],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        man_face_young_1,
        man_face_older_2,
    ],
    [
        "town_13_horse_merchant",
        "Horse Merchant",
        "{!}Town 13 Horse Merchant",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_coarse_tunic],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        man_face_young_1,
        man_face_older_2,
    ],
    [
        "town_14_horse_merchant",
        "Horse Merchant",
        "{!}Town 14 Horse Merchant",
        tf_hero | tf_randomize_face | tf_is_merchant | tf_female,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_peasant_dress, itm_headcloth],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        woman_face_1,
        woman_face_2,
    ],
    [
        "town_15_horse_merchant",
        "Horse Merchant",
        "{!}Town 15 Horse Merchant",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_nomad_armor],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        man_face_young_1,
        man_face_older_2,
    ],
    [
        "town_16_horse_merchant",
        "Horse Merchant",
        "{!}Town 16 Horse Merchant",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_leather_jacket],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        man_face_young_1,
        man_face_older_2,
    ],
    [
        "town_17_horse_merchant",
        "Horse Merchant",
        "{!}Town 17 Horse Merchant",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_coarse_tunic],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        man_face_young_1,
        man_face_older_2,
    ],
    [
        "town_18_horse_merchant",
        "Horse Merchant",
        "{!}Town 18 Horse Merchant",
        tf_hero | tf_randomize_face | tf_is_merchant | tf_female,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_peasant_dress, itm_headcloth],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        woman_face_1,
        woman_face_2,
    ],
    [
        "town_19_horse_merchant",
        "Horse Merchant",
        "{!}Town 15 Horse Merchant",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_nomad_armor],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        man_face_young_1,
        man_face_older_2,
    ],
    [
        "town_20_horse_merchant",
        "Horse Merchant",
        "{!}Town 16 Horse Merchant",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_solarian_robe_a],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        man_face_young_1,
        man_face_older_2,
    ],
    [
        "town_21_horse_merchant",
        "Horse Merchant",
        "{!}Town 17 Horse Merchant",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_solarian_aketon_a],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        man_face_young_1,
        man_face_older_2,
    ],
    [
        "town_22_horse_merchant",
        "Horse Merchant",
        "{!}Town 18 Horse Merchant",
        tf_hero | tf_randomize_face | tf_is_merchant | tf_female,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_sarranid_common_dress_b, itm_sarranid_felt_head_cloth_b],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        woman_face_1,
        woman_face_2,
    ],
    # Town Mayors    #itm_tabard_e itm_gambeson itm_blue_gambeson itm_red_gambeson itm_tabard_f itm_tabard_d
    [
        "town_1_mayor",
        "Guild_Master",
        "{!}Guild_Master",
        tf_hero | tf_randomize_face,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_tabard_e],
        def_attrib | level(2),
        wp(20),
        knows_common,
        man_face_middle_1,
        mercenary_face_2,
    ],
    [
        "town_2_mayor",
        "Guild_Master",
        "{!}Guild_Master",
        tf_hero | tf_randomize_face,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_gambeson],
        def_attrib | level(2),
        wp(20),
        knows_common,
        man_face_middle_1,
        mercenary_face_2,
    ],
    [
        "town_3_mayor",
        "Guild_Master",
        "{!}Guild_Master",
        tf_hero | tf_randomize_face,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_blue_gambeson],
        def_attrib | level(2),
        wp(20),
        knows_common,
        man_face_middle_1,
        mercenary_face_2,
    ],
    [
        "town_4_mayor",
        "Guild_Master",
        "{!}Guild_Master",
        tf_hero | tf_randomize_face,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_fur_coat],
        def_attrib | level(2),
        wp(20),
        knows_common,
        man_face_middle_1,
        mercenary_face_2,
    ],
    [
        "town_5_mayor",
        "Guild_Master",
        "{!}Guild_Master",
        tf_hero | tf_randomize_face,
        0,
        reserved,
        fac_neutral,
        [
            itm_poulaines_d,
            itm_tabard_f,
        ],
        def_attrib | level(2),
        wp(20),
        knows_common,
        man_face_middle_1,
        mercenary_face_2,
    ],
    [
        "town_6_mayor",
        "Guild_Master",
        "{!}Guild_Master",
        tf_hero | tf_randomize_face,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_red_gambeson],
        def_attrib | level(2),
        wp(20),
        knows_common,
        man_face_middle_1,
        mercenary_face_2,
    ],
    [
        "town_7_mayor",
        "Guild_Master",
        "{!}Guild_Master",
        tf_hero | tf_randomize_face,
        0,
        reserved,
        fac_neutral,
        [
            itm_poulaines_d,
            itm_tabard_d,
        ],
        def_attrib | level(2),
        wp(20),
        knows_common,
        man_face_middle_1,
        mercenary_face_2,
    ],
    [
        "town_8_mayor",
        "Guild_Master",
        "{!}Guild_Master",
        tf_hero | tf_randomize_face,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_red_gambeson],
        def_attrib | level(2),
        wp(20),
        knows_common,
        man_face_middle_1,
        mercenary_face_2,
    ],
    [
        "town_9_mayor",
        "Guild_Master",
        "{!}Guild_Master",
        tf_hero | tf_randomize_face,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_tabard_e],
        def_attrib | level(2),
        wp(20),
        knows_common,
        man_face_middle_1,
        mercenary_face_2,
    ],
    [
        "town_10_mayor",
        "Guild_Master",
        "{!}Guild_Master",
        tf_hero | tf_randomize_face,
        0,
        reserved,
        fac_neutral,
        [
            itm_poulaines_d,
            itm_leather_jerkin,
        ],
        def_attrib | level(2),
        wp(20),
        knows_common,
        man_face_middle_1,
        mercenary_face_2,
    ],
    [
        "town_11_mayor",
        "Guild_Master",
        "{!}Guild_Master",
        tf_hero | tf_randomize_face,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_leather_jacket],
        def_attrib | level(2),
        wp(20),
        knows_common,
        man_face_middle_1,
        mercenary_face_2,
    ],
    [
        "town_12_mayor",
        "Guild_Master",
        "{!}Guild_Master",
        tf_hero | tf_randomize_face,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_red_gambeson],
        def_attrib | level(2),
        wp(20),
        knows_common,
        man_face_middle_1,
        mercenary_face_2,
    ],
    [
        "town_13_mayor",
        "Guild_Master",
        "{!}Guild_Master",
        tf_hero | tf_randomize_face,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_tabard_f],
        def_attrib | level(2),
        wp(20),
        knows_common,
        man_face_middle_1,
        mercenary_face_2,
    ],
    [
        "town_14_mayor",
        "Guild_Master",
        "{!}Guild_Master",
        tf_hero | tf_randomize_face,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_blue_gambeson],
        def_attrib | level(2),
        wp(20),
        knows_common,
        man_face_middle_1,
        mercenary_face_2,
    ],
    [
        "town_15_mayor",
        "Guild_Master",
        "{!}Guild_Master",
        tf_hero | tf_randomize_face,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_leather_jacket],
        def_attrib | level(2),
        wp(20),
        knows_common,
        man_face_middle_1,
        mercenary_face_2,
    ],
    [
        "town_16_mayor",
        "Guild_Master",
        "{!}Guild_Master",
        tf_hero | tf_randomize_face,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_fur_coat],
        def_attrib | level(2),
        wp(20),
        knows_common,
        man_face_middle_1,
        mercenary_face_2,
    ],
    [
        "town_17_mayor",
        "Guild_Master",
        "{!}Guild_Master",
        tf_hero | tf_randomize_face,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_tabard_f],
        def_attrib | level(2),
        wp(20),
        knows_common,
        man_face_middle_1,
        mercenary_face_2,
    ],
    [
        "town_18_mayor",
        "Guild_Master",
        "{!}Guild_Master",
        tf_hero | tf_randomize_face,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_blue_gambeson],
        def_attrib | level(2),
        wp(20),
        knows_common,
        man_face_middle_1,
        mercenary_face_2,
    ],
    [
        "town_19_mayor",
        "Guild_Master",
        "{!}Guild_Master",
        tf_hero | tf_randomize_face,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_solarian_robe_a],
        def_attrib | level(2),
        wp(20),
        knows_common,
        man_face_middle_1,
        mercenary_face_2,
    ],
    [
        "town_20_mayor",
        "Guild_Master",
        "{!}Guild_Master",
        tf_hero | tf_randomize_face,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_solarian_robe_a],
        def_attrib | level(2),
        wp(20),
        knows_common,
        man_face_middle_1,
        mercenary_face_2,
    ],
    [
        "town_21_mayor",
        "Guild_Master",
        "{!}Guild_Master",
        tf_hero | tf_randomize_face,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_solarian_robe_a],
        def_attrib | level(2),
        wp(20),
        knows_common,
        man_face_middle_1,
        mercenary_face_2,
    ],
    [
        "town_22_mayor",
        "Guild_Master",
        "{!}Guild_Master",
        tf_hero | tf_randomize_face,
        0,
        reserved,
        fac_neutral,
        [itm_poulaines_d, itm_solarian_robe_a],
        def_attrib | level(2),
        wp(20),
        knows_common,
        man_face_middle_1,
        mercenary_face_2,
    ],
]
