from module_troops_utils import *

troops_factions = [
    [
        "nerpa_recruit",
        "Nerpa Recruit",
        "Nerpa Recruits",
        tf_guarantee_armor | tf_guarantee_boots,
        0,
        0,
        fac_kingdom_7,
        [
            itm_mace_a,
            itm_falchion_a,
            itm_spear_b,
            itm_tab_shield_tauria_a,
            itm_arming_cap_a,
            itm_felt_a_v2,
            itm_felt_b_v1,
            (itm_purple_shirt_a, 0),
            (itm_purple_shirt_a_v1, 0),
            (itm_purple_shirt_a_v2, 0),
            itm_leather_gloves_a,
            itm_hose_d,
            itm_poulaines_d,
        ],
        def_attrib | level(5),
        wp(60),
        knows_common,
        swadian_face_younger_1,
        swadian_face_middle_2,
    ],
    [
        "nerpa_footman",
        "Nerpa Footman",
        "Nerpa Footmen",
        tf_guarantee_armor | tf_guarantee_boots | tf_guarantee_helmet,
        0,
        0,
        fac_kingdom_7,
        [
            itm_sword_short_a,
            itm_mace_a,
            itm_mace_b,
            itm_spear_b,
            itm_tab_shield_tauria_a,
            itm_tab_shield_pavise_a,
            itm_arming_cap_a,
            itm_felt_a_v2,
            itm_felt_b_v1,
            itm_chapel_c,
            itm_chapel_c_v1,
            itm_chapel_c_v2,
            (itm_purple_leather_armor_a, 0),
            itm_leather_gloves_a,
            itm_hose_d,
            itm_poulaines_d,
        ],
        def_attrib | level(10),
        wp(90),
        knows_common,
        swadian_face_younger_1,
        swadian_face_middle_2,
    ],
    [
        "nerpa_yeoman",
        "Nerpa Yeoman",
        "Nerpa Yeomen",
        tf_guarantee_all,
        0,
        0,
        fac_kingdom_7,
        [
            itm_sword_short_a,
            itm_mace_a,
            itm_mace_a_v1,
            itm_long_bow,
            itm_hunting_bow,
            itm_arrows,
            itm_arming_cap_a,
            itm_felt_a_v2,
            itm_felt_b_v1,
            (itm_purple_aketon_a, 0),
            (itm_purple_aketon_a, imod_thick),
            itm_hose_d,
            itm_poulaines_d,
        ],
        def_attrib | level(15),
        wp(100) | wp_archery(50),
        knows_common | knows_power_draw_3,
        swadian_face_younger_1,
        swadian_face_middle_2,
    ],
    [
        "nerpa_trickshot",
        "Nerpa Trickshot",
        "Nerpa Trickshots",
        tf_guarantee_all,
        0,
        0,
        fac_kingdom_7,
        [
            itm_sword_short_a,
            itm_sword_short_a_v1,
            itm_mace_b,
            itm_mace_b_v1,
            itm_long_bow,
            itm_hunting_bow,
            itm_arrows,
            itm_felt_b_v1,
            itm_chapel_c_v2,
            (itm_purple_aketon_a, imod_thick),
            (itm_purple_aketon_a, imod_hardened),
            itm_hose_d,
            itm_poulaines_d,
        ],
        def_attrib | level(20),
        wp(130) | wp_archery(50),
        knows_common | knows_power_draw_6,
        swadian_face_younger_1,
        swadian_face_middle_2,
    ],
    [
        "nerpa_soldier",
        "Nerpa Soldier",
        "Nerpa Soldiers",
        tf_guarantee_all,
        0,
        0,
        fac_kingdom_7,
        [
            itm_sword_short_a,
            itm_sword_short_a_v1,
            itm_mace_b,
            itm_mace_b_v1,
            itm_mace_b_v2,
            itm_tab_shield_pavise_a,
            itm_felt_b_v1,
            itm_chapel_c_v2,
            itm_sallet_a_v2,
            (itm_purple_aketon_a, imod_hardened),
            (itm_purple_hauberk_a, 0),
            (itm_purple_hauberk_a, imod_thick),
            itm_hose_d,
            itm_poulaines_d,
        ],
        def_attrib | level(15),
        wp(120),
        knows_common,
        swadian_face_younger_1,
        swadian_face_middle_2,
    ],
    [
        "nerpa_captain",
        "Nerpa Captain",
        "Nerpa Captains",
        tf_guarantee_all,
        0,
        0,
        fac_kingdom_7,
        [
            itm_sword_short_a,
            itm_sword_short_a_v1,
            itm_mace_b,
            itm_mace_b_v1,
            itm_mace_b_v2,
            itm_tab_shield_tauria_a,
            itm_tab_shield_pavise_a,
            itm_tab_shield_pavise_b,
            itm_chapel_c_v2,
            itm_nerpa_sallet_a,
            itm_nerpa_sallet_a_v1,
            (itm_purple_coat_of_plates_b, 0),
            (itm_purple_coat_of_plates_b_v1, 0),
            (itm_purple_hauberk_a, 0),
            (itm_purple_hauberk_a, imod_thick),
            itm_hose_d,
            itm_poulaines_d,
        ],
        def_attrib | level(20),
        wp(150),
        knows_common | knows_ironflesh_2 | knows_power_strike_2 | knows_athletics_3,
        swadian_face_younger_1,
        swadian_face_middle_2,
    ],
    [
        "nerpa_army_veteran",
        "Nerpa Army Veteran",
        "Nerpa Army Veterans",
        tf_guarantee_all,
        0,
        0,
        fac_kingdom_7,
        [
            itm_sword_short_b,
            itm_sword_short_b_v1,
            itm_mace_b,
            itm_mace_b_v1,
            itm_mace_b_v2,
            itm_polearm_light_halberd_a,
            itm_spear_b_v1,
            itm_tab_shield_tauria_a,
            itm_tab_shield_pavise_a,
            itm_tab_shield_pavise_b,
            itm_chapel_c_v2,
            itm_nerpa_sallet_a,
            itm_nerpa_sallet_a_v1,
            (itm_purple_coat_of_plates_c, 0),
            (itm_purple_coat_of_plates_c, imod_thick),
            (itm_purple_coat_of_plates_c_v1, 0),
            (itm_purple_coat_of_plates_c_v1, imod_thick),
            (itm_purple_hauberk_a, imod_reinforced),
            itm_hose_d,
            itm_poulaines_d,
        ],
        def_attrib | level(25),
        wp(180) | wp_polearm(50),
        knows_common | knows_ironflesh_5 | knows_power_strike_5 | knows_athletics_3,
        swadian_face_old_1,
        swadian_face_old_2,
    ],
    [
        "nerpa_mounted_veteran",
        "Nerpa Mounted Veteran",
        "Nerpa Mounted Veterans",
        tf_guarantee_all,
        0,
        0,
        fac_kingdom_7,
        [
            itm_sword_knight_a,
            itm_sword_knight_a_v1,
            itm_lance_a,
            itm_tab_shield_tauria_b,
            itm_nerpa_sallet_a_v2,
            itm_nerpa_sallet_b,
            (itm_purple_coat_of_plates_a, imod_thick),
            (itm_purple_coat_of_plates_a, imod_hardened),
            (itm_purple_coat_of_plates_a, imod_reinforced),
            (itm_purple_coat_of_plates_a_v1, imod_thick),
            (itm_purple_coat_of_plates_a_v1, imod_hardened),
            (itm_purple_coat_of_plates_a_v1, imod_reinforced),
            itm_leather_gloves_a,
            itm_hose_d,
            itm_poulaines_d,
            itm_hunter,
        ],
        def_attrib | level(30),
        wp(210) | wp_polearm(50),
        knows_common
        | knows_ironflesh_5
        | knows_power_strike_5
        | knows_athletics_3
        | knows_riding_5,
        swadian_face_old_1,
        swadian_face_old_2,
    ],
    [
        "nerpa_commader",
        "Nerpa Commander",
        "Nerpa Commanders",
        tf_guarantee_all,
        0,
        0,
        fac_kingdom_7,
        [
            itm_sword_knight_a,
            itm_sword_knight_a_v1,
            itm_lance_a,
            itm_tab_shield_tauria_b,
            itm_nerpa_sallet_a_v3,
            itm_nerpa_sallet_a_v4,
            itm_nerpa_sallet_b_v1,
            itm_nerpa_sallet_b_v2,
            (itm_purple_coat_of_plates_d, 0),
            (itm_purple_coat_of_plates_d, imod_thick),
            (itm_purple_coat_of_plates_d_v1, 0),
            (itm_purple_coat_of_plates_d_v1, imod_thick),
            itm_plate_gauntlets_a,
            itm_plate_boots_b,
            itm_warhorse,
        ],
        def_attrib | level(35),
        wp(240) | wp_polearm(50),
        knows_common
        | knows_ironflesh_6
        | knows_power_strike_6
        | knows_athletics_3
        | knows_riding_8,
        swadian_face_old_1,
        swadian_face_old_2,
    ],
    [
        "nerpa_black_head",
        "Nerpa Black Head",
        "Nerpa Black Heads",
        tf_guarantee_all,
        0,
        0,
        fac_kingdom_7,
        [
            itm_mace_c,
            itm_mace_c_v1,
            itm_tab_shield_pavise_c,
            itm_nerpa_sallet_b_v2,
            itm_nerpa_sallet_b_v3,
            (itm_purple_coat_of_plates_d, 0),
            (itm_purple_coat_of_plates_d, imod_thick),
            (itm_purple_coat_of_plates_d_v1, 0),
            (itm_purple_coat_of_plates_d_v1, imod_thick),
            itm_plate_gauntlets_a,
            itm_plate_boots_b,
            itm_plate_boots_a,
        ],
        def_attrib | level(35),
        wp(240) | wp_one_handed(50),
        knows_common | knows_ironflesh_10 | knows_power_strike_10 | knows_athletics_8,
        swadian_face_old_1,
        swadian_face_old_2,
    ],
    [
        "nerpa_ranger",
        "Nerpa Ranger",
        "Nerpa Rangers",
        tf_guarantee_all,
        0,
        0,
        fac_kingdom_7,
        [
            itm_sword_short_a,
            itm_sword_short_a_v1,
            itm_mace_b,
            itm_mace_b_v1,
            itm_war_darts,
            itm_tab_shield_pavise_c,
            itm_nerpa_sallet_a_v2,
            itm_nerpa_sallet_b,
            (itm_purple_coat_of_plates_a, imod_thick),
            (itm_purple_coat_of_plates_a, imod_hardened),
            (itm_purple_coat_of_plates_a, imod_reinforced),
            (itm_purple_coat_of_plates_a_v1, imod_thick),
            (itm_purple_coat_of_plates_a_v1, imod_hardened),
            (itm_purple_coat_of_plates_a_v1, imod_reinforced),
            itm_leather_gloves_a,
            itm_leather_boots_a,
            itm_hose_d,
            itm_poulaines_d,
        ],
        def_attrib | level(20),
        wp(120) | wp_throwing(50),
        knows_common | knows_ironflesh_3 | knows_power_throw_4 | knows_athletics_2,
        swadian_face_younger_1,
        swadian_face_middle_2,
    ],
    [
        "nerpa_master_ranger",
        "Nerpa Master Ranger",
        "Nerpa Master Rangers",
        tf_guarantee_all,
        0,
        0,
        fac_kingdom_7,
        [
            itm_sword_short_a,
            itm_sword_short_a_v1,
            itm_throwing_spears,
            itm_tab_shield_pavise_c,
            itm_nerpa_sallet_a_v2,
            itm_nerpa_sallet_b,
            (itm_purple_coat_of_plates_c, 0),
            (itm_purple_coat_of_plates_c, imod_thick),
            (itm_purple_coat_of_plates_c_v1, 0),
            (itm_purple_coat_of_plates_c_v1, imod_thick),
            itm_leather_gloves_a,
            itm_leather_gloves_a_v1,
            itm_leather_boots_a,
            itm_hose_d,
            itm_poulaines_d,
        ],
        def_attrib | level(25),
        wp(150) | wp_throwing(50),
        knows_common | knows_ironflesh_5 | knows_power_throw_7 | knows_athletics_4,
        swadian_face_old_1,
        swadian_face_old_2,
    ],
    # hairako
    [
        "hairako_nomad",
        "Hairako Nomad",
        "Hairako Nomads",
        tf_guarantee_armor | tf_guarantee_boots,
        0,
        0,
        fac_kingdom_8,
        [
            itm_spear_b,
            itm_falchion_b,
            itm_falchion_b_v1,
            itm_stones,
            itm_tab_shield_round_a,
            itm_black_turban_a,
            itm_black_turban_b,
            itm_black_turban_c,
            (itm_hairako_shirt_a, 0),
            itm_leather_gloves_a,
            itm_hose_d,
            itm_poulaines_d,
        ],
        def_attrib | level(5),
        wp(60),
        knows_common,
        khergit_face_young_1,
        khergit_face_young_2,
    ],
    [
        "hairako_footman",
        "Hairako Footman",
        "Hairako Footmans",
        tf_guarantee_armor
        | tf_guarantee_boots
        | tf_guarantee_helmet
        | tf_guarantee_shield,
        0,
        0,
        fac_kingdom_8,
        [
            itm_spear_b,
            itm_spear_b_v1,
            itm_falchion_b,
            itm_falchion_b_v1,
            itm_falchion_b_v2,
            itm_stones,
            itm_tab_shield_round_a,
            itm_black_turban_a,
            itm_black_turban_b,
            itm_black_turban_c,
            (itm_hairako_leather_armor_a, 0),
            (itm_hairako_leather_armor_a_v1, 0),
            itm_leather_gloves_a,
            itm_hose_d,
            itm_poulaines_d,
        ],
        def_attrib | level(10),
        wp(90),
        knows_common,
        khergit_face_young_1,
        khergit_face_young_2,
    ],
    [
        "hairako_infantry",
        "Hairako Infantry",
        "Hairako Infantries",
        tf_guarantee_armor
        | tf_guarantee_boots
        | tf_guarantee_helmet
        | tf_guarantee_shield,
        0,
        0,
        fac_kingdom_8,
        [
            itm_spear_b,
            itm_spear_b_v1,
            itm_sword_b_v3,
            itm_solarian_round_shield_e,
            itm_hairako_helmet_a,
            itm_hairako_helmet_a_v1,
            itm_hairako_helmet_b,
            itm_hairako_helmet_b_v1,
            (itm_hairako_leather_armor_a, imod_hardened),
            (itm_hairako_leather_armor_a_v1, imod_hardened),
            itm_leather_gloves_a,
            itm_leather_gloves_b,
            itm_hose_d,
            itm_poulaines_d,
        ],
        def_attrib | level(15),
        wp(120),
        knows_common,
        khergit_face_young_1,
        khergit_face_young_2,
    ],
    [
        "hairako_infantry_veteran",
        "Hairako Infantry Veteran",
        "Hairako Infantry Veterans",
        tf_guarantee_armor
        | tf_guarantee_boots
        | tf_guarantee_helmet
        | tf_guarantee_shield
        | tf_guarantee_gloves,
        0,
        0,
        fac_kingdom_8,
        [
            itm_spear_b,
            itm_spear_b_v1,
            itm_sword_b_v3,
            itm_sword_b_v4,
            itm_throwing_spears,
            itm_solarian_round_shield_e,
            itm_hairako_helmet_a,
            itm_hairako_helmet_a_v1,
            itm_hairako_helmet_b,
            itm_hairako_helmet_b_v1,
            (itm_hairako_leather_armor_b, 0),
            (itm_hairako_leather_armor_b_v1, 0),
            (itm_hairako_hauberk_a, 0),
            itm_leather_gloves_a,
            itm_leather_gloves_b,
            itm_light_leather_boots_c_v1,
            itm_poulaines_d,
        ],
        def_attrib | level(20),
        wp(150),
        knows_common | knows_athletics_5 | knows_power_strike_4,
        khergit_face_middle_1,
        khergit_face_old_2,
    ],
    [
        "hairako_shaitan",
        "Hairako Shaitan",
        "Hairako Shaitans",
        tf_guarantee_armor
        | tf_guarantee_boots
        | tf_guarantee_helmet
        | tf_guarantee_shield
        | tf_guarantee_gloves,
        0,
        0,
        fac_kingdom_8,
        [
            itm_polearm_voulge_c,
            itm_long_pole_mace_b,
            itm_sword_b_v1,
            itm_sword_b_v2,
            itm_sword_b_v4,
            itm_throwing_spears,
            itm_solarian_round_shield_e,
            itm_hairako_noseguard_helmet_a,
            itm_hairako_noseguard_helmet_a_v1,
            (itm_hairako_hauberk_a, imod_thick),
            (itm_hairako_hauberk_a, imod_reinforced),
            itm_leather_gloves_a,
            itm_leather_gloves_b,
            itm_mail_mittens_a,
            itm_mail_boots_c,
        ],
        def_attrib | level(25),
        wp(180),
        knows_common | knows_athletics_10 | knows_power_strike_9 | knows_ironflesh_10,
        khergit_face_middle_1,
        khergit_face_old_2,
    ],
    [
        "hairako_rider",
        "Hairako Rider",
        "Hairako Riders",
        tf_mounted
        | tf_guarantee_horse
        | tf_guarantee_armor
        | tf_guarantee_helmet
        | tf_guarantee_shield
        | tf_guarantee_boots
        | tf_guarantee_gloves,
        0,
        0,
        fac_kingdom_8,
        [
            itm_sword_b_v3,
            itm_lance_b,
            itm_solarian_round_shield_e,
            itm_hairako_helmet_a,
            itm_hairako_helmet_a_v1,
            itm_hairako_helmet_b,
            itm_hairako_helmet_b_v1,
            (itm_hairako_leather_armor_b, 0),
            (itm_hairako_leather_armor_b_v1, 0),
            itm_leather_gloves_a,
            itm_leather_gloves_b,
            itm_hose_d,
            itm_poulaines_d,
            itm_saddle_horse,
            itm_saddle_horse_b,
        ],
        def_attrib | level(15),
        wp(120),
        knows_common | knows_riding_4,
        khergit_face_young_1,
        khergit_face_young_2,
    ],
    [
        "hairako_experienced_rider",
        "Hairako Experienced Rider",
        "Hairako Experienced Riders",
        tf_mounted
        | tf_guarantee_horse
        | tf_guarantee_armor
        | tf_guarantee_helmet
        | tf_guarantee_shield
        | tf_guarantee_boots
        | tf_guarantee_gloves,
        0,
        0,
        fac_kingdom_8,
        [
            itm_sword_b_v3,
            itm_lance_b_v1,
            itm_solarian_round_shield_e,
            itm_hairako_helmet_a_v2,
            itm_hairako_helmet_b_v2,
            (itm_hairako_leather_armor_b, imod_hardened),
            (itm_hairako_leather_armor_b_v1, imod_hardened),
            itm_leather_gloves_a,
            itm_leather_gloves_b,
            itm_leather_boots_a,
            itm_leather_boots_b,
            itm_steppe_horse,
            itm_steppe_horse_b,
        ],
        def_attrib | level(20),
        wp(150),
        knows_common | knows_riding_5 | knows_ironflesh_4,
        khergit_face_old_1,
        khergit_face_old_2,
    ],
    [
        "hairako_mounted_shaitan",
        "Hairako Mounted Shaitan",
        "Hairako Mounted Shaitans",
        tf_mounted
        | tf_guarantee_horse
        | tf_guarantee_armor
        | tf_guarantee_helmet
        | tf_guarantee_shield
        | tf_guarantee_boots
        | tf_guarantee_gloves,
        0,
        0,
        fac_kingdom_8,
        [
            itm_sword_b_v3,
            itm_sword_b_v4,
            itm_lance_b_v2,
            itm_lance_b_v3,
            itm_solarian_round_shield_e,
            itm_hairako_noseguard_helmet_a_v3,
            itm_hairako_noseguard_helmet_a_v4,
            itm_hairako_noseguard_helmet_a_v5,
            (itm_hairako_leather_armor_b, imod_reinforced),
            (itm_hairako_leather_armor_b_v1, imod_reinforced),
            itm_leather_gloves_b_v1,
            itm_leather_boots_a,
            itm_leather_boots_b,
            itm_steppe_horse_b,
            itm_steppe_horse_c,
            itm_steppe_horse_d,
        ],
        def_attrib | level(25),
        wp(180),
        knows_common | knows_riding_8 | knows_ironflesh_10 | knows_power_strike_7,
        khergit_face_old_1,
        khergit_face_old_2,
    ],
    [
        "hairako_archer",
        "Hairako Archer",
        "Hairako Archers",
        tf_guarantee_armor | tf_guarantee_boots | tf_guarantee_ranged,
        0,
        0,
        fac_kingdom_8,
        [
            itm_falchion_b,
            itm_falchion_b_v1,
            itm_short_bow,
            itm_arrows,
            itm_tab_shield_round_a,
            itm_black_turban_a,
            itm_black_turban_b,
            itm_black_turban_c,
            (itm_hairako_shirt_a, 0),
            itm_leather_gloves_a,
            itm_hose_d,
            itm_poulaines_d,
        ],
        def_attrib | level(10),
        wp(90) | wp_archery(50),
        knows_common | knows_power_draw_4,
        khergit_face_young_1,
        khergit_face_young_2,
    ],
    [
        "hairako_sniper",
        "Hairako Sniper",
        "Hairako Snipers",
        tf_guarantee_armor | tf_guarantee_boots | tf_guarantee_ranged,
        0,
        0,
        fac_kingdom_8,
        [
            itm_falchion_b,
            itm_falchion_b_v1,
            itm_spear_b,
            itm_long_bow,
            itm_arrows,
            itm_solarian_round_shield_e,
            itm_black_turban_a,
            itm_black_turban_b,
            itm_black_turban_c,
            (itm_hairako_leather_armor_a, 0),
            (itm_hairako_leather_armor_a_v1, 0),
            itm_leather_gloves_a,
            itm_hose_d,
            itm_poulaines_d,
        ],
        def_attrib | level(15),
        wp(120) | wp_archery(50),
        knows_common | knows_power_draw_6,
        khergit_face_young_1,
        khergit_face_young_2,
    ],
    [
        "hairako_sniper_elite",
        "Hairako Sniper Elite",
        "Hairako Sniper Elites",
        tf_guarantee_armor | tf_guarantee_boots | tf_guarantee_ranged,
        0,
        0,
        fac_kingdom_8,
        [
            itm_falchion_b,
            itm_falchion_b_v1,
            itm_spear_b,
            itm_long_bow,
            itm_arrows,
            itm_solarian_round_shield_e,
            itm_hairako_helmet_b,
            itm_hairako_helmet_b_v1,
            (itm_hairako_leather_armor_b, 0),
            (itm_hairako_leather_armor_b_v1, 0),
            itm_leather_gloves_a,
            itm_hose_d,
            itm_poulaines_d,
        ],
        def_attrib | level(20),
        wp(180) | wp_archery(50),
        knows_common | knows_power_draw_9 | knows_athletics_5 | knows_ironflesh_4,
        khergit_face_old_1,
        khergit_face_old_2,
    ],
    # tauria
    # TODO: battle priest and spearman/helbardier
    [
        "tauria_recruit",
        "Tauria Recruit",
        "Tauria Recruits",
        tf_guarantee_armor | tf_guarantee_boots,
        0,
        0,
        fac_kingdom_9,
        [
            itm_falchion_a,
            itm_hatchet_a,
            itm_stones,
            itm_tab_shield_tauria_a,
            itm_arming_cap_a,
            itm_adventurer_hood_a,
            (itm_tauria_aketon_a, 0),
            (itm_tauria_aketon_a_v1, 0),
            itm_leather_gloves_a,
            itm_poulaines_d,
            itm_hose_d,
        ],
        def_attrib | level(5),
        wp(60),
        knows_common,
        swadian_face_young_1,
        swadian_face_young_2,
    ],
    [
        "tauria_trooper",
        "Tauria Trooper",
        "Tauria Troopers",
        tf_guarantee_armor | tf_guarantee_boots,
        0,
        0,
        fac_kingdom_9,
        [
            itm_falchion_a,
            itm_falchion_a_v2,
            itm_hatchet_a,
            itm_polearm_military_scythe_a,
            itm_spear_a,
            itm_tab_shield_tauria_a,
            itm_arming_cap_a,
            itm_adventurer_hood_a,
            (itm_tauria_aketon_a, imod_thick),
            (itm_tauria_aketon_a_v1, imod_thick),
            itm_leather_gloves_a,
            itm_poulaines_d,
            itm_hose_d,
        ],
        def_attrib | level(10),
        wp(90),
        knows_common,
        swadian_face_young_1,
        swadian_face_young_2,
    ],
    [
        "tauria_soldier",
        "Tauria Soldier",
        "Tauria Soldiers",
        tf_guarantee_armor
        | tf_guarantee_boots
        | tf_guarantee_helmet
        | tf_guarantee_shield
        | tf_guarantee_gloves,
        0,
        0,
        fac_kingdom_9,
        [
            itm_sword_short_a,
            itm_mace_b,
            itm_spear_a,
            itm_tab_shield_tauria_a,
            itm_sallet_a_v1,
            (itm_tauria_brigandine_a, 0),
            (itm_tauria_brigandine_a, imod_thick),
            (itm_tauria_brigandine_a_v1, 0),
            (itm_tauria_brigandine_a_v1, imod_thick),
            itm_leather_gloves_a,
            itm_poulaines_d,
            itm_hose_d,
        ],
        def_attrib | level(15),
        wp(120),
        knows_common,
        swadian_face_young_1,
        swadian_face_young_2,
    ],
    [
        "tauria_foot_knight",
        "Tauria Foot Knight",
        "Tauria Foot Knights",
        tf_guarantee_armor
        | tf_guarantee_boots
        | tf_guarantee_helmet
        | tf_guarantee_shield
        | tf_guarantee_gloves,
        0,
        0,
        fac_kingdom_9,
        [
            itm_sword_short_a,
            itm_mace_b,
            itm_spear_a,
            itm_polearm_military_scythe_a,
            itm_tab_shield_tauria_a,
            itm_sallet_a_v2,
            itm_sallet_b_v2,
            (itm_tauria_brigandine_b, 0),
            (itm_tauria_brigandine_b, imod_thick),
            (itm_tauria_brigandine_b_v1, 0),
            (itm_tauria_brigandine_b_v1, imod_thick),
            itm_leather_gloves_a,
            itm_poulaines_d,
            itm_hose_d,
        ],
        def_attrib | level(20),
        wp(150),
        knows_common,
        swadian_face_young_1,
        swadian_face_young_2,
    ],
    [
        "tauria_sword_master",
        "Tauria Sword Master",
        "Tauria Sword Masters",
        tf_guarantee_armor
        | tf_guarantee_boots
        | tf_guarantee_helmet
        | tf_guarantee_shield
        | tf_guarantee_gloves,
        0,
        0,
        fac_kingdom_9,
        [
            itm_sword_a,
            itm_sword_a_v1,
            itm_mace_b,
            itm_mace_b_v1,
            itm_polearm_military_scythe_a,
            itm_voulge_a,
            itm_tab_shield_tauria_a,
            itm_sallet_a_v2,
            itm_sallet_b_v2,
            itm_eyeslot_kettlehat_a_v2,
            (itm_tauria_brigandine_c, 0),
            (itm_tauria_brigandine_c, imod_reinforced),
            (itm_tauria_brigandine_c_v1, 0),
            (itm_tauria_brigandine_c_v1, imod_reinforced),
            itm_leather_gloves_a,
            itm_poulaines_d,
            itm_hose_d,
        ],
        def_attrib | level(25),
        wp(180),
        knows_common,
        swadian_face_young_1,
        swadian_face_young_2,
    ],
    [
        "tauria_man_at_arms",
        "Tauria Man-at-Arms",
        "Tauria Men-at-Arms",
        tf_guarantee_armor
        | tf_guarantee_boots
        | tf_guarantee_helmet
        | tf_guarantee_shield
        | tf_guarantee_gloves,
        0,
        0,
        fac_kingdom_9,
        [
            itm_sword_a,
            itm_sword_a_v1,
            itm_mace_c,
            itm_mace_c_v1,
            itm_polearm_military_scythe_a,
            itm_voulge_a,
            itm_tab_shield_tauria_b,
            itm_sallet_a_v4,
            itm_sallet_b_v4,
            itm_eyeslot_kettlehat_a_v2,
            (itm_tauria_brigandine_d, 0),
            (itm_tauria_brigandine_d, imod_reinforced),
            (itm_tauria_brigandine_d_v1, 0),
            (itm_tauria_brigandine_d_v1, imod_reinforced),
            itm_plate_gauntlets_a,
            itm_plate_boots_a,
            itm_plate_boots_b,
        ],
        def_attrib | level(30),
        wp(210),
        knows_common | knows_ironflesh_7 | knows_power_strike_7,
        swadian_face_old_1,
        swadian_face_old_2,
    ],
    [
        "tauria_horseman",
        "Tauria Horseman",
        "Tauria Horsemans",
        tf_guarantee_armor
        | tf_guarantee_boots
        | tf_guarantee_helmet
        | tf_guarantee_shield
        | tf_mounted
        | tf_guarantee_horse,
        0,
        0,
        fac_kingdom_9,
        [
            itm_sword_short_a,
            itm_mace_b,
            itm_spear_a,
            itm_tab_shield_tauria_a,
            itm_sallet_a_v2,
            itm_sallet_b_v2,
            (itm_tauria_brigandine_b, 0),
            (itm_tauria_brigandine_b, imod_thick),
            (itm_tauria_brigandine_b_v1, 0),
            (itm_tauria_brigandine_b_v1, imod_thick),
            itm_leather_gloves_a,
            itm_poulaines_d,
            itm_hose_d,
            itm_hunter,
        ],
        def_attrib | level(20),
        wp(150),
        knows_common | knows_riding_3,
        swadian_face_young_1,
        swadian_face_young_2,
    ],
    [
        "tauria_knight",
        "Tauria Knight",
        "Tauria Knights",
        tf_guarantee_armor
        | tf_guarantee_boots
        | tf_guarantee_helmet
        | tf_guarantee_shield
        | tf_mounted
        | tf_guarantee_horse
        | tf_guarantee_gloves,
        0,
        0,
        fac_kingdom_9,
        [
            itm_sword_a,
            itm_sword_a_v1,
            itm_mace_b,
            itm_mace_b_v1,
            itm_lance_a,
            itm_tab_shield_tauria_b,
            itm_sallet_a_v2,
            itm_sallet_b_v2,
            itm_eyeslot_kettlehat_a_v2,
            (itm_tauria_brigandine_c, 0),
            (itm_tauria_brigandine_c, imod_reinforced),
            (itm_tauria_brigandine_c_v1, 0),
            (itm_tauria_brigandine_c_v1, imod_reinforced),
            itm_leather_gloves_a,
            itm_leather_boots_a,
            itm_warhorse,
        ],
        def_attrib | level(25),
        wp(180),
        knows_common | knows_riding_5 | knows_ironflesh_4,
        swadian_face_young_1,
        swadian_face_young_2,
    ],
    [
        "tauria_noble_knight",
        "Tauria Noble Knight",
        "Tauria Noble Knights",
        tf_guarantee_armor
        | tf_guarantee_boots
        | tf_guarantee_helmet
        | tf_guarantee_shield
        | tf_mounted
        | tf_guarantee_horse
        | tf_guarantee_gloves,
        0,
        0,
        fac_kingdom_9,
        [
            itm_sword_a,
            itm_sword_a_v1,
            itm_lance_a,
            itm_lance_a_v1,
            itm_tab_shield_tauria_b,
            itm_sallet_a_v3,
            itm_sallet_b_v3,
            itm_eyeslot_kettlehat_a_v3,
            (itm_tauria_brigandine_d, 0),
            (itm_tauria_brigandine_d, imod_reinforced),
            (itm_tauria_brigandine_d_v1, 0),
            (itm_tauria_brigandine_d_v1, imod_reinforced),
            itm_plate_gauntlets_a,
            itm_plate_boots_a,
            itm_plate_boots_b,
            itm_warhorse,
        ],
        def_attrib | level(30),
        wp(210) | wp_melee(50),
        knows_common | knows_riding_8 | knows_ironflesh_10 | knows_power_strike_10,
        swadian_face_old_1,
        swadian_face_old_2,
    ],
    [
        "tauria_crossbowman",
        "Tauria Crossbowman",
        "Tauria Crossbowmans",
        tf_guarantee_armor
        | tf_guarantee_boots
        | tf_guarantee_helmet
        | tf_guarantee_shield
        | tf_guarantee_ranged,
        0,
        0,
        fac_kingdom_9,
        [
            itm_crossbow,
            itm_bolts,
            itm_mace_b,
            itm_tab_shield_tauria_b,
            itm_eyeslot_kettlehat_a_v2,
            (itm_tauria_brigandine_a, imod_hardened),
            (itm_tauria_brigandine_a_v1, imod_hardened),
            itm_leather_gloves_a,
            itm_leather_boots_a,
        ],
        def_attrib | level(15),
        wp(120) | wp_crossbow(50),
        knows_common,
        swadian_face_young_1,
        swadian_face_young_2,
    ],
    [
        "tauria_siege_crossbowman",
        "Tauria Siege Crossbowman",
        "Tauria Siege Crossbowmans",
        tf_guarantee_armor
        | tf_guarantee_boots
        | tf_guarantee_helmet
        | tf_guarantee_shield
        | tf_guarantee_ranged,
        0,
        0,
        fac_kingdom_9,
        [
            itm_heavy_crossbow,
            itm_bolts,
            itm_piercing_bolts,
            itm_mace_b,
            itm_mace_b_v1,
            itm_mace_b_v2,
            itm_tab_shield_tauria_b,
            itm_eyeslot_kettlehat_a_v3,
            (itm_tauria_brigandine_b, imod_thick),
            (itm_tauria_brigandine_b_v1, imod_thick),
            itm_leather_gloves_a,
            itm_leather_boots_a,
        ],
        def_attrib | level(20),
        wp(150) | wp_crossbow(50),
        knows_common,
        swadian_face_middle_1,
        swadian_face_old_2,
    ],
    # elen
    [
        "elen_novice",
        "Elen Novice",
        "Elen Novices",
        tf_guarantee_armor | tf_guarantee_boots,
        0,
        0,
        fac_kingdom_10,
        [
            itm_arming_cap_a,
            itm_leather_gloves_a,
            itm_mace_1,
            itm_hatchet_b,
            itm_spear,
            itm_tab_shield_tauria_a,
            itm_hose_b,
            itm_poulaines_b,
        ],
        def_attrib | level(5),
        wp(60),
        knows_common | swadian_face_young_1,
        swadian_face_young_2,
    ],
    [
        "elen_footman",
        "Elen Footman",
        "Elen Footmen",
        tf_guarantee_armor | tf_guarantee_boots | tf_guarantee_helmet,
        0,
        0,
        fac_kingdom_10,
        [
            itm_leather_gloves_a,
            itm_falchion_a,
            itm_flanged_mace,
            itm_military_scythe,
            itm_fighting_axe,
            itm_tab_shield_tauria_a,
            itm_hose_b,
            itm_poulaines_b,
        ],
        def_attrib | level(10),
        wp(90),
        knows_common | swadian_face_young_1,
        swadian_face_young_2,
    ],
    [
        "elen_fighter",
        "Elen Fighter",
        "Elen Fighters",
        tf_guarantee_armor
        | tf_guarantee_boots
        | tf_guarantee_helmet
        | tf_guarantee_shield,
        0,
        0,
        fac_kingdom_10,
        [
            itm_leather_gloves_a,
            itm_leather_gloves_a_v1,
            itm_tab_shield_tauria_a,
            itm_hose_b,
            itm_poulaines_b,
            itm_leather_boots_a,
        ],
        def_attrib | level(15),
        wp(120),
        knows_common | knows_ironflesh_2,
        swadian_face_young_1,
        swadian_face_young_2,
    ],
    [
        "elen_light_infantry",
        "Elen Light Infantry",
        "Elen Light Infantries",
        tf_guarantee_armor
        | tf_guarantee_boots
        | tf_guarantee_helmet
        | tf_guarantee_shield
        | tf_guarantee_gloves,
        0,
        0,
        fac_kingdom_10,
        [
            itm_leather_gloves_a_v1,
            itm_mail_mittens_a_v1,
            itm_mail_mittens_a,
            itm_flanged_mace,
            itm_winged_mace,
            itm_m_glaive_b,
            itm_military_scythe,
            itm_crusader_spear_inf_a,
            itm_tab_shield_tauria_a,
            itm_leather_boots_a,
            itm_leather_boots_b,
            itm_mail_boots_a,
        ],
        def_attrib | level(20),
        wp(150),
        knows_common | knows_ironflesh_3,
        swadian_face_young_1,
        swadian_face_young_2,
    ],
    [
        "elen_heavy_infantry",
        "Elen Heavy Infantry",
        "Elen Heavy Infantries",
        tf_guarantee_armor
        | tf_guarantee_boots
        | tf_guarantee_helmet
        | tf_guarantee_shield
        | tf_guarantee_gloves,
        0,
        0,
        fac_kingdom_10,
        [
            itm_leather_gloves_a_v1,
            itm_mail_mittens_a_v1,
            itm_mail_mittens_a,
            itm_plate_gauntlets_a_v1,
            itm_heavy_infantry_axe,
            itm_strange_winged_mace,
            itm_winged_mace,
            itm_m_glaive_b,
            itm_m_glaive_a,
            itm_crusader_spear_inf_b,
            itm_tab_shield_tauria_a,
            itm_mail_boots_a,
            itm_mail_boots_b,
            itm_plate_boots_a,
            itm_plate_boots_b,
        ],
        def_attrib | level(25),
        wp(180),
        knows_common | knows_ironflesh_5 | knows_power_strike_5,
        swadian_face_young_1,
        swadian_face_young_2,
    ],
    [
        "elen_cheif",
        "Elen Cheif",
        "Elen Cheifs",
        tf_guarantee_armor
        | tf_guarantee_boots
        | tf_guarantee_helmet
        | tf_guarantee_shield
        | tf_guarantee_gloves
        | tf_guarantee_horse,
        0,
        0,
        fac_kingdom_10,
        [
            itm_mail_mittens_a_v1,
            itm_mail_mittens_a,
            itm_crusader_knight_spear_a,
            itm_crusader_knight_spear_b,
            itm_tab_shield_tauria_a,
            itm_mail_boots_a,
            itm_mail_boots_b,
            itm_plate_boots_a,
            itm_plate_boots_b,
        ],
        tier_two_attrib | level(30),
        wp(210),
        knows_common | knows_ironflesh_9 | knows_power_strike_9 | knows_riding_8,
        swadian_face_young_1,
        swadian_face_young_2,
    ],
    [
        "elen_archer",
        "Elen Archer",
        "Elen Archers",
        tf_guarantee_armor
        | tf_guarantee_boots
        | tf_guarantee_helmet
        | tf_guarantee_shield
        | tf_guarantee_gloves
        | tf_guarantee_ranged,
        0,
        0,
        fac_kingdom_10,
        [
            itm_leather_gloves_a,
            itm_mace_1,
            itm_hatchet_b,
            itm_arrows,
            itm_hunting_bow,
            itm_leather_boots_a,
            itm_leather_boots_b,
            itm_hose_b,
            itm_poulaines_b,
        ],
        def_attrib | level(15),
        wp(120) | wp_archery(50),
        knows_common | knows_ironflesh_2 | knows_power_draw_3,
        swadian_face_young_1,
        swadian_face_young_2,
    ],
    [
        "elen_experienced_archer",
        "Elen Experienced Archer",
        "Elen Experienced Archers",
        tf_guarantee_armor
        | tf_guarantee_boots
        | tf_guarantee_helmet
        | tf_guarantee_shield
        | tf_guarantee_gloves
        | tf_guarantee_ranged,
        0,
        0,
        fac_kingdom_10,
        [
            itm_leather_gloves_a,
            itm_falchion_a,
            itm_flanged_mace,
            itm_fighting_axe,
            itm_arrows,
            itm_long_bow,
            itm_leather_boots_a,
            itm_leather_boots_b,
            itm_hose_b,
            itm_poulaines_b,
        ],
        def_attrib | level(20),
        wp(150) | wp_archery(50),
        knows_common | knows_ironflesh_2 | knows_power_draw_4,
        swadian_face_young_1,
        swadian_face_young_2,
    ],
    [
        "elen_sniper",
        "Elen Sniper",
        "Elen Snipers",
        tf_guarantee_armor
        | tf_guarantee_boots
        | tf_guarantee_helmet
        | tf_guarantee_shield
        | tf_guarantee_gloves
        | tf_guarantee_ranged,
        0,
        0,
        fac_kingdom_10,
        [
            itm_leather_gloves_a,
            itm_falchion_a,
            itm_flanged_mace,
            itm_tab_shield_pavise_b,
            itm_tab_shield_pavise_c,
            itm_crossbow,
            itm_bolts,
            itm_leather_boots_a,
            itm_leather_boots_b,
            itm_mail_boots_a,
            itm_mail_boots_b,
        ],
        def_attrib | level(20),
        wp(150) | wp_crossbow(70),
        knows_common | knows_ironflesh_2 | knows_power_strike_2,
        swadian_face_young_1,
        swadian_face_young_2,
    ],
    # Adid units
    # Nomad Scout - Desert Vanguard - Sultanate Vanguard
    [
        "adid_nomad_scout",
        "Adid Nomad Scout",
        "Adid Nomad Scouts",
        tf_guarantee_boots | tf_guarantee_armor,
        0,
        0,
        fac_kingdom_11,
        [
            itm_leather_gloves_a_v1,
            itm_spiked_club,
            itm_falchion_a,
            itm_falchion_b,
            itm_long_spiked_club,
            itm_tab_shield_tauria_a,
            itm_leather_shoes_a,
            itm_leather_shoes_b,
        ],
        def_attrib | level(5),
        wp(60),
        knows_common,
        swadian_face_younger_1,
        swadian_face_middle_2,
    ],
    [
        "adid_desert_vanguard",
        "Adid Desert Vanguard",
        "Adid Desert Vanguards",
        tf_guarantee_boots
        | tf_guarantee_armor
        | tf_guarantee_helmet
        | tf_guarantee_shield,
        0,
        0,
        fac_kingdom_11,
        [
            itm_leather_gloves_a_v1,
            itm_leather_gloves_a,
            itm_scimitar,
            itm_falchion_a,
            itm_falchion_b,
            itm_voulge_a,
            itm_spear,
            itm_tab_shield_tauria_a,
            itm_leather_shoes_a,
            itm_leather_shoes_b,
        ],
        def_attrib | level(10),
        wp(90),
        knows_common,
        swadian_face_young_1,
        swadian_face_middle_2,
    ],
    [
        "adid_sultanate_vanguard",
        "Adid Sultanate Vanguard",
        "Adid Sultanate Vanguards",
        tf_guarantee_boots
        | tf_guarantee_armor
        | tf_guarantee_helmet
        | tf_guarantee_shield
        | tf_guarantee_gloves,
        0,
        0,
        fac_kingdom_11,
        [
            itm_leather_gloves_a,
            itm_leather_gloves_a,
            itm_leather_gloves_a_v1,
            itm_falchion_a,
            itm_falchion_b,
            itm_hafted_blade_a,
            itm_hafted_blade_b,
            itm_hafted_blade_c,
            itm_hafted_blade_d,
            itm_hafted_blade_e,
            itm_hafted_blade_f,
            itm_tab_shield_tauria_a,
            itm_leather_shoes_a,
            itm_leather_shoes_b,
        ],
        def_attrib | level(15),
        wp(120),
        knows_common,
        swadian_face_young_1,
        swadian_face_middle_2,
    ],
    # Sultanate Vanguard - Camel Rider - Sandstalker
    [
        "adid_camel_rider",
        "Adid Camel Rider",
        "Adid Camel Riders",
        tf_guarantee_boots
        | tf_guarantee_armor
        | tf_guarantee_helmet
        | tf_guarantee_shield
        | tf_guarantee_gloves
        | tf_mounted
        | tf_guarantee_horse
        | tf_guarantee_ranged,
        0,
        0,
        fac_kingdom_11,
        [
            itm_leather_gloves_a_v1,
            itm_falchion_a,
            itm_falchion_b,
            itm_nomad_bow,
            itm_arrows,
            itm_maa_camel_light_c,
            itm_maa_camel_light_d,
            itm_tab_shield_tauria_a,
            itm_leather_shoes_a,
            itm_leather_shoes_b,
        ],
        def_attrib | level(20),
        wp(150) | wp_archery(50),
        knows_common | knows_riding_5 | knows_horse_archery_5,
        swadian_face_young_1,
        swadian_face_middle_2,
    ],
    [
        "adid_sandstalker",
        "Adid Sandstalker",
        "Adid Sandstalkers",
        tf_guarantee_boots
        | tf_guarantee_armor
        | tf_guarantee_helmet
        | tf_guarantee_shield
        | tf_guarantee_gloves
        | tf_mounted
        | tf_guarantee_horse
        | tf_guarantee_ranged,
        0,
        0,
        fac_kingdom_11,
        [
            itm_leather_gloves_a_v1,
            itm_leather_gloves_a,
            itm_leather_gloves_a,
            itm_hafted_blade_a,
            itm_hafted_blade_b,
            itm_hafted_blade_c,
            itm_hafted_blade_d,
            itm_hafted_blade_e,
            itm_hafted_blade_f,
            itm_strong_bow,
            itm_barbed_arrows,
            itm_maa_camel_war_a,
            itm_maa_camel_war_b,
            itm_maa_camel_war_c,
            itm_maa_camel_war_d,
            itm_tab_shield_tauria_a,
            itm_light_leather_boots_a,
            itm_light_leather_boots_b,
            itm_light_leather_boots_c,
        ],
        def_attrib | level(25),
        wp(180) | wp_archery(50),
        knows_common | knows_riding_5 | knows_horse_archery_8,
        swadian_face_young_1,
        swadian_face_middle_2,
    ],
    # Sultanate Vanguard - Serpent Guard - Oasis Acolyte
    [
        "adid_serpent_guard",
        "Adid Serpent Guard",
        "Adid Serpent Guards",
        tf_guarantee_boots
        | tf_guarantee_armor
        | tf_guarantee_helmet
        | tf_guarantee_shield
        | tf_guarantee_gloves,
        0,
        0,
        fac_kingdom_11,
        [
            itm_mail_mittens_a,
            itm_mail_mittens_a_v1,
            itm_leather_gloves_a_v1,
            itm_strange_winged_mace,
            itm_strange_winged_mace_decorated,
            itm_falchion_b,
            itm_hafted_blade_a,
            itm_hafted_blade_b,
            itm_hafted_blade_c,
            itm_hafted_blade_d,
            itm_hafted_blade_e,
            itm_hafted_blade_f,
            itm_tab_shield_tauria_a,
            itm_light_leather_boots_a,
            itm_light_leather_boots_b,
            itm_light_leather_boots_c,
        ],
        def_attrib | level(20),
        wp(150) | wp_polearm(50),
        knows_common,
        swadian_face_young_1,
        swadian_face_middle_2,
    ],
    [
        "adid_oasis_acolyte",
        "Adid Oasis Acolyte",
        "Adid Oasis Acolytes",
        tf_guarantee_boots
        | tf_guarantee_armor
        | tf_guarantee_helmet
        | tf_guarantee_shield
        | tf_guarantee_gloves,
        0,
        0,
        fac_kingdom_11,
        [
            itm_mail_mittens_a,
            itm_mail_mittens_a_v1,
            itm_falchion_b,
            itm_hafted_blade_a,
            itm_hafted_blade_b,
            itm_hafted_blade_c,
            itm_hafted_blade_d,
            itm_hafted_blade_e,
            itm_hafted_blade_f,
            itm_battle_trident,
            itm_tab_shield_tauria_a,
            itm_light_leather_boots_a,
            itm_light_leather_boots_b,
            itm_light_leather_boots_c,
        ],
        def_attrib | level(25),
        wp(180) | wp_polearm(50),
        knows_common | knows_ironflesh_4 | knows_power_throw_4,
        swadian_face_young_1,
        swadian_face_middle_2,
    ],
    # Oasis Acolyte - Oasis Priest - Oasis High Priest
    [
        "adid_oasis_priest",
        "Adid Oasis Priest",
        "Adid Oasis Priests",
        tf_guarantee_boots
        | tf_guarantee_armor
        | tf_guarantee_helmet
        | tf_guarantee_shield
        | tf_guarantee_gloves,
        0,
        0,
        fac_kingdom_11,
        [
            itm_mail_mittens_a,
            itm_mail_mittens_a_v1,
            itm_eastern_scale_gloves_a,
            itm_eastern_scale_gloves_b,
            itm_falchion_b,
            itm_hafted_blade_a,
            itm_hafted_blade_b,
            itm_hafted_blade_c,
            itm_hafted_blade_d,
            itm_hafted_blade_e,
            itm_hafted_blade_f,
            itm_battle_trident,
            itm_eastern_round_shield_a,
            itm_eastern_round_shield_b,
            itm_eastern_round_shield_c,
            itm_throwing_spears,
            itm_light_leather_boots_a,
            itm_light_leather_boots_b,
            itm_light_leather_boots_c,
        ],
        def_attrib | level(30),
        wp(210) | wp_polearm(50),
        knows_common
        | knows_ironflesh_9
        | knows_power_strike_5
        | knows_athletics_6
        | knows_power_throw_5,
        swadian_face_young_1,
        swadian_face_middle_2,
    ],
    [
        "adid_oasis_high_priest",
        "Adid Oasis High Priest",
        "Adid Oasis High Priests",
        tf_guarantee_boots
        | tf_guarantee_armor
        | tf_guarantee_helmet
        | tf_guarantee_shield
        | tf_guarantee_gloves,
        0,
        0,
        fac_kingdom_11,
        [
            itm_eastern_scale_gloves_a,
            itm_eastern_scale_gloves_b,
            itm_falchion_b,
            itm_sword_b,
            itm_sword_b_v1,
            itm_hafted_blade_a,
            itm_hafted_blade_b,
            itm_hafted_blade_c,
            itm_hafted_blade_d,
            itm_hafted_blade_e,
            itm_hafted_blade_f,
            itm_battle_trident,
            itm_eastern_round_shield_a,
            itm_eastern_round_shield_b,
            itm_eastern_round_shield_c,
            itm_throwing_spears,
            itm_mail_boots_a,
            itm_mail_boots_b,
            itm_mail_boots_c,
        ],
        def_attrib | level(35),
        wp(240) | wp_polearm(50),
        knows_common
        | knows_ironflesh_10
        | knows_power_strike_10
        | knows_athletics_6
        | knows_power_throw_7,
        swadian_face_young_1,
        swadian_face_middle_2,
    ],
    # Oasis Acolyte - Royal Lancer - Golden Falcon
    [
        "adid_royal_lancer",
        "Adid Royal Lancer",
        "Adid Royal Lancers",
        tf_guarantee_boots
        | tf_guarantee_armor
        | tf_guarantee_helmet
        | tf_guarantee_shield
        | tf_guarantee_gloves
        | tf_mounted
        | tf_guarantee_horse,
        0,
        0,
        fac_kingdom_11,
        [
            itm_mail_mittens_a,
            itm_mail_mittens_a_v1,
            itm_eastern_scale_gloves_a,
            itm_eastern_scale_gloves_b,
            itm_sword_b_v4,
            itm_eastern_round_shield_a,
            itm_eastern_round_shield_b,
            itm_eastern_round_shield_c,
            itm_lance,
            itm_hafted_blade_a,
            itm_hafted_blade_b,
            itm_hafted_blade_c,
            itm_hafted_blade_d,
            itm_hafted_blade_e,
            itm_hafted_blade_f,
            itm_arabian_horse_a,
            itm_arabian_horse_b,
            itm_mail_boots_a,
            itm_mail_boots_b,
            itm_mail_boots_c,
        ],
        def_attrib | level(30),
        wp(210),
        knows_common | knows_ironflesh_9 | knows_power_strike_5 | knows_riding_6,
        swadian_face_young_1,
        swadian_face_middle_2,
    ],
    [
        "adid_golden_falcon",
        "Adid Golden Falcon",
        "Adid Golden Falcons",
        tf_guarantee_boots
        | tf_guarantee_armor
        | tf_guarantee_helmet
        | tf_guarantee_shield
        | tf_guarantee_gloves
        | tf_mounted
        | tf_guarantee_horse,
        0,
        0,
        fac_kingdom_11,
        [
            itm_mail_mittens_a,
            itm_mail_mittens_a_v1,
            itm_eastern_scale_gloves_a,
            itm_eastern_scale_gloves_b,
            itm_sword_b_v4,
            itm_hatchet_a,
            itm_hatchet_b,
            itm_eastern_round_shield_a,
            itm_eastern_round_shield_b,
            itm_eastern_round_shield_c,
            itm_lance,
            itm_hafted_blade_a,
            itm_hafted_blade_b,
            itm_hafted_blade_c,
            itm_hafted_blade_d,
            itm_hafted_blade_e,
            itm_hafted_blade_f,
            itm_arabian_horse_a,
            itm_arabian_horse_b,
            itm_arabian_horse_c,
            itm_arabian_horse_d,
            itm_mail_boots_a,
            itm_mail_boots_b,
            itm_mail_boots_c,
        ],
        def_attrib | level(35),
        wp(240),
        knows_common | knows_ironflesh_10 | knows_power_strike_7 | knows_riding_8,
        swadian_face_young_1,
        swadian_face_middle_2,
    ],
    # Stormguard units
    # Mountaineer - Thunderguard - Stormbringers - Avalanche Warriors
    [
        "stormguard_mountaineer",
        "Stormguard Mountaineer",
        "Stormguard Mountaineers",
        tf_guarantee_armor | tf_guarantee_boots,
        0,
        0,
        fac_kingdom_12,
        [
            itm_pilgrim_hood,
            itm_leather_gloves_a,
            itm_hatchet_a,
            itm_falchion_a,
            itm_pickaxe_a_v1,
            itm_tab_shield_tauria_a,
            itm_boar_spear,
            itm_poulaines_d,
        ],
        def_attrib | level(5),
        wp(60),
        knows_common,
        swadian_face_younger_1,
        swadian_face_middle_2,
    ],
    [
        "stormguard_thunderguard",
        "Stormguard Thunderguard",
        "Stormguard Thunderguards",
        tf_guarantee_armor | tf_guarantee_boots | tf_guarantee_shield,
        0,
        0,
        fac_kingdom_12,
        [
            itm_leather_gloves_a,
            itm_pickaxe_a_v1,
            itm_tab_shield_tauria_a,
            itm_boar_spear,
            itm_broad_spear,
            itm_poulaines_d,
        ],
        def_attrib | level(10),
        wp(90),
        knows_common,
        swadian_face_young_1,
        swadian_face_middle_2,
    ],
    [
        "stormguard_stormbringer",
        "Srormguard Stormbringer",
        "Srormguard Stormbringers",
        tf_guarantee_armor
        | tf_guarantee_boots
        | tf_guarantee_shield
        | tf_guarantee_helmet,
        0,
        0,
        fac_kingdom_12,
        [
            itm_axe_crusader_a,
            itm_tab_shield_tauria_a,
            itm_tab_shield_heater_c,
            itm_two_handed_battle_axe_2,
            itm_leather_gloves_a,
            itm_leather_gloves_a_v1,
            itm_leather_boots_a,
        ],
        def_attrib | level(15),
        wp(120) | wp_two_handed(50),
        knows_common,
        swadian_face_young_1,
        swadian_face_middle_2,
    ],
    [
        "stormguard_avalanche_warrior",
        "Stormguard Avalanche Warrior",
        "Stormguard Avalanche Warriors",
        tf_guarantee_armor
        | tf_guarantee_boots
        | tf_guarantee_shield
        | tf_guarantee_helmet
        | tf_guarantee_gloves,
        0,
        0,
        fac_kingdom_12,
        [
            itm_coat_of_plates,
            itm_coat_of_plates_v1,
            itm_coat_of_plates_v2,
            itm_mail_mittens_a_v1,
            itm_mail_mittens_a,
            itm_leather_gloves_a_v1,
            itm_axe_crusader_a,
            itm_axe_crusader_b,
            itm_mace_4,
            itm_shield_heater_d,
            itm_tab_shield_tauria_a,
            itm_sword_great_a,
            itm_throwing_spears,
            itm_leather_boots_a,
        ],
        def_attrib | level(20),
        wp(150) | wp_two_handed(50),
        knows_common,
        swadian_face_young_1,
        swadian_face_middle_2,
    ],
    # Avalanche Warriors - Lightning Riders
    [
        "stormguard_lightning_rider",
        "Stormguard Lightning Rider",
        "Stormguard Lightning Riders",
        tf_guarantee_armor
        | tf_guarantee_boots
        | tf_guarantee_shield
        | tf_guarantee_helmet
        | tf_guarantee_gloves
        | tf_mounted
        | tf_guarantee_horse,
        0,
        0,
        fac_kingdom_12,
        [
            itm_coat_of_plates,
            itm_coat_of_plates_v1,
            itm_coat_of_plates,
            itm_coat_of_plates_v1,
            itm_coat_of_plates_v2,
            itm_leather_gloves_a_v1,
            itm_mail_mittens_a_v1,
            itm_mail_mittens_a,
            itm_axe_crusader_a,
            itm_axe_crusader_b,
            itm_axe_crusader_1,
            itm_tab_shield_tauria_a,
            itm_light_lance,
            itm_throwing_spears,
            itm_warhorse,
            itm_black_knight_horse_a,
            itm_mail_boots_a,
            itm_mail_boots_b,
            itm_mail_boots_c,
            itm_leather_boots_a,
        ],
        def_attrib | level(25),
        wp(180),
        knows_common | knows_riding_5,
        swadian_face_young_1,
        swadian_face_middle_2,
    ],
    # Avalanche Warriors - Tempest Sentinels - Elite Stormguard
    [
        "stormguard_tempest_sentinel",
        "Stormguard Tempest Sentinel",
        "Stormguard Tempest Sentinels",
        tf_guarantee_armor
        | tf_guarantee_boots
        | tf_guarantee_shield
        | tf_guarantee_helmet
        | tf_guarantee_gloves,
        0,
        0,
        fac_kingdom_12,
        [
            itm_coat_of_plates,
            itm_coat_of_plates_v1,
            itm_coat_of_plates_v2,
            itm_plate_gauntlets_a,
            itm_plate_gauntlets_a_v1,
            itm_one_handed_battle_axe_c,
            itm_tab_shield_tauria_b,
            itm_sword_great_a,
            itm_war_axe,
            itm_shortened_voulge,
            itm_throwing_spears,
            itm_mail_boots_a,
            itm_mail_boots_b,
            itm_mail_boots_c,
        ],
        def_attrib | level(25),
        wp(180) | wp_two_handed(50),
        knows_common | knows_power_throw_6,
        swadian_face_young_1,
        swadian_face_middle_2,
    ],
    [
        "stormguard_elite_stormguard",
        "Stormguard Elite",
        "Stormguard Elite",
        tf_guarantee_armor
        | tf_guarantee_boots
        | tf_guarantee_shield
        | tf_guarantee_helmet
        | tf_guarantee_gloves,
        0,
        0,
        fac_kingdom_12,
        [
            itm_coat_of_plates_v3,
            itm_plate_gauntlets_a_v1,
            itm_axe_crusader_1,
            itm_tab_shield_tauria_b,
            itm_bec_de_corbin_a,
            itm_heavy_throwing_axes,
            itm_throwing_spears,
            itm_plate_boots_a,
            itm_plate_boots_b,
        ],
        def_attrib | level(30),
        wp(210) | wp_polearm(50),
        knows_common | knows_power_throw_9,
        swadian_face_young_1,
        swadian_face_middle_2,
    ],
]
