from module_troops_utils import *

troops_alpine = [
    [
        "alpine_recruit",
        "Alpine Recruit",
        "Alpine Recruits",
        tf_guarantee_boots | tf_guarantee_armor,
        0,
        0,
        fac_kingdom_5,
        [
            itm_falchion_a,
            itm_hammer_a,
            itm_stones,
            itm_tab_shield_round_a,
            itm_arming_cap_a,
            itm_felt_a,
            itm_chapel_alpine_a,
            (itm_green_aketon_a, 0),
            (itm_green_aketon_a_v1, 0),
            (itm_green_aketon_a_v2, 0),
            itm_leather_gloves_a,
            itm_hose_c,
            itm_poulaines_c,
        ],
        def_attrib | level(5),
        wp(60),
        knows_common | knows_power_draw_2 | knows_ironflesh_1,
        rhodok_face_younger_1,
        rhodok_face_old_2,
    ],
    [
        "alpine_levy",
        "Alpine Levy",
        "Alpine Levy",
        tf_guarantee_boots | tf_guarantee_armor,
        0,
        0,
        fac_kingdom_5,
        [
            itm_sword_short_a,
            itm_pickaxe_a,
            itm_polearm_military_scythe_a,
            itm_infantry_shield_heraldic_a_v1,
            itm_infantry_shield_heraldic_a_v3,
            itm_arming_cap_a,
            itm_chapel_alpine_a,
            (itm_green_hauberk_a, 0),
            (itm_green_hauberk_a_v1, 0),
            (itm_green_hauberk_a_v2, 0),
            itm_leather_gloves_a,
            itm_hose_c,
            itm_poulaines_c,
        ],
        def_attrib | level(10),
        wp(90),
        knows_common | knows_power_draw_2 | knows_ironflesh_1,
        rhodok_face_young_1,
        rhodok_face_old_2,
    ],
    [
        "alpine_watchman",
        "Alpine Watchman",
        "Alpine Watchmen",
        tf_guarantee_boots | tf_guarantee_armor | tf_guarantee_helmet,
        0,
        0,
        fac_kingdom_5,
        [
            itm_hunting_crossbow,
            itm_bolts,
            itm_falchion_a,
            itm_military_pick_a,
            itm_infantry_shield_heraldic_a_v1,
            itm_infantry_shield_heraldic_a_v3,
            itm_arming_cap_a,
            itm_chapel_alpine_a,
            (itm_green_aketon_a, imod_thick),
            (itm_green_aketon_a_v1, imod_thick),
            (itm_green_aketon_a_v2, imod_thick),
            itm_leather_gloves_a,
            itm_hose_c,
            itm_poulaines_c,
        ],
        def_attrib | level(10),
        wp(90),
        knows_common | knows_power_draw_2 | knows_ironflesh_1,
        rhodok_face_young_1,
        rhodok_face_old_2,
    ],
    [
        "alpine_militia",
        "Alpine Militia",
        "Alpine Militia",
        tf_guarantee_boots | tf_guarantee_armor | tf_guarantee_helmet,
        0,
        0,
        fac_kingdom_5,
        [
            itm_hunting_crossbow,
            itm_bolts,
            itm_falchion_a,
            itm_falchion_a_v1,
            itm_falchion_a_v2,
            itm_military_pick_a,
            itm_military_pick_a_v1,
            itm_infantry_shield_heraldic_a_v1,
            itm_infantry_shield_heraldic_a_v3,
            itm_chapel_alpine_a,
            itm_chapel_alpine_a_v1,
            (itm_green_aketon_b, 0),
            (itm_green_aketon_b_v1, 0),
            (itm_green_aketon_b_v2, 0),
            itm_leather_gloves_a,
            itm_hose_c,
            itm_poulaines_c,
        ],
        def_attrib | level(15),
        wp(120),
        knows_common | knows_power_draw_2 | knows_ironflesh_3,
        rhodok_face_young_1,
        rhodok_face_old_2,
    ],
    [
        "alpine_footman",
        "Alpine Footman",
        "Alpine Footmen",
        tf_guarantee_boots | tf_guarantee_armor | tf_guarantee_helmet,
        0,
        0,
        fac_kingdom_5,
        [
            itm_sword_short_a,
            itm_sword_short_a_v1,
            itm_sword_short_a_v2,
            itm_pickaxe_a_v1,
            itm_polearm_military_scythe_a,
            itm_infantry_shield_heraldic_a_v1,
            itm_infantry_shield_heraldic_a_v3,
            itm_chapel_alpine_a,
            itm_chapel_alpine_a_v1,
            itm_sallet_a_v1,
            itm_sallet_a_v2,
            (itm_green_hauberk_a, 0),
            (itm_green_hauberk_a_v1, 0),
            (itm_green_hauberk_a_v2, 0),
            itm_leather_gloves_a,
            itm_hose_c,
            itm_poulaines_c,
        ],
        def_attrib | level(10),
        wp(90) | wp_one_handed(50),
        knows_common
        | knows_ironflesh_2
        | knows_shield_1
        | knows_power_strike_2
        | knows_athletics_1,
        rhodok_face_young_1,
        rhodok_face_old_2,
    ],
    [
        "alpine_swordsman",
        "Alpine Swordsman",
        "Alpine Swordsmen",
        tf_guarantee_armor | tf_guarantee_helmet | tf_guarantee_shield,
        0,
        0,
        fac_kingdom_5,
        [
            itm_sword_short_b,
            itm_sword_short_b_v1,
            itm_sword_short_b_v2,
            itm_infantry_shield_heraldic_a_v1,
            itm_infantry_shield_heraldic_a_v3,
            itm_chapel_alpine_a_v1,
            itm_chapel_alpine_a_v2,
            itm_sallet_a_v2,
            itm_sallet_a_v3,
            (itm_green_hauberk_a, imod_thick),
            (itm_green_hauberk_a_v1, imod_thick),
            (itm_green_hauberk_a_v2, imod_thick),
            itm_leather_gloves_a,
            itm_leather_gloves_b,
            itm_hose_c,
            itm_poulaines_c,
        ],
        def_attrib | level(15),
        wp(120) | wp_one_handed(50),
        knows_common
        | knows_ironflesh_5
        | knows_shield_1
        | knows_power_strike_5
        | knows_athletics_1,
        rhodok_face_young_1,
        rhodok_face_old_2,
    ],
    [
        "alpine_elite_swordsman",
        "Alpine Elite Swordsman",
        "Alpine Elite Swordsmen",
        tf_guarantee_boots
        | tf_guarantee_armor
        | tf_guarantee_helmet
        | tf_guarantee_shield
        | tf_guarantee_gloves,
        0,
        0,
        fac_kingdom_5,
        [
            itm_sword_great_a,
            itm_sword_a,
            itm_sword_a_v1,
            itm_infantry_shield_heraldic_a_v1,
            itm_infantry_shield_heraldic_a_v3,
            itm_chapel_alpine_a_v2,
            itm_chapel_alpine_a_v3,
            itm_sallet_a_v3,
            itm_sallet_a_v4,
            (itm_green_hauberk_a, imod_reinforced),
            (itm_green_hauberk_a_v1, imod_reinforced),
            (itm_green_hauberk_a_v2, imod_reinforced),
            itm_leather_gloves_a,
            itm_leather_gloves_b,
            itm_leather_gloves_b_v1,
            itm_mail_mittens_a,
            itm_hose_c,
            itm_poulaines_c,
            itm_plate_boots_b,
        ],
        def_attrib | level(20),
        wp(150) | wp_one_handed(50),
        knows_common
        | knows_ironflesh_8
        | knows_shield_6
        | knows_power_strike_8
        | knows_athletics_5,
        rhodok_face_young_1,
        rhodok_face_old_2,
    ],
    [
        "alpine_spearman",
        "Alpine Spearman",
        "Alpine Spearmen",
        tf_guarantee_boots | tf_guarantee_armor | tf_guarantee_helmet,
        0,
        0,
        fac_kingdom_5,
        [
            itm_sword_short_a_v2,
            itm_pickaxe_a_v1,
            itm_spear_a,
            itm_polearm_military_scythe_a,
            itm_infantry_shield_heraldic_a_v1,
            itm_infantry_shield_heraldic_a_v3,
            itm_chapel_alpine_a,
            itm_chapel_alpine_a_v1,
            itm_sallet_a_v1,
            itm_sallet_a_v2,
            (itm_green_aketon_b, 0),
            (itm_green_aketon_b_v1, 0),
            (itm_green_aketon_b_v2, 0),
            itm_leather_gloves_a,
            itm_hose_c,
            itm_poulaines_c,
        ],
        def_attrib | level(15),
        wp(120),
        knows_common
        | knows_ironflesh_2
        | knows_shield_1
        | knows_power_strike_2
        | knows_athletics_1,
        rhodok_face_young_1,
        rhodok_face_old_2,
    ],
    [
        "alpine_scout",
        "Alpine Scout",
        "Alpine Scouts",
        tf_mounted
        | tf_guarantee_boots
        | tf_guarantee_armor
        | tf_guarantee_helmet
        | tf_guarantee_shield
        | tf_guarantee_horse,
        0,
        0,
        fac_kingdom_5,
        [
            itm_sword_a,
            itm_sword_a_v1,
            itm_infantry_shield_heraldic_a,
            itm_chapel_alpine_a,
            itm_chapel_alpine_a_v1,
            itm_sallet_a_v1,
            itm_sallet_a_v2,
            (itm_green_aketon_b, imod_thick),
            (itm_green_aketon_b_v1, imod_thick),
            (itm_green_aketon_b_v2, imod_thick),
            itm_leather_gloves_a,
            itm_hose_c,
            itm_poulaines_c,
            itm_saddle_horse,
        ],
        def_attrib | level(20),
        wp(150),
        knows_common
        | knows_ironflesh_5
        | knows_riding_4
        | knows_shield_3
        | knows_power_strike_4
        | knows_athletics_3,
        rhodok_face_young_1,
        rhodok_face_old_2,
    ],
    [
        "alpine_horseman",
        "Alpine Horseman",
        "Alpine Horsemen",
        tf_mounted
        | tf_guarantee_boots
        | tf_guarantee_armor
        | tf_guarantee_helmet
        | tf_guarantee_shield
        | tf_guarantee_gloves
        | tf_guarantee_horse,
        0,
        0,
        fac_kingdom_5,
        [
            itm_sword_a,
            itm_sword_a_v1,
            itm_sword_knight_a,
            itm_lance_a,
            itm_infantry_shield_heraldic_a,
            itm_chapel_alpine_a_v1,
            itm_chapel_alpine_a_v2,
            itm_sallet_a_v2,
            itm_sallet_a_v3,
            (itm_green_aketon_b, imod_reinforced),
            (itm_green_aketon_b_v1, imod_reinforced),
            (itm_green_aketon_b_v2, imod_reinforced),
            itm_leather_gloves_a,
            itm_hose_c,
            itm_poulaines_c,
            itm_hunter,
        ],
        def_attrib | level(25),
        wp(180),
        knows_common
        | knows_ironflesh_6
        | knows_shield_7
        | knows_power_strike_6
        | knows_riding_7,
        rhodok_face_young_1,
        rhodok_face_old_2,
    ],
    [
        "alpine_trained_spearman",
        "Alpine Trained Spearman",
        "Alpine Trained Spearmen",
        tf_guarantee_boots | tf_guarantee_armor | tf_guarantee_shield,
        0,
        0,
        fac_kingdom_5,
        [
            itm_sword_a_v2,
            itm_sword_a_v3,
            itm_pickaxe_a_v1,
            itm_mace_a,
            itm_military_pick_a,
            itm_spear_a,
            itm_polearm_military_scythe_a,
            itm_polearm_light_halberd_a,
            itm_infantry_shield_heraldic_a_v1,
            itm_infantry_shield_heraldic_a_v3,
            itm_chapel_alpine_a_v1,
            itm_chapel_alpine_a_v2,
            itm_sallet_a_v2,
            itm_sallet_a_v3,
            (itm_green_churburg_a, 0),
            (itm_green_churburg_a, imod_thick),
            (itm_green_churburg_a, imod_reinforced),
            itm_leather_gloves_a,
            itm_leather_gloves_b,
            itm_leather_gloves_b_v1,
            itm_hose_c,
            itm_poulaines_c,
        ],
        def_attrib | level(20),
        wp(150) | wp_polearm(50),
        knows_common
        | knows_ironflesh_3
        | knows_shield_2
        | knows_power_strike_2
        | knows_athletics_2,
        rhodok_face_young_1,
        rhodok_face_older_2,
    ],
    [
        "alpine_veteran_spearman",
        "Alpine Veteran Spearman",
        "Alpine Veteran Spearmen",
        tf_guarantee_boots
        | tf_guarantee_armor
        | tf_guarantee_helmet
        | tf_guarantee_shield,
        0,
        0,
        fac_kingdom_5,
        [
            itm_sword_a_v3,
            itm_military_pick_a_v1,
            itm_military_pick_a_v2,
            itm_spear_a,
            itm_polearm_military_scythe_a,
            itm_polearm_light_halberd_a,
            itm_infantry_shield_heraldic_a_v1,
            itm_infantry_shield_heraldic_a_v3,
            itm_chapel_alpine_a_v1,
            itm_chapel_alpine_a_v2,
            itm_sallet_a_v2,
            itm_sallet_a_v3,
            (itm_green_churburg_b, 0),
            (itm_green_churburg_b, imod_reinforced),
            itm_leather_gloves_b,
            itm_leather_gloves_b_v1,
            itm_plate_gauntlets_a,
            itm_plate_gauntlets_a_v1,
            itm_hose_c,
            itm_poulaines_c,
        ],
        def_attrib | level(25),
        wp(180) | wp_polearm(50),
        knows_common
        | knows_ironflesh_5
        | knows_shield_3
        | knows_power_strike_4
        | knows_athletics_3,
        rhodok_face_young_1,
        rhodok_face_older_2,
    ],
    [
        "alpine_man_at_arms",
        "Alpine Man-at-Arms",
        "Alpine Men-at-Arms",
        tf_guarantee_boots
        | tf_guarantee_armor
        | tf_guarantee_helmet
        | tf_guarantee_shield
        | tf_guarantee_gloves,
        0,
        0,
        fac_kingdom_5,
        [
            itm_military_pick_a_v1,
            itm_military_pick_a_v2,
            itm_polehammer_a,
            itm_poleaxe_a,
            itm_infantry_shield_heraldic_a_v4,
            itm_chapel_alpine_a_v3,
            itm_sallet_a_v4,
            itm_sallet_b_v4,
            itm_sallet_c_v4,
            (itm_green_churburg_c, 0),
            (itm_green_churburg_c, imod_reinforced),
            itm_plate_gauntlets_a,
            itm_plate_gauntlets_a_v1,
            itm_plate_gauntlets_a_v2,
            itm_plate_boots_a,
            itm_plate_boots_b,
        ],
        def_attrib | level(30),
        wp(210) | wp_polearm(50),
        knows_common
        | knows_ironflesh_9
        | knows_shield_5
        | knows_power_strike_9
        | knows_athletics_6,
        rhodok_face_middle_1,
        rhodok_face_older_2,
    ],
    [
        "alpine_crossbowman",
        "Alpine Crossbowman",
        "Alpine Crossbowmen",
        tf_guarantee_boots
        | tf_guarantee_armor
        | tf_guarantee_helmet
        | tf_guarantee_ranged,
        0,
        0,
        fac_kingdom_5,
        [
            itm_crossbow,
            itm_bolts,
            itm_sword_a,
            itm_pickaxe_a_v1,
            itm_falchion_b,
            itm_falchion_b_v1,
            itm_infantry_shield_heraldic_a_v1,
            itm_infantry_shield_heraldic_a_v3,
            itm_chapel_alpine_a_v2,
            (itm_green_aketon_b, imod_thick),
            (itm_green_aketon_b_v1, imod_thick),
            (itm_green_aketon_b_v2, imod_thick),
            itm_leather_gloves_a,
            itm_hose_c,
            itm_poulaines_c,
        ],
        def_attrib | level(15),
        wp(120) | wp_crossbow(50),
        knows_common
        | knows_ironflesh_2
        | knows_shield_1
        | knows_power_strike_1
        | knows_athletics_2,
        rhodok_face_young_1,
        rhodok_face_older_2,
    ],
    [
        "alpine_trained_crossbowman",
        "Alpine Trained Crossbowman",
        "Alpine Trained Crossbowmen",
        tf_guarantee_boots
        | tf_guarantee_armor
        | tf_guarantee_helmet
        | tf_guarantee_ranged
        | tf_guarantee_shield,
        0,
        0,
        fac_kingdom_5,
        [
            itm_crossbow,
            itm_bolts,
            itm_sword_a,
            itm_pickaxe_a_v1,
            itm_falchion_b,
            itm_falchion_b_v1,
            itm_infantry_shield_heraldic_a_v1,
            itm_infantry_shield_heraldic_a_v3,
            itm_chapel_alpine_a_v2,
            (itm_green_aketon_b, imod_reinforced),
            (itm_green_aketon_b_v1, imod_reinforced),
            (itm_green_aketon_b_v2, imod_reinforced),
            itm_leather_gloves_b,
            itm_hose_c,
            itm_poulaines_c,
        ],
        def_attrib | level(20),
        wp(150) | wp_crossbow(50),
        knows_common
        | knows_ironflesh_1
        | knows_shield_2
        | knows_power_strike_2
        | knows_athletics_3,
        rhodok_face_young_1,
        rhodok_face_older_2,
    ],
    [
        "alpine_veteran_crossbowman",
        "Alpine Veteran Crossbowman",
        "Alpine Veteran Crossbowmen",
        tf_guarantee_boots
        | tf_guarantee_armor
        | tf_guarantee_helmet
        | tf_guarantee_ranged
        | tf_guarantee_shield,
        0,
        0,
        fac_kingdom_5,
        [
            itm_heavy_crossbow,
            itm_bolts,
            itm_sword_a,
            itm_pickaxe_a_v1,
            itm_falchion_c,
            itm_falchion_c_v1,
            itm_infantry_shield_heraldic_a_v1,
            itm_infantry_shield_heraldic_a_v3,
            itm_chapel_alpine_a_v3,
            (itm_green_hauberk_a, 0),
            (itm_green_hauberk_a_v1, 0),
            (itm_green_hauberk_a_v2, 0),
            itm_leather_gloves_b,
            itm_hose_c,
            itm_poulaines_c,
        ],
        def_attrib | level(25),
        wp(180) | wp_crossbow(50),
        knows_common
        | knows_ironflesh_2
        | knows_shield_3
        | knows_power_strike_3
        | knows_athletics_4,
        rhodok_face_middle_1,
        rhodok_face_older_2,
    ],
    [
        "alpine_sharpshooter",
        "Alpine Sharpshooter",
        "Alpine Sharpshooters",
        tf_guarantee_boots
        | tf_guarantee_armor
        | tf_guarantee_helmet
        | tf_guarantee_ranged
        | tf_guarantee_shield,
        0,
        0,
        fac_kingdom_5,
        [
            itm_sniper_crossbow,
            itm_piercing_bolts,
            itm_sword_a_v1,
            itm_pickaxe_a_v1,
            itm_falchion_c,
            itm_falchion_c_v1,
            itm_infantry_shield_heraldic_a_v1,
            itm_infantry_shield_heraldic_a_v3,
            itm_chapel_alpine_a_v3,
            (itm_green_hauberk_a, imod_reinforced),
            (itm_green_hauberk_a_v1, imod_reinforced),
            (itm_green_hauberk_a_v2, imod_reinforced),
            itm_leather_gloves_b,
            itm_mail_mittens_a,
            itm_plate_boots_b,
            itm_hose_c,
            itm_poulaines_c,
        ],
        def_attrib | level(30),
        wp(210) | wp_crossbow(50),
        knows_common
        | knows_ironflesh_3
        | knows_shield_4
        | knows_power_strike_4
        | knows_athletics_6,
        rhodok_face_middle_1,
        rhodok_face_older_2,
    ],
    [
        "rhodok_messenger",
        "Rhodok Messenger",
        "Rhodok Messengers",
        tf_mounted
        | tf_guarantee_boots
        | tf_guarantee_armor
        | tf_guarantee_gloves
        | tf_guarantee_horse
        | tf_guarantee_ranged,
        0,
        0,
        fac_kingdom_5,
        [
            itm_sword_short_a_v1,
            itm_regular_leather_jerkin_a,
            itm_courser,
            itm_leather_gloves_a,
            itm_short_bow,
            itm_arrows,
        ],
        def_attrib | agi_21 | level(25),
        wp(130),
        knows_common | knows_riding_7 | knows_horse_archery_5 | knows_power_draw_5,
        rhodok_face_middle_1,
        rhodok_face_older_2,
    ],
    [
        "rhodok_deserter",
        "Rhodok Deserter",
        "Rhodok Deserters",
        tf_guarantee_ranged | tf_guarantee_boots | tf_guarantee_armor,
        0,
        0,
        fac_deserters,
        [
            itm_arrows,
            itm_spiked_mace,
            itm_heavy_axe_a,
            itm_falchion_a,
            itm_short_bow,
            itm_short_bow,
            itm_hunting_bow,
            itm_javelin,
            itm_javelin,
            itm_steppe_cap,
            itm_leather_vest_regular_shirt_a,
            itm_regular_nomad_vest_a,
        ],
        def_attrib | str_10 | level(14),
        wp(80),
        knows_ironflesh_1 | knows_power_draw_1,
        rhodok_face_middle_1,
        rhodok_face_older_2,
    ],
    [
        "rhodok_prison_guard",
        "Prison Guard",
        "Prison Guards",
        tf_guarantee_shield
        | tf_guarantee_boots
        | tf_guarantee_armor
        | tf_guarantee_helmet,
        0,
        0,
        fac_kingdom_5,
        [
            itm_ashwood_pike,
            itm_battle_fork,
            itm_battle_axe,
            itm_fighting_axe,
            itm_tab_shield_pavise_b,
            itm_sallet_b,
            itm_leather_gloves_a,
        ],
        def_attrib | level(24),
        wp(130),
        knows_athletics_3 | knows_shield_2 | knows_ironflesh_3,
        rhodok_face_middle_1,
        rhodok_face_older_2,
    ],
    [
        "rhodok_castle_guard",
        "Castle Guard",
        "Castle Guards",
        tf_guarantee_shield
        | tf_guarantee_boots
        | tf_guarantee_armor
        | tf_guarantee_helmet,
        0,
        0,
        fac_kingdom_5,
        [
            itm_ashwood_pike,
            itm_battle_fork,
            itm_battle_axe,
            itm_fighting_axe,
            itm_tab_shield_pavise_c,
            itm_sallet_b,
            itm_leather_gloves_a,
        ],
        def_attrib | level(24),
        wp(130),
        knows_athletics_3 | knows_shield_2 | knows_ironflesh_3,
        rhodok_face_middle_1,
        rhodok_face_older_2,
    ],
]
