from module_troops_utils import *

troops_silver_rose = [
    # SILVER ROSE UNITS BEGIN
    [
        "silver_rose_recruit",
        "Silver Rose Recruit",
        "Silver Rose Recruits",
        tf_guarantee_armor | tf_guarantee_boots,
        0,
        0,
        fac_kingdom_1,
        [
            itm_hammer_a,
            itm_hatchet_a,
            itm_hatchet_a_v1,
            itm_pickaxe_a,
            itm_falchion_a,
            itm_falchion_b,
            itm_tab_shield_tauria_a,
            (itm_red_aketon_a, 0),
            (itm_red_aketon_a, imod_thick),
            (itm_red_aketon_a_v1, 0),
            (itm_red_aketon_a_v1, imod_thick),
            (itm_red_aketon_a_v2, 0),
            (itm_red_aketon_a_v2, imod_thick),
            itm_arming_cap_a,
            itm_felt_a,
            itm_felt_a_v1,
            itm_felt_a_v2,
            itm_felt_b,
            itm_felt_b_v1,
            itm_leather_gloves_a_v1,
            itm_hose_b,
            itm_poulaines_b,
        ],
        def_attrib | level(5),
        wp(60),
        knows_common,
        swadian_face_younger_1,
        swadian_face_middle_2,
    ],
    [
        "silver_rose_city_watch",
        "Silver Rose City Watch",
        "Silver Rose City Watch",
        tf_guarantee_armor | tf_guarantee_boots | tf_guarantee_helmet,
        0,
        0,
        fac_kingdom_1,
        [
            itm_falchion_a,
            itm_falchion_a_v1,
            itm_falchion_a_v2,
            itm_spear_a,
            itm_tab_shield_tauria_a,
            itm_cervelliere_a,
            itm_cervelliere_b,
            (itm_red_aketon_a, imod_hardened),
            (itm_red_aketon_a_v1, imod_thick),
            (itm_red_aketon_a_v2, imod_hardened),
            itm_leather_gloves_a_v1,
            itm_hose_b,
            itm_poulaines_b,
        ],
        def_attrib | level(10),
        wp(90),
        knows_common,
        swadian_face_younger_1,
        swadian_face_middle_2,
    ],
    [
        "silver_rose_tower_guard",
        "Silver Rose Tower Guard",
        "Silver Rose Tower Guards",
        tf_guarantee_armor | tf_guarantee_boots | tf_guarantee_helmet,
        0,
        0,
        fac_kingdom_1,
        [
            itm_sword_short_a,
            itm_sword_short_a_v1,
            itm_sword_short_a_v2,
            itm_spear_a_v1,
            itm_tab_shield_tauria_a,
            itm_cervelliere_a_v1,
            itm_cervelliere_b_v1,
            (itm_red_aketon_a, imod_hardened),
            (itm_red_aketon_a_v1, imod_hardened),
            (itm_red_aketon_a_v2, imod_hardened),
            (itm_red_aketon_b, imod_thick),
            (itm_red_aketon_b_v1, imod_thick),
            (itm_red_aketon_b_v2, imod_thick),
            itm_leather_gloves_a_v1,
            itm_hose_b,
            itm_poulaines_b,
        ],
        def_attrib | level(15),
        wp(120),
        knows_common,
        swadian_face_younger_1,
        swadian_face_middle_2,
    ],
    [
        "silver_rose_wall_guard",
        "Silver Rose Wall Guard",
        "Silver Rose Wall Guards",
        tf_guarantee_armor | tf_guarantee_boots | tf_guarantee_helmet | tf_guarantee_ranged,
        0,
        0,
        fac_kingdom_1,
        [
            itm_mace_a,
            itm_mace_a_v1,
            itm_falchion_a,
            itm_falchion_b,
            itm_long_bow,
            itm_arrows,
            itm_arming_cap_a,
            itm_felt_a,
            itm_felt_a_v1,
            itm_felt_a_v2,
            itm_felt_b,
            itm_felt_b_v1,
            itm_red_aketon_a,
            itm_red_aketon_a_v1,
            itm_red_aketon_a_v2,
            itm_leather_gloves_a_v1,
            itm_hose_b,
            itm_poulaines_b,
        ],
        def_attrib | level(15),
        wp(120),
        knows_common | knows_power_draw_1,
        swadian_face_younger_1,
        swadian_face_middle_2,
    ],
    [
        "silver_rose_levy",
        "Silver Rose Levy",
        "Silver Rose Levy",
        tf_guarantee_armor | tf_guarantee_boots | tf_guarantee_helmet,
        0,
        0,
        fac_kingdom_1,
        [
            itm_sword_short_a,
            itm_sword_short_a_v1,
            itm_sword_short_a_v2,
            itm_military_pick_a,
            itm_military_pick_a_v1,
            itm_military_pick_a_v2,
            itm_polearm_military_scythe_a,
            itm_tab_shield_tauria_a,
            itm_arming_cap_a,
            itm_cervelliere_a,
            itm_cervelliere_b,
            (itm_red_aketon_a, imod_thick),
            (itm_red_aketon_a_v1, imod_thick),
            (itm_red_aketon_a_v2, imod_thick),
            itm_leather_gloves_a_v1,
            itm_hose_b,
            itm_poulaines_b,
        ],
        def_attrib | level(10),
        wp(90),
        knows_common,
        swadian_face_younger_1,
        swadian_face_middle_2,
    ],
    [
        "silver_rose_scout",
        "Silver Rose Scout",
        "Silver Rose Scouts",
        tf_mounted
        | tf_guarantee_armor
        | tf_guarantee_boots
        | tf_guarantee_helmet
        | tf_guarantee_horse
        | tf_guarantee_shield,
        0,
        0,
        fac_kingdom_1,
        [
            itm_sword_short_a,
            itm_mace_a,
            itm_mace_a_v1,
            itm_tab_shield_tauria_a,
            itm_cervelliere_a_v1,
            itm_cervelliere_b_v1,
            (itm_red_aketon_a, imod_hardened),
            (itm_red_aketon_a_v1, imod_hardened),
            (itm_red_aketon_a_v2, imod_hardened),
            itm_leather_gloves_a,
            itm_hose_b,
            itm_poulaines_b,
            itm_hunter,
        ],
        def_attrib | level(15),
        wp(120),
        knows_common | knows_riding_3,
        swadian_face_young_1,
        swadian_face_old_2,
    ],
    [
        "silver_rose_milita",
        "Silver Rose Militia",
        "Silver Rose Militia",
        tf_guarantee_armor
        | tf_guarantee_boots
        | tf_guarantee_shield
        | tf_guarantee_helmet,
        0,
        0,
        fac_kingdom_1,
        [
            itm_sword_short_a,
            itm_sword_short_a_v1,
            itm_sword_short_a_v2,
            itm_spear_a,
            itm_polearm_military_scythe_a,
            itm_polearm_glaive_a,
            itm_tab_shield_tauria_a,
            itm_cervelliere_a_v1,
            itm_cervelliere_b_v1,
            itm_flat_top_a_v1,
            itm_flat_top_b_v1,
            (itm_red_aketon_a, imod_hardened),
            (itm_red_aketon_a_v1, imod_hardened),
            (itm_red_aketon_a_v2, imod_hardened),
            itm_leather_gloves_a_v1,
            itm_hose_b,
            itm_poulaines_b,
        ],
        def_attrib | level(15),
        wp(120),
        knows_common,
        swadian_face_young_1,
        swadian_face_old_2,
    ],
    [
        "silver_rose_footman",
        "Silver Rose Footman",
        "Silver Rose Footmen",
        tf_guarantee_armor
        | tf_guarantee_boots
        | tf_guarantee_shield
        | tf_guarantee_helmet,
        0,
        0,
        fac_kingdom_1,
        [
            itm_sword_short_b,
            itm_sword_short_b_v1,
            itm_sword_short_b_v2,
            itm_polearm_light_voulge_a,
            itm_polearm_light_voulge_b,
            itm_oval_shield_heraldic_a,
            itm_eyeslot_kettlehat_a_v2,
            itm_chapel_a_v2,
            itm_chapel_b_v2,
            itm_sallet_a_v2,
            (itm_red_churburg_a, 0),
            (itm_red_churburg_a, imod_thick),
            (itm_red_churburg_a, imod_reinforced),
            itm_leather_gloves_a,
            itm_leather_gloves_a_v1,
            itm_hose_d,
            itm_poulaines_d,
        ],
        def_attrib | level(15),
        wp_melee(120),
        knows_common
        | knows_ironflesh_3
        | knows_shield_2
        | knows_athletics_2
        | knows_power_strike_2,
        swadian_face_young_1,
        swadian_face_old_2,
    ],
    [
        "silver_rose_hacker",
        "Silver Rose Hacker",
        "Silver Rose Hackers",
        tf_guarantee_shield
        | tf_guarantee_boots
        | tf_guarantee_armor
        | tf_guarantee_helmet,
        0,
        0,
        fac_kingdom_1,
        [
            itm_sword_great_a,
            itm_sword_great_a_v1,
            itm_sallet_a_v2,
            itm_sallet_a_v3,
            itm_sallet_b_v2,
            itm_sallet_b_v3,
            itm_eyeslot_kettlehat_a_v2,
            (itm_red_brigandine_b, 0),
            (itm_red_brigandine_b, imod_reinforced),
            (itm_red_brigandine_b_v1, 0),
            (itm_red_brigandine_b_v1, imod_reinforced),
            itm_plate_gauntlets_a_v1,
            itm_leather_gloves_a_v1,
            itm_plate_boots_b,
        ],
        def_attrib | str_18 | agi_20 | level(20),
        wp_melee(150) | wp_two_handed(50),
        knows_common | knows_ironflesh_5 | knows_power_strike_4 | knows_athletics_5,
        swadian_face_middle_1,
        swadian_face_old_2,
    ],
    [
        "silver_rose_infantry",
        "Silver Rose Infantry",
        "Silver Rose Infantry",
        tf_guarantee_shield
        | tf_guarantee_armor
        | tf_guarantee_boots
        | tf_guarantee_helmet,
        0,
        0,
        fac_kingdom_1,
        [
            itm_sword_a,
            itm_sword_a_v1,
            itm_sword_a_v2,
            itm_sword_a_v3,
            itm_polearm_light_halberd_a,
            itm_polearm_light_voulge_a,
            itm_polearm_light_voulge_b,
            itm_oval_shield_heraldic_a,
            itm_sallet_a_v3,
            itm_sallet_b_v3,
            itm_sallet_c_v3,
            itm_flat_top_a_v3,
            itm_flat_top_b_v3,
            (itm_red_brigandine_c, 0),
            (itm_red_brigandine_c, imod_thick),
            (itm_red_brigandine_c_v1, 0),
            (itm_red_brigandine_c_v1, imod_thick),
            itm_plate_gauntlets_a_v1,
            itm_leather_gloves_a_v1,
            itm_plate_boots_b,
        ],
        def_attrib | level(20),
        wp_melee(150),
        knows_common
        | knows_ironflesh_4
        | knows_power_strike_3
        | knows_shield_3
        | knows_athletics_3,
        swadian_face_middle_1,
        swadian_face_old_2,
    ],
    [
        "silver_rose_sergeant",
        "Silver Rose Sergeant",
        "Silver Rose Sergeants",
        tf_mounted
        | tf_guarantee_shield
        | tf_guarantee_armor
        | tf_guarantee_boots
        | tf_guarantee_helmet,
        0,
        0,
        fac_kingdom_1,
        [
            itm_sword_knight_a,
            itm_sword_knight_a_v1,
            itm_sword_knight_a_v2,
            itm_polearm_light_halberd_a,
            itm_polearm_light_voulge_a,
            itm_polearm_light_voulge_b,
            itm_oval_shield_heraldic_a,
            itm_sallet_a_v4,
            itm_sallet_b_v4,
            itm_sallet_c_v4,
            itm_flat_top_a_v4,
            itm_flat_top_b_v4,
            (itm_red_brigandine_d, 0),
            (itm_red_brigandine_d, imod_thick),
            (itm_red_brigandine_d_v1, 0),
            (itm_red_brigandine_d_v1, imod_thick),
            itm_leather_gloves_a_v1,
            itm_plate_gauntlets_a,
            itm_plate_gauntlets_a_v1,
            itm_plate_boots_a,
            itm_plate_boots_b,
        ],
        def_attrib | str_30 | agi_20 | level(25),
        wp_melee(180) | wp_one_handed(50) | wp_polearm(50),
        knows_common
        | knows_shield_4
        | knows_ironflesh_4
        | knows_power_strike_4
        | knows_athletics_4,
        swadian_face_middle_1,
        swadian_face_older_2,
    ],
    [
        "silver_rose_crossbowman",
        "Silver Rose Crossbowman",
        "Silver Rose Crossbowmen",
        tf_guarantee_ranged
        | tf_guarantee_armor
        | tf_guarantee_boots
        | tf_guarantee_helmet,
        0,
        0,
        fac_kingdom_1,
        [
            itm_bolts,
            itm_light_crossbow,
            itm_hunting_crossbow,
            itm_falchion_c,
            itm_falchion_c_v1,
            itm_falchion_c_v2,
            itm_military_pick_a,
            itm_military_pick_a_v1,
            itm_military_pick_a_v2,
            itm_tab_shield_tauria_a,
            itm_chapel_a_v1,
            itm_chapel_b_v1,
            itm_chapel_c_v1,
            itm_arming_cap_a,
            (itm_red_churburg_a, 0),
            (itm_red_churburg_a, imod_thick),
            (itm_red_churburg_a, imod_reinforced),
            itm_leather_gloves_a_v1,
            itm_hose_d,
            itm_poulaines_d,
        ],
        def_attrib | level(15),
        wp(120),
        knows_common | knows_riding_2 | knows_ironflesh_1,
        swadian_face_young_1,
        swadian_face_middle_2,
    ],
    [
        "silver_rose_trained_crossbowman",
        "Silver Rose Trained Crossbowman",
        "Silver Rose Trained Crossbowmen",
        tf_guarantee_ranged
        | tf_guarantee_armor
        | tf_guarantee_boots
        | tf_guarantee_helmet,
        0,
        0,
        fac_kingdom_1,
        [
            itm_bolts,
            itm_crossbow,
            itm_light_crossbow,
            itm_falchion_c,
            itm_falchion_c_v1,
            itm_falchion_c_v2,
            itm_military_pick_a,
            itm_military_pick_a_v1,
            itm_military_pick_a_v2,
            itm_tab_shield_tauria_a,
            itm_chapel_a_v2,
            itm_chapel_b_v2,
            itm_chapel_c_v2,
            itm_eyeslot_kettlehat_a_v2,
            (itm_red_churburg_b, 0),
            (itm_red_churburg_b, imod_thick),
            (itm_red_churburg_b, imod_reinforced),
            itm_leather_gloves_a_v1,
            itm_hose_d,
            itm_poulaines_d,
        ],
        def_attrib | level(20),
        wp(150) | wp_crossbow(50),
        knows_common | knows_riding_2 | knows_ironflesh_1 | knows_athletics_1,
        swadian_face_young_1,
        swadian_face_old_2,
    ],
    [
        "silver_rose_sharpshooter",
        "Silver Rose Sharpshooter",
        "Silver Rose Sharpshooters",
        tf_guarantee_ranged
        | tf_guarantee_armor
        | tf_guarantee_boots
        | tf_guarantee_helmet,
        0,
        0,
        fac_kingdom_1,
        [
            itm_bolts,
            itm_crossbow,
            itm_crossbow,
            itm_heavy_crossbow,
            itm_falchion_c,
            itm_falchion_c_v1,
            itm_falchion_c_v2,
            itm_military_pick_a,
            itm_military_pick_a_v1,
            itm_military_pick_a_v2,
            itm_tab_shield_tauria_a,
            itm_chapel_a_v3,
            itm_chapel_b_v3,
            itm_chapel_c_v3,
            itm_eyeslot_kettlehat_a_v3,
            (itm_red_churburg_c, 0),
            (itm_red_churburg_c, imod_reinforced),
            itm_leather_gloves_a_v1,
            itm_hose_d,
            itm_poulaines_d,
        ],
        def_attrib | level(25),
        wp(180) | wp_crossbow(50),
        knows_common
        | knows_power_draw_3
        | knows_ironflesh_1
        | knows_power_strike_1
        | knows_athletics_2,
        swadian_face_middle_1,
        swadian_face_older_2,
    ],
    [
        "silver_rose_squire",
        "Silver Rose Squire",
        "Silver Rose Squires",
        tf_guarantee_armor | tf_guarantee_boots | tf_guarantee_helmet | tf_guarantee_shield | tf_guarantee_gloves,
        0,
        0,
        fac_kingdom_1,
        [
            itm_sword_knight_a,
            itm_sword_knight_a_v1,
            itm_sword_knight_a_v2,
            itm_tab_shield_tauria_a,
            itm_sallet_a_v4,
            itm_flat_top_a_v4,
            itm_flat_top_b_v4,
            itm_eyeslot_kettlehat_a_v3,
            itm_chapel_b_v2,
            (itm_red_pourpoint_a, 0),
            (itm_red_pourpoint_a, imod_sturdy),
            (itm_red_pourpoint_a, imod_thick),
            itm_leather_gloves_a_v1,
            itm_hose_d,
            itm_poulaines_d,
        ],
        def_attrib | level(20),
        wp_melee(150),
        knows_common
        | knows_riding_2
        | knows_ironflesh_2
        | knows_power_strike_2
        | knows_shield_2
        | knows_athletics_2,
        swadian_face_middle_1,
        swadian_face_old_2,
    ],
    [
        "silver_rose_horseman",
        "Silver Rose Horseman",
        "Silver Rose Horsemen",
        tf_mounted
        | tf_guarantee_armor
        | tf_guarantee_helmet
        | tf_guarantee_boots
        | tf_guarantee_horse
        | tf_guarantee_shield,
        0,
        0,
        fac_kingdom_1,
        [
            itm_sword_knight_a,
            itm_sword_knight_a_v1,
            itm_sword_knight_a_v2,
            itm_lance_a,
            itm_tab_shield_tauria_a,
            itm_sallet_a_v4,
            itm_sallet_b_v4,
            itm_flat_top_a_v4,
            itm_flat_top_b_v4,
            itm_eyeslot_kettlehat_a_v3,
            (itm_red_hauberk_a, 0),
            (itm_red_hauberk_a, imod_thick),
            (itm_red_hauberk_a, imod_hardened),
            itm_leather_gloves_a_v1,
            itm_hose_d,
            itm_poulaines_d,
            itm_hunter,
            itm_hunter,
            itm_hunter_b,
            itm_hunter_c,
        ],
        def_attrib | level(25),
        wp_melee(180),
        knows_common
        | knows_riding_3
        | knows_ironflesh_4
        | knows_power_strike_4
        | knows_shield_3
        | knows_athletics_3,
        swadian_face_middle_1,
        swadian_face_old_2,
    ],
    [
        "silver_rose_man_at_arms",
        "Silver Rose Man at Arms",
        "Silver Rose Men at Arms",
        tf_mounted
        | tf_guarantee_armor
        | tf_guarantee_helmet
        | tf_guarantee_boots
        | tf_guarantee_horse
        | tf_guarantee_shield,
        0,
        0,
        fac_kingdom_1,
        [
            itm_sword_knight_a,
            itm_sword_knight_a_v1,
            itm_sword_knight_a_v2,
            itm_lance_a,
            itm_tab_shield_tauria_a,
            itm_sallet_a_v4,
            itm_sallet_b_v4,
            itm_sallet_c_v4,
            (itm_red_churburg_b, 0),
            (itm_red_churburg_b, imod_thick),
            (itm_red_churburg_b, imod_hardened),
            (itm_red_churburg_c, 0),
            (itm_red_churburg_c, imod_reinforced),
            itm_leather_gloves_a_v1,
            itm_plate_boots_b,
            itm_hunter,
            itm_hunter_b,
            itm_hunter_c,
            itm_hunter_d,
        ],
        def_attrib | level(30),
        wp_melee(210),
        knows_common
        | knows_riding_4
        | knows_ironflesh_5
        | knows_shield_2
        | knows_power_strike_5,
        swadian_face_young_1,
        swadian_face_old_2,
    ],
    [
        "silver_rose_knight",
        "Silver Rose Knight",
        "Silver Rose Knights",
        tf_mounted
        | tf_guarantee_armor
        | tf_guarantee_gloves
        | tf_guarantee_helmet
        | tf_guarantee_boots
        | tf_guarantee_horse
        | tf_guarantee_shield,
        0,
        0,
        fac_kingdom_1,
        [
            itm_sword_knight_a,
            itm_sword_knight_a_v1,
            itm_sword_knight_a_v2,
            itm_lance_a,
            itm_oval_shield_heraldic_a,
            itm_sallet_b_v3,
            itm_sallet_b_v4,
            itm_sallet_b_v5,
            itm_sallet_c_v3,
            itm_sallet_c_v4,
            itm_sallet_c_v5,
            (itm_red_churburg_mail_a, 0),
            (itm_red_churburg_mail_b, 0),
            (itm_red_churburg_mail_c, 0),
            itm_plate_gauntlets_a,
            itm_plate_gauntlets_a_v1,
            itm_plate_boots_a,
            itm_plate_boots_b,
            itm_silver_rose_heavy_horse_a,
        ],
        def_attrib | level(35),
        wp_melee(240),
        knows_common
        | knows_riding_5
        | knows_shield_5
        | knows_ironflesh_8
        | knows_power_strike_8,
        swadian_face_middle_1,
        swadian_face_older_2,
    ],
    [
        "swadian_messenger",
        "Swadian Messenger",
        "Swadian Messengers",
        tf_mounted
        | tf_guarantee_boots
        | tf_guarantee_armor
        | tf_guarantee_gloves
        | tf_guarantee_horse
        | tf_guarantee_ranged,
        0,
        0,
        fac_kingdom_1,
        [
            itm_sword_medieval_a,
            itm_leather_jerkin,
            itm_courser,
            itm_leather_gloves_a,
            itm_light_crossbow,
            itm_bolts,
        ],
        str_7 | agi_21 | int_4 | cha_4 | level(25),
        wp(130),
        knows_common | knows_riding_7 | knows_horse_archery_5,
        swadian_face_young_1,
        swadian_face_old_2,
    ],
    [
        "swadian_deserter",
        "Swadian Deserter",
        "Swadian Deserters",
        tf_guarantee_ranged | tf_guarantee_boots | tf_guarantee_armor,
        0,
        0,
        fac_deserters,
        [
            itm_bolts,
            itm_light_crossbow,
            itm_hunting_crossbow,
            itm_dagger,
            itm_club,
            itm_voulge,
            itm_wooden_shield,
            itm_leather_jerkin,
            itm_padded_cloth,
            itm_padded_coif_a,
            itm_eyeslot_kettlehat_a_v1,
        ],
        def_attrib | level(14),
        wp(80),
        knows_common | knows_riding_2 | knows_ironflesh_1,
        swadian_face_young_1,
        swadian_face_old_2,
    ],
    [
        "swadian_prison_guard",
        "Prison Guard",
        "Prison Guards",
        tf_guarantee_shield
        | tf_guarantee_boots
        | tf_guarantee_armor
        | tf_guarantee_helmet,
        0,
        0,
        fac_kingdom_1,
        [
            itm_awlpike,
            itm_pike,
            itm_sword_great_a,
            itm_morningstar,
            itm_sword_medieval_b,
            itm_tab_shield_heater_c,
            itm_coat_of_plates,
            itm_full_plate_armor_a,
            itm_sallet_c,
            itm_sallet_a_v5,
            itm_sallet_a,
            itm_sallet_c,
            itm_leather_gloves_a,
        ],
        def_attrib | level(25),
        wp(130),
        knows_common | knows_shield_3 | knows_ironflesh_3 | knows_power_strike_3,
        swadian_face_young_1,
        swadian_face_old_2,
    ],
    [
        "swadian_castle_guard",
        "Castle Guard",
        "Castle Guards",
        tf_guarantee_shield
        | tf_guarantee_boots
        | tf_guarantee_armor
        | tf_guarantee_helmet,
        0,
        0,
        fac_kingdom_1,
        [
            itm_awlpike,
            itm_pike,
            itm_sword_great_a,
            itm_morningstar,
            itm_sword_medieval_b,
            itm_tab_shield_heater_c,
            itm_tab_shield_heater_d,
            itm_coat_of_plates,
            itm_full_plate_armor_a,
            itm_sallet_c,
            itm_sallet_a_v5,
            itm_sallet_a,
            itm_sallet_c,
            itm_leather_gloves_a,
        ],
        def_attrib | level(25),
        wp(130),
        knows_common | knows_shield_3 | knows_ironflesh_3 | knows_power_strike_3,
        swadian_face_young_1,
        swadian_face_old_2,
    ],
    # SILVER ROSE UNITS END
]
