from module_troops_utils import *

troops_tavern = [
    # Ransom brokers.
    [
        "ransom_broker_1",
        "Ransom_Broker",
        "Ransom_Broker",
        tf_hero | tf_randomize_face,
        0,
        reserved,
        fac_commoners,
        [itm_leather_boots_a, itm_leather_vest],
        def_attrib | level(5),
        wp(20),
        knows_common,
        merchant_face_1,
        merchant_face_2,
    ],
    [
        "ransom_broker_2",
        "Ransom_Broker",
        "Ransom_Broker",
        tf_hero | tf_randomize_face,
        0,
        reserved,
        fac_commoners,
        [itm_leather_boots_a, itm_tabard_a],
        def_attrib | level(5),
        wp(20),
        knows_common,
        merchant_face_1,
        merchant_face_2,
    ],
    [
        "ransom_broker_3",
        "Ransom_Broker",
        "Ransom_Broker",
        tf_hero | tf_randomize_face,
        0,
        reserved,
        fac_commoners,
        [itm_hose_a, itm_leather_vest],
        def_attrib | level(5),
        wp(20),
        knows_common,
        merchant_face_1,
        merchant_face_2,
    ],
    [
        "ransom_broker_4",
        "Ransom_Broker",
        "Ransom_Broker",
        tf_hero | tf_randomize_face,
        0,
        reserved,
        fac_commoners,
        [itm_leather_boots_b],
        def_attrib | level(5),
        wp(20),
        knows_common,
        merchant_face_1,
        merchant_face_2,
    ],
    [
        "ransom_broker_5",
        "Ransom_Broker",
        "Ransom_Broker",
        tf_hero | tf_randomize_face,
        0,
        reserved,
        fac_commoners,
        [itm_leather_boots_a, itm_gambeson],
        def_attrib | level(5),
        wp(20),
        knows_common,
        merchant_face_1,
        merchant_face_2,
    ],
    [
        "ransom_broker_6",
        "Ransom_Broker",
        "Ransom_Broker",
        tf_hero | tf_randomize_face,
        0,
        reserved,
        fac_commoners,
        [itm_poulaines_b, itm_blue_gambeson],
        def_attrib | level(5),
        wp(20),
        knows_common,
        merchant_face_1,
        merchant_face_2,
    ],
    [
        "ransom_broker_7",
        "Ransom_Broker",
        "Ransom_Broker",
        tf_hero | tf_randomize_face,
        0,
        reserved,
        fac_commoners,
        [itm_leather_boots_a, itm_red_gambeson],
        def_attrib | level(5),
        wp(20),
        knows_common,
        merchant_face_1,
        merchant_face_2,
    ],
    [
        "ransom_broker_8",
        "Ransom_Broker",
        "Ransom_Broker",
        tf_hero | tf_randomize_face,
        0,
        reserved,
        fac_commoners,
        [itm_leather_boots_a, itm_fur_coat],
        def_attrib | level(5),
        wp(20),
        knows_common,
        merchant_face_1,
        merchant_face_2,
    ],
    [
        "ransom_broker_9",
        "Ransom_Broker",
        "Ransom_Broker",
        tf_hero | tf_randomize_face,
        0,
        reserved,
        fac_commoners,
        [itm_poulaines_d, itm_leather_vest],
        def_attrib | level(5),
        wp(20),
        knows_common,
        merchant_face_1,
        merchant_face_2,
    ],
    [
        "ransom_broker_10",
        "Ransom_Broker",
        "Ransom_Broker",
        tf_hero | tf_randomize_face,
        0,
        reserved,
        fac_commoners,
        [itm_leather_boots_a, itm_leather_jacket],
        def_attrib | level(5),
        wp(20),
        knows_common,
        merchant_face_1,
        merchant_face_2,
    ],
    # Tavern traveler.
    [
        "tavern_traveler_1",
        "Traveller",
        "Traveller",
        tf_hero | tf_randomize_face,
        0,
        reserved,
        fac_commoners,
        [itm_leather_boots_a, itm_fur_coat],
        def_attrib | level(5),
        wp(20),
        knows_common,
        merchant_face_1,
        merchant_face_2,
    ],
    [
        "tavern_traveler_2",
        "Traveller",
        "Traveller",
        tf_hero | tf_randomize_face,
        0,
        reserved,
        fac_commoners,
        [itm_leather_boots_c, itm_tabard_a],
        def_attrib | level(5),
        wp(20),
        knows_common,
        merchant_face_1,
        merchant_face_2,
    ],
    [
        "tavern_traveler_3",
        "Traveller",
        "Traveller",
        tf_hero | tf_randomize_face,
        0,
        reserved,
        fac_commoners,
        [itm_leather_boots_a, itm_leather_vest],
        def_attrib | level(5),
        wp(20),
        knows_common,
        merchant_face_1,
        merchant_face_2,
    ],
    [
        "tavern_traveler_4",
        "Traveller",
        "Traveller",
        tf_hero | tf_randomize_face,
        0,
        reserved,
        fac_commoners,
        [itm_poulaines_a, itm_blue_gambeson],
        def_attrib | level(5),
        wp(20),
        knows_common,
        merchant_face_1,
        merchant_face_2,
    ],
    [
        "tavern_traveler_5",
        "Traveller",
        "Traveller",
        tf_hero | tf_randomize_face,
        0,
        reserved,
        fac_commoners,
        [itm_leather_boots_a],
        def_attrib | level(5),
        wp(20),
        knows_common,
        merchant_face_1,
        merchant_face_2,
    ],
    [
        "tavern_traveler_6",
        "Traveller",
        "Traveller",
        tf_hero | tf_randomize_face,
        0,
        reserved,
        fac_commoners,
        [itm_leather_shoes_a, itm_fur_coat],
        def_attrib | level(5),
        wp(20),
        knows_common,
        merchant_face_1,
        merchant_face_2,
    ],
    [
        "tavern_traveler_7",
        "Traveller",
        "Traveller",
        tf_hero | tf_randomize_face,
        0,
        reserved,
        fac_commoners,
        [itm_leather_boots_a, itm_leather_jacket],
        def_attrib | level(5),
        wp(20),
        knows_common,
        merchant_face_1,
        merchant_face_2,
    ],
    [
        "tavern_traveler_8",
        "Traveller",
        "Traveller",
        tf_hero | tf_randomize_face,
        0,
        reserved,
        fac_commoners,
        [itm_leather_boots_a, itm_tabard_a],
        def_attrib | level(5),
        wp(20),
        knows_common,
        merchant_face_1,
        merchant_face_2,
    ],
    [
        "tavern_traveler_9",
        "Traveller",
        "Traveller",
        tf_hero | tf_randomize_face,
        0,
        reserved,
        fac_commoners,
        [itm_leather_shoes_b, itm_fur_coat],
        def_attrib | level(5),
        wp(20),
        knows_common,
        merchant_face_1,
        merchant_face_2,
    ],
    [
        "tavern_traveler_10",
        "Traveller",
        "Traveller",
        tf_hero | tf_randomize_face,
        0,
        reserved,
        fac_commoners,
        [itm_leather_boots_a, itm_leather_jacket],
        def_attrib | level(5),
        wp(20),
        knows_common,
        merchant_face_1,
        merchant_face_2,
    ],
    # Tavern traveler.
    [
        "tavern_bookseller_1",
        "Book_Merchant",
        "Book_Merchant",
        tf_hero | tf_is_merchant | tf_randomize_face,
        0,
        reserved,
        fac_commoners,
        [
            itm_leather_boots_a,
            itm_fur_coat,
            itm_book_tactics,
            itm_book_persuasion,
            itm_book_wound_treatment_reference,
            itm_book_leadership,
            itm_book_intelligence,
            itm_book_training_reference,
            itm_book_surgery_reference,
        ],
        def_attrib | level(5),
        wp(20),
        knows_common,
        merchant_face_1,
        merchant_face_2,
    ],
    [
        "tavern_bookseller_2",
        "Book_Merchant",
        "Book_Merchant",
        tf_hero | tf_is_merchant | tf_randomize_face,
        0,
        reserved,
        fac_commoners,
        [
            itm_leather_boots_a,
            itm_fur_coat,
            itm_book_wound_treatment_reference,
            itm_book_leadership,
            itm_book_intelligence,
            itm_book_trade,
            itm_book_engineering,
            itm_book_weapon_mastery,
        ],
        def_attrib | level(5),
        wp(20),
        knows_common,
        merchant_face_1,
        merchant_face_2,
    ],
    # Tavern minstrel.
    [
        "tavern_minstrel_1",
        "Wandering Minstrel",
        "Minstrel",
        tf_hero
        | tf_randomize_face
        | tf_guarantee_shield
        | tf_guarantee_armor
        | tf_guarantee_boots,
        0,
        reserved,
        fac_commoners,
        [itm_leather_boots_a, itm_leather_jacket, itm_lute],
        def_attrib | level(5),
        wp(20),
        knows_common,
        merchant_face_1,
        merchant_face_2,
    ],  # lute
    [
        "tavern_minstrel_2",
        "Wandering Bard",
        "Minstrel",
        tf_hero
        | tf_randomize_face
        | tf_guarantee_shield
        | tf_guarantee_armor
        | tf_guarantee_boots,
        0,
        reserved,
        fac_commoners,
        [itm_leather_boots_a, itm_tunic_with_green_cape, itm_lyre],
        def_attrib | level(5),
        wp(20),
        knows_common,
        merchant_face_1,
        merchant_face_2,
    ],  # early harp/lyre
    [
        "tavern_minstrel_3",
        "Wandering Ashik",
        "Minstrel",
        tf_hero
        | tf_randomize_face
        | tf_guarantee_shield
        | tf_guarantee_armor
        | tf_guarantee_boots,
        0,
        reserved,
        fac_commoners,
        [itm_leather_boots_a, itm_nomad_robe, itm_lute],
        def_attrib | level(5),
        wp(20),
        knows_common,
        merchant_face_1,
        merchant_face_2,
    ],  # lute/oud or rebab
    [
        "tavern_minstrel_4",
        "Wandering Skald",
        "Minstrel",
        tf_hero
        | tf_randomize_face
        | tf_guarantee_shield
        | tf_guarantee_armor
        | tf_guarantee_boots,
        0,
        reserved,
        fac_commoners,
        [itm_leather_boots_a, itm_fur_coat, itm_lyre],
        def_attrib | level(5),
        wp(20),
        knows_common,
        merchant_face_1,
        merchant_face_2,
    ],  # No instrument or lyre
    [
        "tavern_minstrel_5",
        "Wandering Troubadour",
        "Minstrel",
        tf_hero
        | tf_randomize_face
        | tf_guarantee_shield
        | tf_guarantee_armor
        | tf_guarantee_boots,
        0,
        reserved,
        fac_commoners,
        [itm_leather_boots_a, itm_lute],
        def_attrib | level(5),
        wp(20),
        knows_common,
        merchant_face_1,
        merchant_face_2,
    ],  # Lute or Byzantine/Occitan lyra
]
