from module_troops_utils import *

# Consider splitting it into actual female troops and quests troops
# for caravan master, kidnapped girl, etc.
troops_female = [
    # FEMALE TROOPS BEGIN
    [
        "follower_woman",
        "Camp Follower",
        "Camp Follower",
        tf_female | tf_guarantee_armor,
        0,
        0,
        fac_commoners,
        [
            itm_bolts,
            itm_light_crossbow,
            itm_short_bow,
            itm_crossbow,
            itm_nordic_shield,
            itm_hide_covered_round_shield,
            itm_hatchet_a,
            itm_hatchet_b,
            itm_voulge,
            itm_fighting_pick,
            itm_club,
            itm_dress,
            itm_woolen_dress,
            itm_hose_d,
            itm_poulaines_d,
            itm_cervelliere_a,
        ],
        def_attrib | level(5),
        wp(70),
        knows_common,
        refugee_face1,
        refugee_face2,
    ],
    [
        "hunter_woman",
        "Huntress",
        "Huntresses",
        tf_female | tf_guarantee_armor,
        0,
        0,
        fac_commoners,
        [
            itm_bolts,
            itm_arrows,
            itm_light_crossbow,
            itm_short_bow,
            itm_crossbow,
            itm_nordic_shield,
            itm_hide_covered_round_shield,
            itm_hatchet_a,
            itm_hatchet_b,
            itm_voulge,
            itm_fighting_pick,
            itm_club,
            itm_dress,
            itm_regular_leather_jerkin_a,
            itm_hose_d,
            itm_poulaines_d,
            itm_cervelliere_a,
        ],
        def_attrib | level(10),
        wp(85),
        knows_common | knows_power_strike_1,
        refugee_face1,
        refugee_face2,
    ],
    [
        "fighter_woman",
        "Camp Defender",
        "Camp Defenders",
        tf_female | tf_guarantee_boots | tf_guarantee_armor,
        0,
        0,
        fac_commoners,
        [
            itm_bolts,
            itm_arrows,
            itm_light_crossbow,
            itm_short_bow,
            itm_crossbow,
            itm_fur_covered_shield,
            itm_hide_covered_round_shield,
            itm_hatchet_a,
            itm_voulge,
            itm_gray_hauberk_a,
            itm_hose_d,
            itm_poulaines_d,
            itm_cervelliere_a,
        ],
        def_attrib | level(16),
        wp(100),
        knows_common
        | knows_riding_3
        | knows_power_strike_2
        | knows_athletics_2
        | knows_ironflesh_1,
        refugee_face1,
        refugee_face2,
    ],
    [
        "sword_sister",
        "Sword Sister",
        "Sword Sisters",
        tf_female
        | tf_mounted
        | tf_guarantee_boots
        | tf_guarantee_armor
        | tf_guarantee_gloves
        | tf_guarantee_shield
        | tf_guarantee_horse,
        0,
        0,
        fac_commoners,
        [
            itm_bolts,
            itm_sword_medieval_b,
            itm_sword_khergit_3,
            itm_plate_covered_round_shield,
            itm_tab_shield_small_round_c,
            itm_crossbow,
            itm_full_plate_armor_a,
            itm_coat_of_plates,
            itm_sallet_c,
            itm_sallet_a_v5,
            itm_courser,
            itm_mail_boots_a,
            itm_leather_boots_a,
            itm_leather_gloves_a,
        ],
        def_attrib | level(22),
        wp(140),
        knows_common
        | knows_power_strike_3
        | knows_riding_5
        | knows_athletics_3
        | knows_ironflesh_2
        | knows_shield_2,
        refugee_face1,
        refugee_face2,
    ],
    [
        "refugee",
        "Refugee",
        "Refugees",
        tf_female | tf_guarantee_armor,
        0,
        0,
        fac_commoners,
        [
            itm_knife,
            itm_pitch_fork,
            itm_sickle,
            itm_hatchet_a,
            itm_club,
            itm_dress,
            itm_robe,
            itm_woolen_dress,
            itm_headcloth,
            itm_hose_d,
            itm_poulaines_d,
        ],
        def_attrib | level(1),
        wp(45),
        knows_common,
        refugee_face1,
        refugee_face2,
    ],
    [
        "peasant_woman",
        "Peasant Woman",
        "Peasant Women",
        tf_female | tf_guarantee_armor,
        0,
        0,
        fac_commoners,
        [
            itm_knife,
            itm_pitch_fork,
            itm_sickle,
            itm_hatchet_a,
            itm_club,
            itm_dress,
            itm_woolen_dress,
            itm_headcloth,
            itm_hose_d,
            itm_poulaines_d,
        ],
        def_attrib | level(1),
        wp(40),
        knows_common,
        refugee_face1,
        refugee_face2,
    ],
    # FEMALES TROOPS END
    [
        "caravan_master",
        "Caravan Master",
        "Caravan Masters",
        tf_mounted | tf_guarantee_boots | tf_guarantee_armor | tf_guarantee_horse,
        0,
        0,
        fac_commoners,
        [
            itm_sword_medieval_c,
            itm_peasant_fur_coat_a,
            itm_saddle_horse,
            itm_saddle_horse,
            itm_saddle_horse,
            itm_saddle_horse,
            itm_regular_shirt_c,
            itm_hose_d,
            itm_poulaines_d,
            itm_arming_cap_a,
        ],
        def_attrib | level(9),
        wp(100),
        knows_common | knows_riding_4 | knows_ironflesh_3,
        mercenary_face_1,
        mercenary_face_2,
    ],
    # KIDNAPPERS QUEST TROOPS BEGIN
    [
        "kidnapped_girl",
        "Kidnapped Girl",
        "Kidnapped Girls",
        tf_hero | tf_randomize_face | tf_female | tf_unmoveable_in_party_window,
        0,
        reserved,
        fac_commoners,
        [itm_dress, itm_poulaines_d],
        def_attrib | level(2),
        wp(50),
        knows_common | knows_riding_2,
        woman_face_1,
        woman_face_2,
    ],
    # KIDNAPPERS QUEST TROOPS END
]
