from module_troops_utils import *

troops_village = [
    # Village stores
    [
        "village_1_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_regular_shirt_d, itm_felt_a],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_2_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_robe],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_3_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_regular_shirt_d],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_4_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_regular_shirt_d, itm_arming_cap_a],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_5_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_regular_shirt_d],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_6_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_regular_shirt_d],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_7_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_fur_coat],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_8_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_regular_shirt_d, itm_felt_a],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_9_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_regular_shirt_d, itm_arming_cap_a],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_10_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_robe],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_11_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_regular_shirt_d],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_12_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_robe, itm_arming_cap_a],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_13_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_regular_shirt_d],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_14_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_robe],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_15_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_regular_shirt_d, itm_felt_a],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_16_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_regular_shirt_d],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_17_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_fur_coat],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_18_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_regular_shirt_d],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_19_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_regular_shirt_d],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_20_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_regular_shirt_d],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_21_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_robe, itm_arming_cap_a],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_22_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_fur_coat],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_23_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_regular_shirt_d, itm_felt_a],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_24_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_robe],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_25_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_fur_coat],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_26_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_robe, itm_arming_cap_a],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_27_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_regular_shirt_d, itm_felt_a],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_28_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_robe],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_29_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_regular_shirt_d],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_30_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_robe, itm_arming_cap_a],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_31_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_regular_shirt_d],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_32_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_robe],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_33_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_robe, itm_arming_cap_a],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_34_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_regular_shirt_d],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_35_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_robe],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_36_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_regular_shirt_d],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_37_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_robe],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_38_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_regular_shirt_d],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_39_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_regular_shirt_d],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_40_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_robe],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_41_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_regular_shirt_d],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_42_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_robe],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_43_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_robe, itm_arming_cap_a],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_44_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_regular_shirt_d],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_45_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_robe],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_46_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_regular_shirt_d],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_47_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_robe],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_48_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_regular_shirt_d],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_49_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_fur_coat],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_50_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_robe],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_51_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_robe, itm_arming_cap_a],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_52_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_regular_shirt_d],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_53_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_regular_shirt_d, itm_felt_a],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_54_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_robe],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_55_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_regular_shirt_d],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_56_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_robe, itm_arming_cap_a],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_57_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_regular_shirt_d, itm_felt_a],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_58_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_fur_coat],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_59_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_regular_shirt_d],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_60_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_robe, itm_arming_cap_a],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_61_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_robe, itm_arming_cap_a],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_62_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_regular_shirt_d],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_63_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_regular_shirt_d, itm_felt_a],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_64_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_robe],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_65_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_fur_coat],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_66_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_robe, itm_arming_cap_a],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_67_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_regular_shirt_d, itm_felt_a],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_68_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_robe],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_69_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_regular_shirt_d],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_70_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_robe, itm_arming_cap_a],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_71_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_robe, itm_arming_cap_a],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_72_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_regular_shirt_d],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_73_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_regular_shirt_d, itm_felt_a],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_74_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_robe],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_75_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_regular_shirt_d],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_76_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_fur_coat, itm_arming_cap_a],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_77_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_regular_shirt_d, itm_felt_a],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_78_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_robe],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_79_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_regular_shirt_d],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_80_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_robe, itm_arming_cap_a],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_81_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_regular_shirt_d],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_82_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_robe],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_83_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_fur_coat, itm_arming_cap_a],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_84_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_regular_shirt_d],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_85_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_robe],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_86_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_regular_shirt_d],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_87_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_robe],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_88_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_fur_coat],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_89_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_regular_shirt_d],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_90_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_91_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_92_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_robe],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_93_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_arming_cap_a],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_94_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_95_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_96_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_regular_shirt_d],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_97_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_98_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_99_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_regular_shirt_d],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_100_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_101_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_102_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_robe],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_103_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_arming_cap_a],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_104_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_regular_shirt_d],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_105_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_106_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_regular_shirt_d],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_107_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_robe],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_108_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_109_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
    [
        "village_110_elder",
        "Village_Elder",
        "{!}village_1_elder",
        tf_hero | tf_randomize_face | tf_is_merchant,
        0,
        0,
        fac_commoners,
        [itm_hose_d, itm_robe],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        man_face_old_1,
        man_face_older_2,
    ],
]
