from module_troops_utils import *

troops_neutral = [
    [
        "player",
        "Player",
        "Player",
        tf_hero | tf_unmoveable_in_party_window,
        no_scene,
        reserved,
        fac_player_faction,
        [],
        str_4 | agi_4 | int_4 | cha_4,
        wp(15),
        0,
        0x000000018000000136DB6DB6DB6DB6DB00000000001DB6DB0000000000000000,
    ],
    [
        "multiplayer_profile_troop_male",
        "multiplayer_profile_troop_male",
        "multiplayer_profile_troop_male",
        tf_hero | tf_guarantee_all,
        0,
        0,
        fac_commoners,
        [itm_shirt, itm_leather_shoes_a],
        0,
        0,
        0,
        0x000000018000000136DB6DB6DB6DB6DB00000000001DB6DB0000000000000000,
    ],
    [
        "multiplayer_profile_troop_female",
        "multiplayer_profile_troop_female",
        "multiplayer_profile_troop_female",
        tf_hero | tf_female | tf_guarantee_all,
        0,
        0,
        fac_commoners,
        [itm_shirt, itm_leather_shoes_a],
        0,
        0,
        0,
        0x000000018000000136DB6DB6DB6DB6DB00000000001DB6DB0000000000000000,
    ],
    [
        "temp_troop",
        "Temp Troop",
        "Temp Troop",
        tf_hero,
        no_scene,
        reserved,
        fac_commoners,
        [],
        def_attrib,
        0,
        knows_common | knows_inventory_management_10,
        0,
    ],
    ####################################################################################################################
    # Troops before this point are hardwired into the game and their order should not be changed!
    ####################################################################################################################
    [
        "find_item_cheat",
        "find_item_cheat",
        "find_item_cheat",
        tf_hero | tf_is_merchant,
        no_scene,
        reserved,
        fac_commoners,
        [],
        def_attrib,
        0,
        knows_common | knows_inventory_management_10,
        0,
    ],
    [
        "random_town_sequence",
        "Random Town Sequence",
        "Random Town Sequence",
        tf_hero,
        no_scene,
        reserved,
        fac_commoners,
        [],
        def_attrib,
        0,
        knows_common | knows_inventory_management_10,
        0,
    ],
    [
        "tournament_participants",
        "Tournament Participants",
        "Tournament Participants",
        tf_hero,
        no_scene,
        reserved,
        fac_commoners,
        [],
        def_attrib,
        0,
        knows_common | knows_inventory_management_10,
        0,
    ],
    [
        "tutorial_maceman",
        "Maceman",
        "Maceman",
        tf_guarantee_boots | tf_guarantee_armor,
        no_scene,
        reserved,
        fac_commoners,
        [itm_tutorial_club, itm_shirt, itm_leather_shoes_a],
        str_6 | agi_6 | level(1),
        wp(50),
        knows_common,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "tutorial_archer",
        "Archer",
        "Archer",
        tf_guarantee_boots | tf_guarantee_armor | tf_guarantee_ranged,
        no_scene,
        reserved,
        fac_commoners,
        [itm_tutorial_short_bow, itm_tutorial_arrows, itm_shirt, itm_leather_shoes_a],
        str_6 | agi_6 | level(5),
        wp(100),
        knows_common | knows_power_draw_4,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "tutorial_swordsman",
        "Swordsman",
        "Swordsman",
        tf_guarantee_boots | tf_guarantee_armor,
        no_scene,
        reserved,
        fac_commoners,
        [itm_tutorial_sword, itm_shirt, itm_leather_shoes_a],
        str_6 | agi_6 | level(5),
        wp(80),
        knows_common,
        mercenary_face_1,
        mercenary_face_2,
    ],
    # ========================================================================================================
    # Training partners
    # ========================================================================================================
    [
        "novice_fighter",
        "Novice Fighter",
        "Novice Fighters",
        tf_guarantee_boots | tf_guarantee_armor,
        no_scene,
        reserved,
        fac_commoners,
        [itm_short_tunic, itm_poulaines_b],
        str_6 | agi_6 | level(5),
        wp(60),
        knows_common,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "regular_fighter",
        "Regular Fighter",
        "Regular Fighters",
        tf_guarantee_boots | tf_guarantee_armor,
        no_scene,
        reserved,
        fac_commoners,
        [itm_short_tunic, itm_poulaines_b],
        str_8 | agi_8 | level(11),
        wp(90),
        knows_common
        | knows_ironflesh_1
        | knows_power_strike_1
        | knows_athletics_1
        | knows_riding_1
        | knows_shield_2,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "veteran_fighter",
        "Veteran Fighter",
        "Veteran Fighters",
        tf_guarantee_boots | tf_guarantee_armor,
        no_scene,
        0,
        fac_commoners,
        [itm_short_tunic, itm_poulaines_b],
        str_10 | agi_10 | level(17),
        wp(110),
        knows_common
        | knows_ironflesh_3
        | knows_power_strike_2
        | knows_athletics_2
        | knows_riding_2
        | knows_shield_3,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "champion_fighter",
        "Champion Fighter",
        "Champion Fighters",
        tf_guarantee_boots | tf_guarantee_armor,
        no_scene,
        reserved,
        fac_commoners,
        [itm_short_tunic, itm_poulaines_b],
        str_12 | agi_11 | level(22),
        wp(140),
        knows_common
        | knows_ironflesh_4
        | knows_power_strike_3
        | knows_athletics_3
        | knows_riding_3
        | knows_shield_4,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "arena_training_fighter_1",
        "Novice Fighter",
        "Novice Fighters",
        tf_guarantee_boots | tf_guarantee_armor,
        no_scene,
        reserved,
        fac_commoners,
        [itm_short_tunic, itm_poulaines_b],
        str_6 | agi_6 | level(5),
        wp(60),
        knows_common,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "arena_training_fighter_2",
        "Novice Fighter",
        "Novice Fighters",
        tf_guarantee_boots | tf_guarantee_armor,
        no_scene,
        reserved,
        fac_commoners,
        [itm_short_tunic, itm_poulaines_b],
        str_7 | agi_6 | level(7),
        wp(70),
        knows_common,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "arena_training_fighter_3",
        "Regular Fighter",
        "Regular Fighters",
        tf_guarantee_boots | tf_guarantee_armor,
        no_scene,
        reserved,
        fac_commoners,
        [itm_short_tunic, itm_poulaines_b],
        str_8 | agi_7 | level(9),
        wp(80),
        knows_common,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "arena_training_fighter_4",
        "Regular Fighter",
        "Regular Fighters",
        tf_guarantee_boots | tf_guarantee_armor,
        no_scene,
        reserved,
        fac_commoners,
        [itm_short_tunic, itm_poulaines_b],
        str_8 | agi_8 | level(11),
        wp(90),
        knows_common,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "arena_training_fighter_5",
        "Regular Fighter",
        "Regular Fighters",
        tf_guarantee_boots | tf_guarantee_armor,
        no_scene,
        reserved,
        fac_commoners,
        [itm_short_tunic, itm_poulaines_b],
        str_9 | agi_8 | level(13),
        wp(100),
        knows_common,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "arena_training_fighter_6",
        "Veteran Fighter",
        "Veteran Fighters",
        tf_guarantee_boots | tf_guarantee_armor,
        no_scene,
        reserved,
        fac_commoners,
        [itm_short_tunic, itm_poulaines_b],
        str_10 | agi_9 | level(15),
        wp(110),
        knows_common,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "arena_training_fighter_7",
        "Veteran Fighter",
        "Veteran Fighters",
        tf_guarantee_boots | tf_guarantee_armor,
        no_scene,
        reserved,
        fac_commoners,
        [itm_short_tunic, itm_poulaines_b],
        str_10 | agi_10 | level(17),
        wp(120),
        knows_common,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "arena_training_fighter_8",
        "Veteran Fighter",
        "Veteran Fighters",
        tf_guarantee_boots | tf_guarantee_armor,
        no_scene,
        reserved,
        fac_commoners,
        [itm_short_tunic, itm_poulaines_b],
        str_11 | agi_10 | level(19),
        wp(130),
        knows_common,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "arena_training_fighter_9",
        "Champion Fighter",
        "Champion Fighters",
        tf_guarantee_boots | tf_guarantee_armor,
        no_scene,
        reserved,
        fac_commoners,
        [itm_short_tunic, itm_poulaines_b],
        str_12 | agi_11 | level(21),
        wp(140),
        knows_common,
        mercenary_face_1,
        mercenary_face_2,
    ],
    [
        "arena_training_fighter_10",
        "Champion Fighter",
        "Champion Fighters",
        tf_guarantee_boots | tf_guarantee_armor,
        no_scene,
        reserved,
        fac_commoners,
        [itm_short_tunic, itm_poulaines_b],
        str_12 | agi_12 | level(23),
        wp(150),
        knows_common,
        mercenary_face_1,
        mercenary_face_2,
    ],
    # ========================================================================================================
    # Cattle
    # ========================================================================================================
    [
        "cattle",
        "Cattle",
        "Cattle",
        0,
        no_scene,
        reserved,
        fac_neutral,
        [],
        def_attrib | level(1),
        wp(60),
        0,
        mercenary_face_1,
        mercenary_face_2,
    ],
]
